### ISSUE TITLE
[Windows] [Win7] Application can't be pinned to the taskbar

### ISSUE THREAD

**Issue by ngugcx** [wangwenx190/framelesshelper#10]
Win7上，打开例子程序，在任务栏上右键，“固定到任务栏”。
程序关闭后，任务栏图标没有固定，消失了。

**Comment by wangwenx190** [comment]
我在win10上试了试，没问题。你那边有试过win10吗

**Comment by ngugcx** [comment]
Win10没问题。

**Comment by wangwenx190** [comment]
暂时不明白为什么会这样

**Comment by wangwenx190** [comment]
我在Win7上成功复现了，确实无法固定，暂时不知道为什么。

**Comment by wangwenx190** [comment]
Win8.1和Win10都可以正常固定，只有Win7不行，还是不知道原因

**Comment by wangwenx190** [comment]
感觉不是这个repo导致的问题，先close了，有问题再重新open
