### ISSUE TITLE
当在主窗口中嵌入一个QGLWidget后，标题栏就不能命中，继而不能拖动。

### ISSUE THREAD

**Issue by glimix** [wangwenx190/framelesshelper#103]

**Comment by glimix** [comment]
我注释掉了
`
    if (!QCoreApplication::testAttribute(Qt::AA_DontCreateNativeWidgetSiblings))
        QCoreApplication::setAttribute(Qt::AA_DontCreateNativeWidgetSiblings);
`
QOpenGLWidget可以使用了，QGLWiget不能使用。
魔改的glfw窗口嵌入进去，与QGLWidget一样，标题栏就不能移动了。
多半是我的问题了。

**Comment by wangwenx190** [comment]
试试wip分支呢，wip分支更换实现方式了

**Comment by wangwenx190** [comment]
QGLWidget确实有兼容性问题。标题栏不能拖动应该是事件被QGLWidget或者glfw窗口拦截了，这个不好解决。不过1.x版本不会大改了，你可以试试wip分支有没有改善。

**Comment by JulienMaille** [comment]
Are you far from finishing your wip branch? I'm tempted to try but it might be too soon

**Comment by wangwenx190** [comment]
> Are you far from finishing your wip branch? I'm tempted to try but it might be too soon

For the wip branch, the Windows implementation is mostly done, there won't be any large API or architechtural changes anymore, in the next few days I'll focus on fixing bugs and minor internal tweaks, you can start trying the new code already. The public API for Qt Widgets is settled and most likely won't changed, but I'm still thinking about the Qt Quick API, so for now it's better not to use the Qt Quick parts although it can work normally. The linux and macOS implementation is still missing, but they will be added before I officially released the next version.

**Comment by wangwenx190** [comment]
Feedbacks are really welcome

**Comment by wangwenx190** [comment]
QGLWidget不被支持，请迁移到Qt官方推荐的QOpenGLWidget。先关闭了，有问题可以再重新打开
