### ISSUE TITLE
【Win11】Quick例子多屏幕不同dpi场景下，移动窗口切换屏幕时窗口大小不正确

### ISSUE THREAD

**Issue by qsyttkx** [wangwenx190/framelesshelper#107]
场景：Win11，一块屏幕4k 200%缩放，一块屏幕1080p 100%缩放，Qt6.2

问题：移动窗口从一个窗口到另一个窗口时，dpi改变导致的窗口resize大小不正确。

似乎作者在这种场景下其实有做处理（在`void FramelessWindowsManager::addWindow(QWindow *window)`中），如果不做这个处理每次Qt在resize时会在原来的基础上加上原生窗口的边框大小，导致窗口越来越大。

但是难受的是切换屏幕时Qt内部可能会触发多次resize，所以加上这个处理依然会存在这个问题（在移动到另一个屏幕上时，先按住鼠标等一会儿再放开就很容易触发）。

我试了下在QML里把window的最大宽高和最小宽高设置成一样的（禁用resize）之后，移动窗口就没有问题了。

也许可以考虑在拖动的过程中，临时禁掉窗口的resize，等拖动完毕之后再还原回来。🙂

**Comment by wangwenx190** [comment]
禁用resize确实是一个办法，值得尝试。
试试wip分支的代码呢？wip分支改进了很多。

**Comment by qsyttkx** [comment]
试了下wip分支目前还不是很稳定，切换显示器的时候出现了一些闪烁。
无论如何非常感谢~

**Comment by wangwenx190** [comment]
最新代码应该是没这个问题了
