### ISSUE TITLE
可不可以自定义标题栏的高度

### ISSUE THREAD

**Issue by SineStriker** [wangwenx190/framelesshelper#110]
Windows版的源码里，注意到处理WM_NCHITTEST事件时使用的titleBarSize是强制使用系统的，能不能自定义一个值。比如改成布局顶端的Widget的高度。

**Comment by SineStriker** [comment]
是不是只要在自定义titleBar的resizeEvent里调用FramelessHelperWindowsManager::setTitleBarHeight就行了，貌似还要除以一个缩放比率。

**Comment by wangwenx190** [comment]
试试wip分支呢，wip分支更改了实现方式，可以自由设置标题栏widget，高度、形状和位置都很自由

**Comment by wangwenx190** [comment]
> 是不是只要在自定义titleBar的resizeEvent里调用FramelessHelperWindowsManager::setTitleBarHeight就行了，貌似还要除以一个缩放比率。

不是在resizeEvent里，这个数值要在窗口刚初始化的时候就设置，比如构造函数，或者你调用FramelessHelperWindowsManager::addWindow的地方

**Comment by wangwenx190** [comment]
缩放比率不用管，内部会自动处理

**Comment by SineStriker** [comment]
> > 是不是只要在自定义titleBar的resizeEvent里调用FramelessHelperWindowsManager::setTitleBarHeight就行了，貌似还要除以一个缩放比率。
> 
> 不是在resizeEvent里，这个数值要在窗口刚初始化的时候就设置，比如构造函数，或者你调用FramelessHelperWindowsManager::addWindow的地方

我试过了没问题了，另外遇到一个比较严重的问题。Qt里面只要WindowFlags里指定了Dialog就能在指定parent的情况下不嵌入parent的窗口，但是如果对frameless的dialog指定了parent，dialog里整个区域都无法响应鼠标单击事件，都被当成非客户区了。
