### ISSUE TITLE
[Feature Request] [Windows] Add the snap layout feature introduced in Windows 11

### ISSUE THREAD

**Issue by wangwenx190** [wangwenx190/framelesshelper#115]

**Comment by wangwenx190** [comment]
There's much hope to get the snap layout released within next week. The implementation is almost done now and I'm currently finishing the details and testing it locally.

**Comment by wangwenx190** [comment]
@JulienMaille  The snap layout is now fully supported by FramelessHelper, can you test the code from the `main` branch? If no serious issues are found, I'll release it as the 2.1 version.

**Comment by JulienMaille** [comment]
I'll do my best but I'm quite busy right now. Have you implemented it in the Mainwindow example?

**Comment by wangwenx190** [comment]
No need to hurry, bro! I've tested the code on my PC locally already and everything seems to work fine.

> Have you implemented it in the Mainwindow example?

Snap layout is supported by all the examples, we should show as many features as possible in the demo applications anyway :)

**Comment by wangwenx190** [comment]
Done in 2.1
