### ISSUE TITLE
[Feature Request] [All platforms] Add cross-platform system menu

### ISSUE THREAD

**Issue by wangwenx190** [wangwenx190/framelesshelper#116]
Support both Qt Widgets and Qt Quick
Support both light theme and dark theme
Can be triggered by right-clicking on the title bar area or pressing the shortcut (ALT + SPACE)

**Comment by nocanstillbb** [comment]
qtquick1 menu 混合qquick 2 item可以实现这个功能 , 我在把quick1 menu封闭成qquick 2 自定义控件后可以实现,需要把qqlication设置为qapplication,菜单样式才能生效, 在菜单样式中可以嵌入qquick2 control, 不过比较麻烦.
通过阅读qt源码 ,  可以在 aboutshow信号中, 通过信号连接, 获得qquick control 1 menu的window, 在弹菜单前用c++做一些窗口的控制.

![image](https://user-images.githubusercontent.com/22405678/181876192-1ba34c4d-c016-4582-8b3b-8a6092846182.png)
如果需要,我可以花点时间 提一个Pr

**Comment by nocanstillbb** [comment]
哦我理解错了,你说的是sysetm menu不是menu.
mac os ,我正在是寻找保留mac os左上三个按钮的无边框找到这边来的

**Comment by wangwenx190** [comment]
>
> 哦我理解错了,你说的是sysetm menu不是menu.
>

是的，是系统菜单，不是普通的右键菜单。

>
> mac os ,我正在是寻找保留mac os左上三个按钮的无边框找到这边来的
>

保留三个按钮很简单吧，我都是专门把它们去掉，为什么要保留？

**Comment by nocanstillbb** [comment]
> > 哦我理解错了,你说的是sysetm menu不是menu.
> 
> 是的，是系统菜单，不是普通的右键菜单。
> 
> > mac os ,我正在是寻找保留mac os左上三个按钮的无边框找到这边来的
> 
> 保留三个按钮很简单吧，我都是专门把它们去掉，为什么要保留？

因为我打算抄一个网难云音乐练练手,我注意到网易云左上有三个按钮,但没有system menu,不知道是不是伪造的三个按钮,
如果是伪造的,这里面是否有什么技术难点,导致他们这样做
![HC 0))IEQI509A$(2DE3I%T](https://user-images.githubusercontent.com/22405678/181880724-a6ec5b52-c50f-47dc-96f3-10f053ad49f5.png)

![CXWSX)%G3LBM@ GWB35SJ%V](https://user-images.githubusercontent.com/22405678/181880790-c6a6d2aa-fe41-4f67-bbcd-d75a61bab443.png)

**Comment by wangwenx190** [comment]
这个我不太清楚，但我觉得应该不是伪造的，至于为什么没有那个菜单，可能是受到了styleMask的影响，可能网易云有什么特别的设置吧

**Comment by nocanstillbb** [comment]
好的  嗯 马上会做一些实验，谢了发自我的荣耀手机-------- 原始邮件 --------发件人： Yuhang Zhao ***@***.***>日期： 2022年7月30日周六 下午3:54收件人： wangwenx190/framelesshelper ***@***.***>抄送： huang bin bin ***@***.***>, Comment ***@***.***>主    题： Re: [wangwenx190/framelesshelper] [Feature Request] [All platforms] Add cross-platform system menu (Issue #116)

这个我不太清楚，但我觉得应该不是伪造的，至于为什么没有那个菜单，可能是受到了styleMask的影响，可能网易云有什么特别的设置吧

**Comment by wangwenx190** [comment]
应该不需要了，目前已经能在三个平台都弹出原生菜单
