### ISSUE TITLE
Qt版本过高，导致编译不过

### ISSUE THREAD

**Issue by lsnbing** [wangwenx190/framelesshelper#12]
win10+qt5.12.4
framelessquickhelper.h 中Q_DISABLE_COPY_MOVE不可用

建议在readme中写清mac的qt支持得版本

范例代码：data.titlebarHeight = 30;，拼写错误

顺便问下，qt5.15的无边框特性够完善吗？

**Comment by wangwenx190** [comment]
>
> win10+qt5.12.4
> framelessquickhelper.h 中Q_DISABLE_COPY_MOVE不可用
> 

不好意思，这个宏5.13才引入，我刚刚已经修复了这个问题。代码中没有用到很新的API，只要不低于5.6，都是能编译运行的。

>
> 建议在readme中写清mac的qt支持得版本
> 

Linux和macOS的代码用的是Qt 5.15新引入的`startSystemMove`和`startSystemResize`这两个API，所以版本固定死了，不能低于5.15。这个API是跨平台的，支持Win+Linux+macOS，如果不用这两个API，要针对每个平台自行实现，过于复杂。为了简便，就直接用了。unix平台的自述文件是另一个，`README_unix.md`，里面有版本要求。

>
> 范例代码：data.titlebarHeight = 30;，拼写错误
> 

不好意思了，这个变量中途改了名，忘记更新文档了。已经修复。

>
> 顺便问下，qt5.15的无边框特性够完善吗？
>

你指的是Qt本身对无边框的支持吗？Qt的话，由于5.15引入了我上面提到的那两个API，所以无边框特别好做了，但在Windows上效果很不理想，因为去掉边框还是用FramelessWindowHint，而这个flag在Windows平台会导致窗口变成弹出窗口，正常窗口该有的特性都没了。如果不在意的话倒无所谓，但如果要做到接近完美，就一定不能这样干，要和这个repo一样，拦截win32消息自行处理。在Linux和macOS上比Windows强一些，因为很多东西都是窗口管理器负责的，至少窗口动画是不会丢掉的，这和Windows不一样。但由于我自己没有mac，所以没法实际测试macOS上的效果，只是从理论上推测。

**Comment by wangwenx190** [comment]
那个宏的问题已经解决了，现在应该只要不低于5.6都能编译了。

**Comment by wangwenx190** [comment]
所有提到的问题都已经解决了，issue我先关了。如果再发现新的问题，你可以重新打开这个issue，或者再开一个新的。

**Comment by lsnbing** [comment]
试了一下，仅仅是提供了多了两个api，还有很多工作需要处理。

对以上的回答和工作表示感谢！

**Comment by wangwenx190** [comment]
>
> 试了一下，仅仅是提供了多了两个api，还有很多工作需要处理。
> 

这两个API是完全跨平台的，支持所有主流桌面平台，我看过这个特性的补丁，代码大几千行，如果你真要完全自己去做，很不划算的。有了这两个API，工作量已经很小了，我那个UNIX平台的代码，一共才400行左右，就已经比较完善了，这在以前的版本是完全做不到的。

>
> 对以上的回答和工作表示感谢！
>

如果能帮到你，我也很高兴。如果遇到了新的问题，或者有了新的需求，欢迎开新的issue，大家一起讨论。
