### ISSUE TITLE
question about license

### ISSUE THREAD

**Issue by micpub** [wangwenx190/framelesshelper#124]
Hello, i am thinking about using this lib in my app however im not sure if the license is right - version 2.0 should be MIT according to you but from what i can see you are using these files inside:

qtx11extras.cpp
qtx11extras_p.h
qwinregistry.cpp
qwinregistry_p.h

and these files are internal qt files released under either commercial / lgpl ver.X / gpl ver.X  licenses - and those licenses cant be mixed(with MIT) - so in reality it makes your whole library gpl / lgpl.

i think it should be stated somewhere - as its very important - im trying to avoid lgpl where possible.
is there a way to kick-out that code? or any plans? to make it truly MIT lib?

**Comment by wangwenx190** [comment]
Hi, sorry for the confusion. 

The `QWinRegistry` class was introduced in Qt 5.14, and the `QX11Info` class was introduced in Qt 5.1. The `QX11Info` class in Qt5 was in a separate module called `Qt X11Extras`, and this module was removed in Qt 6.0 but the content of it was added back in Qt 6.2 to QtCore as a private feature. I've checked the source code of it from Qt 5.15.2 and Qt dev (currently will be Qt 6.4), and found that the code was not touched, so in reality the `QX11Info` class was just moved to a different place. And I use preprocessor macros to control whether to use the copy in this project or the original one in Qt. The only chance to make `qwinregistry_p.h` and `qwinregistry.cpp` compile into this library is (1) building for the Windows platform and (2) you are using a Qt of some version lower than 5.14. The condition for `qtx11extras_p.h` and `qtx11extras.cpp` is (1) building for the Linux platform and (2) you are using a Qt of some version below 6.2 (including Qt5). I didn't actually read the content of the GPL/LGPL license text, but I guess it won't break our MIT license if the source code are not compiled into our library?

> is there a way to kick-out that code?

Of course. The `QWinRegistry` is just a convenient helper class to access Windows registry, we can replace it with the public `QSettings` instead, if you really want to get rid of that code. And we can get rid of `qtx11extras_p.h` and `qtx11extras.cpp` by using Qt's own code, for example, for Qt5 we can just use the `X11Extras` module, for Qt 6.2 and greater we can use the QtCore feature directly. But there are no good replacement for Qt versions between 6.0 and 6.2. However, `QX11Info` is just a conenient helper of some QPA functions, we can totally remove the usage of `QX11Info` by calling the QPA functions directly by ourself.

Currently there are no plans to do the above migration process, but you can make a PR for this and I'll surely accept it.

**Comment by wangwenx190** [comment]
OK, I think I may have some time next week. I'll do the above migration in next week, if I have enough time. Anyway, thanks for your suggestion about the license issue!

**Comment by wangwenx190** [comment]
All the bundled Qt classes have been removed in main branch, I'll release the 2.1 version based on the latest code of the main branch soon.
