### ISSUE TITLE
Quick 若使用自定义的Window 而不是使用FramelessWindow 

### ISSUE THREAD

**Issue by zengdapang** [wangwenx190/framelesshelper#125]
如何像1.x版本一样，在使用自定义的Window时使用 removeWindowFrame( )实现无边框？2.0版本 好像不支持这样做，若只能使用FramelessWindow ，好像有些局限性？

**Comment by wangwenx190** [comment]
我可以给2.0添加接口，重新开放这个函数

**Comment by zengdapang** [comment]
感谢您及时的的回复，个人觉得开放此接口对于Quick来说更加灵活。

**Comment by wangwenx190** [comment]
已经在main分支完成此项改动，将会在近期基于main分支的最新代码发布2.1版本
