### ISSUE TITLE
VS2017+QT5.12.12编译不过

### ISSUE THREAD

**Issue by luoshengke** [wangwenx190/framelesshelper#126]
使用 qmke -project导出 .pro , 打开工程编译不过, 求助

**Comment by wangwenx190** [comment]
具体报什么错啊，你不贴出来，我怎么知道哪里的问题

**Comment by pre361** [comment]
**同样遇到这个问题，博主迭代版本不做代码测试的吗。。。。。**

**Comment by wangwenx190** [comment]
5.12确实没法编译，能上5.15尽量上5.15吧

**Comment by pre361** [comment]
好的

**Comment by pre361** [comment]
加油~~~你最棒！

**Comment by wangwenx190** [comment]
Windows平台确实没法用5.12编译，如果要支持的话改动较大，因此先放弃了，建议使用5.15
