### ISSUE TITLE
macOS Mojave编译问题

### ISSUE THREAD

**Issue by ifpelset** [wangwenx190/framelesshelper#129]
macOS编译找不到符号。
系统版本：Mojave
Qt版本：5.15.2
可能的解决方法：
Core模块CMakeList.txt中添加
if(APPLE)
    find_library(AppKit AppKit)
    target_link_libraries(${SUB_PROJ_NAME} PRIVATE
        ${AppKit}
    )
endif()

顺便问一句，macOS不支持resize窗口吗？

**Comment by wangwenx190** [comment]
我只测了macOS 12上的行为，可以正常编译，窗口也能resize

**Comment by wangwenx190** [comment]
这个跟Qt版本有关系吗，要不要试试Qt6？macOS平台我只测过Qt6

**Comment by wangwenx190** [comment]
听说macOS 10.15上也是正常的

**Comment by ifpelset** [comment]
那我这边试下Qt6。

**Comment by ifpelset** [comment]
测试了下Qt6，demo窗口一样不能resize。

**Comment by wangwenx190** [comment]
那大概是系统版本的问题了，我想办法搞个环境测试一下

**Comment by wangwenx190** [comment]
编译问题应该是解决了，resize的问题如果确实存在的话也不好解决，因此先close了
