### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by Caprey** [wangwenx190/framelesshelper#13]

**Comment by Caprey** [comment]
![T2](https://user-images.githubusercontent.com/28674556/82277635-f7e26e80-99ba-11ea-8738-ea64454ff32b.gif)

**Comment by wangwenx190** [comment]
It's hard to know what caused this issue.

Can you provide a minimum re-produciable project?

**Comment by Caprey** [comment]
[Qt-Advanced-Docking-System-3.4.0 error.zip](https://github.com/wangwenx190/framelesshelper/files/4647922/Qt-Advanced-Docking-System-3.4.0.error.zip)
![image](https://user-images.githubusercontent.com/28674556/82278473-e00bea00-99bc-11ea-8bef-af38c1cadc0b.png)

**Comment by wangwenx190** [comment]
既然是国人，就不要用英语交流了，我的英语水平也不怎么样。

你发的复现工程我这边测了下，运行挺正常的，没发现你gif里那个问题。不过我测的是最新的代码，不知道你那边用的是什么时候的版本。

我这边的测试环境是Qt 5.15，MSVC 2019，Win10 2004

我要额外提一句，`moveWindowToDesktopCenter`这个函数是居中窗口用的，你在这种窗口里调用这个接口不太合适吧？

**Comment by wangwenx190** [comment]
目前已知在5.6上有些问题，是qt自身的原因，不知道你用的是不是5.6

**Comment by Caprey** [comment]
我使用的是5.14.2，那我升级一下版本试看看

**Comment by Caprey** [comment]
或者你编译一个exe，给我运行看看

**Comment by wangwenx190** [comment]
5.15正式版还没发布，我用的是测试版。

> 或者你编译一个exe，给我运行看看

行

**Comment by wangwenx190** [comment]
你发给我的那个工程，我把所有窗口都拖出来试了试，发现有几个窗口确实会出现你gif里的问题，但大部分还是没问题的。是不是那几个窗口有什么特殊的地方？

**Comment by wangwenx190** [comment]
我就暂时先不录屏了。

既然大部分窗口都没问题，就说明有问题的那几个窗口和其他窗口不一样，大概是设置了什么属性，影响到了无边框代码的执行，这个还是你自己调试一下吧，我对那个Qt Advanced Docking System不够熟悉，没法短时间内做出具体的判断。

**Comment by wangwenx190** [comment]
设置了`QCoreApplication::setAttribute(Qt::AA_DontCreateNativeWidgetSiblings);`应该就不存在这个问题了。
https://github.com/wangwenx190/framelesshelper/blob/0debbb890fdbe070ab959da7fd3d058db1fe4d6f/examples/QWidget/main.cpp#L35
