### ISSUE TITLE
Compilation issues with 2.1

### ISSUE THREAD

**Issue by JulienMaille** [wangwenx190/framelesshelper#130]
I'm trying to update my project to latest code.
With msvc2022 and c++17 flag, I have weird errors on missing std functions:
```
36>D:\FramelessHelper\src\core\framelesshelper_win.cpp(129,52): error C2039: 'optional': is not a member of 'std'
36>D:\FramelessHelper\src\core\framelesshelper_win.cpp(131,14): error C2065: 'exclude': undeclared identifier
36>D:\FramelessHelper\src\widgets\framelesswidgetshelper.cpp(248,30): error C3861: 'instance': identifier not found
```
The other error I have is:
`36>D:\FramelessHelper\src\widgets\framelesswidgetshelper.cpp(248,13): error C2653: 'FramelessConfig': is not a class or namespace name
`

For information I don't use CMake so I had to adapte a .pri file, maybe I forgot something there.

**Comment by wangwenx190** [comment]
really sorry to hear that, it looks like your are missing some headers. 2.1 added some headers and renamed some headers, if you are not using the official CMake project files, you may be missing some pieces ...

**Comment by wangwenx190** [comment]
You can make use of the discord channel, so we can communicate in real time
