### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by swq0553** [wangwenx190/framelesshelper#133]
在utils.cpp和utils_win.cpp的include中是否可以不使用
#include <QtCore/private/qsystemlibrary_p.h>
#include <QtGui/qpa/qplatformwindow.h>
 他们似乎在更下层，不在$(Qt_INCLUDEPATH_)宏所包含范围，在切换qt版本时不方便

**Comment by wangwenx190** [comment]
什么意思？你的Qt版本是什么？只要你用的Qt版本不是很老，这两个文件都是存在的
