### ISSUE TITLE
qml中导入后QtCreator无法识别，且无语法提示。

### ISSUE THREAD

**Issue by zengdapang** [wangwenx190/framelesshelper#135]
![屏幕截图 2022-05-31 185640](https://user-images.githubusercontent.com/50150904/171158186-a0e41706-d7f3-478d-aff9-5ce2414cf731.png)
编译为动态库后 

    // 无框注册
    FramelessHelper::Core::initialize();
    //
    QGuiApplication app(argc, argv);
    QQmlApplicationEngine engine;
    FramelessHelper::Quick::registerTypes(&engine);

QtCreator无法识别，qml中也没有语法提示，但是代码可以正常运行。

FramelessHelper::Quick::registerTypes(&engine);
同时注册时 附带了一个警告 
qt.qml.typeregistration: 2022-05-31 14:59:29.207 [W] Invalid QML element name "FramelessHelperConstants"; value type names should begin with a lowercase letter。
如果把registerTypes中的代码挪在 main中运行，QtCreator就可以识别并且qml中出现语法提示。

**Comment by wangwenx190** [comment]
那个警告我也看到了，不过不影响使用，而且警告的内容也有些不合理，可以直接忽略

**Comment by zengdapang** [comment]
改成小写 提示 大写 改成大写 提示小写，绝啦~~~！！！很奇怪，在你的示例中是有语法提示的。我以为是cmake和qmake配置存在差异，我还在使用qmake。cmake还在尝试中，需要点时间适应学习。

**Comment by wangwenx190** [comment]
QMake 也是可以做到语法高亮的，而且Qt5和Qt6都支持，不过由于这个库的2.x版本并没有QMake工程文件，所以也没有做相关的适配。

**Comment by zengdapang** [comment]
了解，我再尝试尝试，感谢您的回复。

**Comment by wangwenx190** [comment]
如果编译为静态库，或者是你自己工程里的qml类型，qt可以自动识别并高亮，不需要额外的操作，但编译为动态库以后因为需要动态加载，所以qt就不能自动识别了
