### ISSUE TITLE
MinGW不支持ATL

### ISSUE THREAD

**Issue by SineStriker** [wangwenx190/framelesshelper#136]
最近尝试了2.0+版本的，CMake确实比QMake方便。用MSVC 2019试过没什么问题，但是MinGW貌似不支持ATL，在utils_win.cpp引入atlbase.h时提示找不到头文件，还是希望照顾下使用MinGW的群体移除ATL模块吧，感觉应该能找到替代。

**Comment by wangwenx190** [comment]
ATL主要是用了其中一个智能指针，用来自动释放com指针，其实用别的也能代替，过几天我看看

**Comment by wangwenx190** [comment]
main分支已去掉对ATL的依赖

**Comment by SineStriker** [comment]
感谢
