### ISSUE TITLE
在quick下使用只能是Qt6以上吗

### ISSUE THREAD

**Issue by luhongyi123** [wangwenx190/framelesshelper#137]
2.0以上版本是否有qt6以下可用的，我看见在qml中使用是有限制的，是有哪一部分功能不能用吗

**Comment by wangwenx190** [comment]
qml部分是纯C++实现的，但我所用到的好几个类在Qt5是不导出的，Qt6才导出，所以限制了Qt版本。如果是完全用qml实现的话，就没有这个限制了。

**Comment by wangwenx190** [comment]
具体是标准系统按钮和标准标题栏，一共有四个控件，在Qt5下是不能用的。FramelessHelper的核心功能不受影响。

**Comment by luhongyi123** [comment]
> 具体是标准系统按钮和标准标题栏，一共有四个控件，在Qt5下是不能用的。FramelessHelper的核心功能不受影响。

请问窗口圆角有影响吗

**Comment by wangwenx190** [comment]
> > 具体是标准系统按钮和标准标题栏，一共有四个控件，在Qt5下是不能用的。FramelessHelper的核心功能不受影响。
> 
> 请问窗口圆角有影响吗

只是几个控件不能用了，跟窗口圆角不圆角完全没关系

**Comment by luhongyi123** [comment]
> > > 具体是标准系统按钮和标准标题栏，一共有四个控件，在Qt5下是不能用的。FramelessHelper的核心功能不受影响。
> > 
> > 
> > 请问窗口圆角有影响吗
> 
> 只是几个控件不能用了，跟窗口圆角不圆角完全没关系

那请问怎么设置窗口圆角呢，我并没有找到对应的接口

**Comment by wangwenx190** [comment]
主要运行在什么系统？win7还是win10还是win11？

**Comment by luhongyi123** [comment]
> 主要运行在什么系统？win7还是win10还是win11？

win7和win10

**Comment by wangwenx190** [comment]
目前只有win11原生支持圆角。win7和win10可以用SetWindowRgn来把窗口变为圆角，但这样会破坏窗口的原生阴影，而且圆角的锯齿也比较严重，所以我并没有提供这个接口。有个间接的实现方法，就是让你的窗口使用透明背景，然后用样式表设置窗口的corner radius，这样可以用跨平台的方式实现圆角窗口，而且与你具体的系统版本没有关系。但这个方法只支持widget程序，quick程序我暂时还不清楚怎么做。

**Comment by wangwenx190** [comment]
圆角问题本身也与这个项目没有关系，所以这个项目并没有太多涉及

**Comment by luhongyi123** [comment]
> 



> 目前只有win11原生支持圆角。win7和win10可以用SetWindowRgn来把窗口变为圆角，但这样会破坏窗口的原生阴影，而且圆角的锯齿也比较严重，所以我并没有提供这个接口。有个间接的实现方法，就是让你的窗口使用透明背景，然后用样式表设置窗口的corner radius，这样可以用跨平台的方式实现圆角窗口，而且与你具体的系统版本没有关系。但这个方法只支持widget程序，quick程序我暂时还不清楚怎么做。

好的，谢谢。我目前也没有找到qml可以让窗口圆角的方法。

**Comment by wangwenx190** [comment]
你可以试试我说的那个思路，quick程序也能把窗口背景变透明，设置window的color为transparent就可以，然后在内部实现一个圆角的假窗口就可以了，感觉也行得通。

**Comment by luhongyi123** [comment]
> 你可以试试我说的那个思路，quick程序也能把窗口背景变透明，设置window的color为transparent就可以，然后在内部实现一个圆角的假窗口就可以了，感觉也行得通。

这种方法我试过，但是边框阴影是直角的，会导致四个角只有阴影和圆角中间是透明的

**Comment by wangwenx190** [comment]
这种方法肯定不能再使用系统提供的边框阴影了，只能自己模拟一个，不过这对于quick程序而言应该不难。

**Comment by luhongyi123** [comment]
> 这种方法肯定不能再使用系统提供的边框阴影了，只能自己模拟一个，不过这对于quick程序而言应该不难。

好的， 请问在你的库中怎么去掉系统提供的边框阴影呢

**Comment by wangwenx190** [comment]
用这种方法基本就用不到我这个项目了，我这个项目是在保留原生边框的基础上进行自定义，而要使用上面我提到的方法，就不能保留系统边框，两者是矛盾的。

**Comment by luhongyi123** [comment]
> 用这种方法基本就用不到我这个项目了，我这个项目是在保留原生边框的基础上进行自定义，而要使用上面我提到的方法，就不能保留系统边框，两者是矛盾的。

好吧，我主要是想保留半屏还有状态栏隐藏一些情况下能像原生窗口一样，这种情况大部分是要保留原生边框的，看来我只能两者选其一了

**Comment by wangwenx190** [comment]
这个确实没办法。想要保留原生窗口的行为，窗口边框是不可或缺的。但圆角本身不被系统支持（除了win11），实现起来基本都会破坏原生窗口的外观和行为。

**Comment by wangwenx190** [comment]
先close了
