### ISSUE TITLE
MacOS与MinGW无法通过编译

### ISSUE THREAD

**Issue by SineStriker** [wangwenx190/framelesshelper#138]
MinGW0.8.1缺少一些API函数和枚举类型（虽然ATL没了），暂时还是只能用MSVC。
MacOS（x86）无法通过编译。
PS：给您发了一封邮件希望查看。

**Comment by SineStriker** [comment]
MinGW缺失的内容。

WS_EX_NOREDIRECTIONBITMAP
USER_DEFAULT_SCREEN_DPI

DPI_AWARENESS_CONTEXT
DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2
DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE
DPI_AWARENESS_CONTEXT_SYSTEM_AWARE
DPI_AWARENESS_CONTEXT_UNAWARE_GDISCALED

GetSystemMetricsForDpi
GetDpiForWindow
GetSystemDpiForProcess
SetProcessDpiAwarenessContext
SetProcessDPIAware

**Comment by wangwenx190** [comment]
问题不大，我补一下相关的定义就好了，本来这些函数也都是动态加载的





------------------ 原始邮件 ------------------
发件人: VerySimple ***@***.***&gt;
发送时间: 2022年7月3日 18:59
收件人: wangwenx190/framelesshelper ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[wangwenx190/framelesshelper] MacOS与MinGW无法通过编译 (Issue #138)






MinGW缺失的内容。

WS_EX_NOREDIRECTIONBITMAP
USER_DEFAULT_SCREEN_DPI

DPI_AWARENESS_CONTEXT
DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2
DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE
DPI_AWARENESS_CONTEXT_SYSTEM_AWARE
DPI_AWARENESS_CONTEXT_UNAWARE_GDISCALED

GetSystemMetricsForDpi
GetDpiForWindow
GetSystemDpiForProcess
SetProcessDpiAwarenessContext
SetProcessDPIAware

**Comment by SineStriker** [comment]
Mac机子暂时不在身边，过两天我在补充。

**Comment by wangwenx190** [comment]
好的。到时候记得一并说一下系统版本，编译器版本和qt版本。





------------------ 原始邮件 ------------------
发件人: VerySimple ***@***.***&gt;
发送时间: 2022年7月3日 19:02
收件人: wangwenx190/framelesshelper ***@***.***&gt;
抄送: Yuhang Zhao ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[wangwenx190/framelesshelper] MacOS与MinGW无法通过编译 (Issue #138)





 
Mac机子暂时不在身边，过两天我在补充。

**Comment by wangwenx190** [comment]
> MinGW缺失的内容。
> 
> WS_EX_NOREDIRECTIONBITMAP USER_DEFAULT_SCREEN_DPI
> 
> DPI_AWARENESS_CONTEXT DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE DPI_AWARENESS_CONTEXT_SYSTEM_AWARE DPI_AWARENESS_CONTEXT_UNAWARE_GDISCALED
> 
> GetSystemMetricsForDpi GetDpiForWindow GetSystemDpiForProcess SetProcessDpiAwarenessContext SetProcessDPIAware

你所列在这里的内容都已经补充到代码里了，如果这里的内容没有缺漏，那么mingw应该是能编译了

**Comment by SineStriker** [comment]
mac的CMake里少了一句链接系统库
set(CMAKE_SHARED_LINKER_FLAGS "-framework ServiceManagement -framework Foundation -framework Cocoa")
加上以后就通过了
