### ISSUE TITLE
what's ignoreObjects and ignoreAreas

### ISSUE THREAD

**Issue by tianmingyao** [wangwenx190/framelesshelper#14]
如题，可以解释一下这个东西是干嘛的吗。

**Comment by wangwenx190** [comment]
标题栏区域里的鼠标事件都会被拦截，所以如果你的标题栏里有控件（比如按钮），就会无法响应鼠标事件，从而失效。而`ignoreObjects`可以接受`QObject`指针，你可以把你的控件（Widget或者Qt Quick元素）的指针添加到`ignoreObjects`里，这个控件的鼠标事件就不会被拦截了，从而能响应用户的操作。`ignoreAreas`是接受的不是指针而是区域，这个区域内的所有控件都能保持响应。这两个东西是等价的，具体用哪个看你项目的需要。只有标题栏区域里才需要这个，其他地方本来就不需要这两个东西。

**Comment by tianmingyao** [comment]
> 标题栏区域里的鼠标事件都会被拦截，所以如果你的标题栏里有控件（比如按钮），就会无法响应鼠标事件，从而失效。而`ignoreObjects`可以接受`QObject`指针，你可以把你的控件（Widget或者Qt Quick元素）的指针添加到`ignoreObjects`里，这个控件的鼠标事件就不会被拦截了，从而能响应用户的操作。`ignoreAreas`是接受的不是指针而是区域，这个区域内的所有控件都能保持响应。这两个东西是等价的，具体用哪个看你项目的需要。只有标题栏区域里才需要这个，其他地方本来就不需要这两个东西。

好的谢谢，还有几个问题
1. 是怎么设置可以拖动窗口的titlebar的高度/位置，我在我的项目中使用，发现无论是否使用setTitleBarHeight设置都无法拖动窗口
2. 窗口border的颜色可以设置吗，或者最好能够跟随windows主题颜色变化。默认的是白色，如果主界面是黑色，可能会比较难看。如下图：
![企业微信截图_15909998194879](https://user-images.githubusercontent.com/51583430/83390358-457fc200-a424-11ea-8b90-7f270989e669.png)

**Comment by wangwenx190** [comment]
>
> 是怎么设置可以拖动窗口的titlebar的高度/位置，我在我的项目中使用，发现无论是否使用setTitleBarHeight设置都无法拖动窗口
>
设置标题栏高度的接口只有这一个。按理说默认情况下，就算你什么都不设置，也不会影响拖动的。你是不是设置过draggableArea或者draggableObject，有了这两个就会忽略标题栏区域的。
>
> 窗口border的颜色可以设置吗，或者最好能够跟随windows主题颜色变化。默认的是白色，如果主界面是黑色，可能会比较难看
>
正常情况下border是看不见的，如果想显示边界线，需要自己去画一个，你这个会出现边界线也很奇怪。是Win10系统吗？

**Comment by wangwenx190** [comment]
如果你找不到原因在哪的话，可以把复现工程发给我，我这边调试一下

**Comment by tianmingyao** [comment]
> 窗口border的颜色可以设置吗，或者最好能够跟随windows主题颜色变化。默认的是白色，如果主界面是黑色，可能会比较难看



这个是由于我这边主layout设置了border导致的，修改之后正常了。

但是现在情况是无法拖动窗口，也无法缩放窗口。示例工程如下，代码比较乱，望见谅。
[test.zip](https://github.com/wangwenx190/framelesshelper/files/4710407/test.zip)

**Comment by tianmingyao** [comment]
我已经发现是项目里的DisplayWidget导致的，我删掉之后就都正常了，原因暂未知，我再看看啊。

**Comment by tianmingyao** [comment]
是由于DisplayWidget构造函数中的this->winId();导致的，

**Comment by wangwenx190** [comment]
> 是由于DisplayWidget构造函数中的this->winId();导致的，

调用winId()这个函数后，对应的widget会变成一个原生窗口，父widget就收不到鼠标事件了（因为这个widget已经不是父widget的一部分了），应该是这个原因

**Comment by wangwenx190** [comment]
如果必须要获取窗口句柄，可以试试windowHandle()->winId()，不过不能在构造函数里调用，因为构造函数里windowHandle()是空的

**Comment by tianmingyao** [comment]
> 如果必须要获取窗口句柄，可以试试windowHandle()->winId()，不过不能在构造函数里调用，因为构造函数里windowHandle()是空的

好的 谢谢 我试试。

**Comment by winsoft666** [comment]
﻿是这个问题导致的。




在 2020年6月1日，17:26，ming.tian-vrviu <notifications@github.com> 写道：

﻿

是由于DisplayWidget构造函数中的this->winId();导致的，
