### ISSUE TITLE
windows下不包含example.manifest时， 窗口的拉伸区域识别不正常，有什么办法解决吗？

### ISSUE THREAD

**Issue by ZhouYing-bit** [wangwenx190/framelesshelper#140]
```
win32 {
    RC_FILE += $$PWD/example.rc
#    CONFIG -= embed_manifest_exe
#    QMAKE_MANIFEST = $$PWD/example.manifest
}
```

git版本： 2.1.7

如上代码，如果不使用example.manifest文件，窗口边缘拉伸区域识别是再内容区，而不是在窗口外;

不太明白example.manifest和这个效果有什么关联

**Comment by wangwenx190** [comment]
清单文件里声明了应用程序支持的系统版本和缩放策略，其中后者可以通过代码设置，我也默认设置了最合适的策略，但前者无法通过代码修改，因此如果缺少此文件，会导致部分API行为改变。但最新的代码应该是规避了这个问题，你没有使用最新代码吧？

**Comment by wangwenx190** [comment]
直接用main分支的最新代码就行，一般未完工的功能我不会直接提交到主分支

**Comment by ZhouYing-bit** [comment]
main分支使用qmake编译不过，错误信息是 ` In included file: 'framelesshelper.version' file not found`；  
目前很多项目还是使用qmake，希望作者能兼容qmake编译。

**Comment by wangwenx190** [comment]
那个文件是自动生成的，你可以手动弄一个，就是包含版本号什么的一个很简单的头文件

**Comment by wangwenx190** [comment]
其他应该没有什么会影响qmake的地方了

**Comment by wangwenx190** [comment]
> 目前很多项目还是使用qmake，希望作者能兼容qmake编译。

行，这周我搞一下

**Comment by wangwenx190** [comment]
https://github.com/wangwenx190/framelesshelper/blob/main/src/core/framelesshelper.version.in

这个是那个文件的模板

**Comment by ZhouYing-bit** [comment]
好的，这个文件内容我已在cmake build里面找到了。

**Comment by wangwenx190** [comment]
qmake的事被耽误了，我看这周能不能加上。不过这个issue主要反映Windows版本判断不准确，会受清单文件影响，这个问题在最新的代码里已经解决了，因此先把这个issue关闭了，有问题可以再重新打开。
