### ISSUE TITLE
[Win10] Window expands when transitioning between two monitors with different DPI.

### ISSUE THREAD

**Issue by mpb27** [wangwenx190/framelesshelper#141]
Branch: master (2.2.0 work in progress) 7f9f2c8543949c504b5cceb998cbb78d390cb70f 
System: Windows 10.0.18363
Monitor 1: DPI 96 - 100%
Monitor 2: DPI 120 - 125%
Qt: 6.3.1 _(edit)_

![Animation2](https://user-images.githubusercontent.com/6098645/179430397-5ac96acc-44fa-4a60-bb6f-8b3c3ab71408.gif)

To try and fix this I played around with the code below:

https://github.com/wangwenx190/framelesshelper/blob/7f9f2c8543949c504b5cceb998cbb78d390cb70f/src/core/framelesshelper_win.cpp#L630-L641

And moved the bottom of the client rectangle also when moving the top:

```
clientRect->bottom += (originalTop - clientRect->top);
```

This fixed the expanding issue, but introduced another where a stripe was created the size of the native frame bar but on the bottom.

Hope to get some help on reproducing and fixing this issue.

Thanks.

**Comment by wangwenx190** [comment]
FramelessHelper's code should be correct. This issue probably comes from the Windows QPA. Qt's platform plugin does many magic things, and most of the time they don't take frameless windows into account, so this may cause issues for frameless windows. The issue you mentioned here is not new to me, some FramelessHelper users have already told me about it long time ago, but I don't dig much into it due to it's mostly a Qt bug.

By the way, what's your Qt version? This information is also very important.

**Comment by mpb27** [comment]
I'm using Qt 6.3.1 and if I add the `clientRect->bottom += (originalTop - clientRect->top);` then the problem does not occur:

![Animation3](https://user-images.githubusercontent.com/6098645/179441536-2bac3751-8b4d-4412-a5f8-f42488bd2101.gif)

But the inner widget (and dock space) is not extended to the full size of the window.

**Comment by mpb27** [comment]
We can probably leave this bug for now. It is a fairly minor issue, but I thought I'd report it just in case it was an easy fix. That does not seem to be the case.

**Comment by wangwenx190** [comment]
> We can probably leave this bug for now. It is a fairly minor issue, but I thought I'd report it just in case it was an easy fix. That does not seem to be the case.

I'm not sure whether it's easy or hard to fix, but I'm sure there's nothing wrong with FramelessHelper's code.

**Comment by mpb27** [comment]
Thanks. Just a couple notes for anyone following this on the Qt version.

Qt 6.1.3 has different behaviour. The entire window resizes a bit, but does not continouusly grow on each transition. 
Qt 6.2.4 has the same behaviour as Qt 6.3.1.

I wonder if there is a way to report this to Qt? Or if anyone from Qt is following FramelessHelper?

**Comment by wangwenx190** [comment]
So it seems it's a regression since Qt 6.2. You can report this bug to Qt through its official website: <https://bugreports.qt.io/>

**Comment by wangwenx190** [comment]
It's indeed a Qt bug and I've located the wrong code, I'm preparing a fix for it and hopefully Qt will merge my fix and all later Qt versions won't have this issue anymore.

**Comment by wangwenx190** [comment]
fixed, both in FramelessHelper and Qt itself
