### ISSUE TITLE
[Feature Request] FramelessDialog

### ISSUE THREAD

**Issue by PenceP** [wangwenx190/framelesshelper#143]
Please consider adding FramelessDialog to complement the FramelessMainWindow and FramelessWidget.

**Comment by wangwenx190** [comment]
Hi, sorry for the long time delay. I've implemented FramelessDialog in latest code in the main branch, please try it out if you have time, thanks! Since I myself don't have enough test cases to test dialogs, it would be really helpful if you could test it and share your findings 😁

**Comment by wangwenx190** [comment]
Close as solved.
