### ISSUE TITLE
[Qt 5.15] Quick for qt 5.15?

### ISSUE THREAD

**Issue by mirroI** [wangwenx190/framelesshelper#144]
Will quick support be added for qt version 5.15?

**Comment by wangwenx190** [comment]
It's always supported. However, some controls provided by FramelessHelper will not be available, because I'm using pure C++ to implement them, but the private classes I used were not exported in Qt5.

**Comment by wangwenx190** [comment]
In the earlier days of FramelessHelper, I'm using QML files to implement these controls, so they work on both Qt5 and Qt6, later I migrated to pure C++ implementation to get better performance and higher customizability, but sadly since that time they can't be ported to Qt5
