### ISSUE TITLE
setMinimumSize() not work

### ISSUE THREAD

**Issue by xq114** [wangwenx190/framelesshelper#15]
如题，QWidget的setMinimumSize和setMaximumSize都失效了，有什么解决办法吗

**Comment by xq114** [comment]
看了README发现需要用这个设置，没事了

**Comment by wangwenx190** [comment]
边框去掉以后，为了处理一些边边角角的事情，设置窗口最大和最小尺寸的消息被我拦截了，所以只能用README里提到的方式间接进行设置，虽然不如以前方便，但也没有其他更好的办法了。
