### ISSUE TITLE
[Feature Request] .pro or .pri 支持

### ISSUE THREAD

**Issue by zengdapang** [wangwenx190/framelesshelper#150]
如果可以的话，除了cmake外希望还是能够提供qmake支持。

**Comment by wangwenx190** [comment]
有好几个人提过这个了，我可以搞个简单一点的。如果是完整的qmake工程，而且还要一比一还原现在的cmake工程的话，比较费劲，暂时没空搞。

**Comment by zengdapang** [comment]
只是个建议，毕竟老工程很多都是qmake的，有时间可以考虑一下。

**Comment by wangwenx190** [comment]
目前我的打算是整几个pri文件，需要的可以直接include对应的pri，直接把FramelessHelper静态链接进去，就不搞什么专门的工程了

**Comment by zengdapang** [comment]
这样已经非常好了。

**Comment by wangwenx190** [comment]
最新代码已添加qmake支持

**Comment by zengdapang** [comment]
ASSERT: "fallbackTitleBarWindowHandle" in file ..\..\ZQDeps\3rdparty\framelesshelper\src\core\framelesshelper_win.cpp, line 463

使用.pri创建窗口时 收到这个assert CreateWindowExW返回失败，是需要做什么吗？

**Comment by wangwenx190** [comment]
这个不太正常。你系统版本是多少？Qt版本呢？控制台输出了什么？

**Comment by wangwenx190** [comment]
不过这个断言失败可以忽略，不影响程序的后续运行

**Comment by zengdapang** [comment]
版本	Windows 11 家庭中文版
版本	21H2
操作系统版本	22000.918
体验	Windows 功能体验包 1000.22000.918.0
Qt6.4 beta4

**Comment by zengdapang** [comment]
后续运行是正常的，只是win11的窗口快照不正常。

**Comment by zengdapang** [comment]
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "SetProcessDpiAwarenessContext" from "user32"
qt.qpa.windows: setProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2) failed: COM error 0x5  (拒绝访问。)
qt.qml.typeregistration: Invalid QML element name "FramelessHelperConstants"; value type names should begin with a lowercase letter
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "RtlGetVersion" from "ntdll"
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "timeGetDevCaps" from "winmm"
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "timeBeginPeriod" from "winmm"
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "timeEndPeriod" from "winmm"
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "DwmGetCompositionTimingInfo" from "dwmapi"
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "SetWindowThemeAttribute" from "uxtheme"
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "GetDpiForWindow" from "user32"
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "GetSystemMetricsForDpi" from "user32"
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "DwmExtendFrameIntoClientArea" from "dwmapi"
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "DwmSetWindowAttribute" from "dwmapi"
wangwenx190.framelesshelper.core.sysapiloader: Successfully loaded "SetWindowTheme" from "uxtheme"
ASSERT: "fallbackTitleBarWindowHandle" in file ..\..\3rdparty\framelesshelper\src\core\framelesshelper_win.cpp, line 463

**Comment by wangwenx190** [comment]
> 版本 Windows 11 家庭中文版 版本 21H2 操作系统版本 22000.918 体验 Windows 功能体验包 1000.22000.918.0 Qt6.4 beta4

这个没什么问题，现在也是这个配置。

> win11的窗口快照不正常

这个是什么表现呢，能不能贴一个截图之类的

> ASSERT: "fallbackTitleBarWindowHandle" in file ....\3rdparty\framelesshelper\src\core\framelesshelper_win.cpp, line 463

关于那个CreateWindowExW没有什么输出吗？

**Comment by zengdapang** [comment]
![image](https://user-images.githubusercontent.com/50150904/188259340-0172e232-5fb0-4d91-95d8-3ee0ccb99a9e.png)

**Comment by wangwenx190** [comment]
你的窗口是不是有什么额外的或者特殊的设置，导致无法创建子窗口

**Comment by zengdapang** [comment]
![image](https://user-images.githubusercontent.com/50150904/188259358-23d069f5-d087-4d8f-a512-3de2066d34ba.png)

**Comment by zengdapang** [comment]
原样照搬了示例

**Comment by zengdapang** [comment]
仅仅是这个小组件无法显示

**Comment by wangwenx190** [comment]
那个窗口就是为了显示这个菜单而创建的，创建失败自然就没有这个菜单了。不过按理说不应该无法创建。你有QQ或者微信吗，可以加一下进一步交流。

**Comment by zengdapang** [comment]
QQ : 992808734

**Comment by zhuzichu520** [comment]
这个解决了没，我也遇到这个问题了

**Comment by wangwenx190** [comment]
> 这个解决了没，我也遇到这个问题了

是指贴靠菜单无法弹出吗？这个需要你的exe添加一个清单文件，里面显式声明win11兼容性
