### ISSUE TITLE
[Bug] [Windows] incorrect registry section existence check

### ISSUE THREAD

**Issue by trbogdanov** [wangwenx190/framelesshelper#152]
Hello, @wangwenx190!

System: Qt 5.12.0, Windows 10 (21H2).

I found that it is not possible to get the current system theme because checking for the existence of the "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" section in the Windows registry fails (registrykey.cpp).

```cpp
RegistryKey::RegistryKey(const RegistryRootKey root, const QString &key, QObject *parent) : QObject(parent)
{
    // ...
    m_settings.reset(new QSettings(rootKey, QSettings::NativeFormat));
    if (m_settings->contains(m_subKey)) { // FAILS EVEN IF SECTION EXISTS
        // ...
}
```

I suggest this fix. We check that section "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes" contains a "Personalize" child section. This actually means that `m_subKey` exists entirely.

```cpp
    // ...
    m_settings.reset(new QSettings(rootKey + u'\\' + m_subKey.leftRef(m_subKey.lastIndexOf(u'\\')), QSettings::NativeFormat));
    if (m_settings->childGroups().contains(m_subKey.midRef(m_subKey.lastIndexOf(u'\\') + 1))) {
        // ...
```

It is just an option, but at least it worked for me

**Comment by wangwenx190** [comment]
Really thanks! But why the "Personalize" section doesn't exist on your system? I see your OS version is 21H2, it's quite new.

**Comment by wangwenx190** [comment]
Oh, do you mean the registry key exists, but QSettings still think it doesn't exist? It's a real problem, I'll fix it right away.

**Comment by wangwenx190** [comment]
Can you test whether the latest code fixed the issue for you or not? Thanks!

**Comment by trbogdanov** [comment]
I have checked, now it works well!

Thanks for your work, I just started using your library and I really like it!

**Comment by wangwenx190** [comment]
I'm glad you like it 😁
