### ISSUE TITLE
Windows related errors when trying to include pri files

### ISSUE THREAD

**Issue by yeahitsjan** [wangwenx190/framelesshelper#153]
Hey there!

First of all, awesome library! Would really like to use it in some of my applications, and to minimize the build for the user, I want to directly integrate it using the ``.pri`` file. My project file looks like this:

```
QT += core gui multimedia network opengl
CONFIG += c++17
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TARGET = framelessapp
TEMPLATE = app

SOURCES += main.cpp

include(framelesshelper/qmake/core.pri)
include(framelesshelper/qmake/widgets.pri)
```

The system I use is Windows 10 21H2 Build 19044. Qt is 5.14.2 MinGW 64-bit.

When trying to build I get some Windows related errors:

<details>
<summary>Output</summary>
<pre>
In file included from ..\..\framelesshelper\src\core\framelesshelper_windows.h:1:0,
                 from ..\..\framelesshelper\src\core\registrykey.cpp:26:
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/framelesshelper_windows.h:310:1: error: 'EXTERN_C_START' does not name a type; did you mean 'EXTERN_C'?
 EXTERN_C_START
 ^~~~~~~~~~~~~~
 EXTERN_C
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/framelesshelper_windows.h:378:1: error: 'EXTERN_C_END' does not name a type; did you mean 'EXTERN_C'?
 EXTERN_C_END
 ^~~~~~~~~~~~
 EXTERN_C
..\..\framelesshelper\src\core\registrykey.cpp:52:5: error: 'HKEY_CURRENT_USER_LOCAL_SETTINGS' was not declared in this scope
     HKEY_CURRENT_USER_LOCAL_SETTINGS,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
..\..\framelesshelper\src\core\registrykey.cpp:52:5: note: suggested alternative: 'ENUM_CURRENT_SETTINGS'
     HKEY_CURRENT_USER_LOCAL_SETTINGS,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     ENUM_CURRENT_SETTINGS
..\..\framelesshelper\src\core\registrykey.cpp:56:1: error: static assertion failed
 static_assert(std::size(g_keyMap) == (static_cast<int>(RegistryRootKey::PerformanceNlsText) + 1));
 ^~~~~~~~~~~~~
..\..\framelesshelper\src\core\registrykey.cpp:70:1: error: static assertion failed
 static_assert(std::size(g_strMap) == std::size(g_keyMap));
 ^~~~~~~~~~~~~
mingw32-make[1]: *** [Makefile.Debug:3561: debug/registrykey.o] Error 1
mingw32-make[1]: *** Waiting for unfinished jobs....
In file included from ..\..\framelesshelper\src\core\framelesshelper_windows.h:1:0,
                 from ..\..\framelesshelper\src\core\framelesshelper_win.cpp:36:
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/framelesshelper_windows.h:310:1: error: 'EXTERN_C_START' does not name a type; did you mean 'EXTERN_C'?
 EXTERN_C_START
 ^~~~~~~~~~~~~~
 EXTERN_C
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/framelesshelper_windows.h:378:1: error: 'EXTERN_C_END' does not name a type; did you mean 'EXTERN_C'?
 EXTERN_C_END
 ^~~~~~~~~~~~
 EXTERN_C
..\..\framelesshelper\src\core\framelesshelper_win.cpp: In member function 'virtual bool wangwenx190::FramelessHelper::FramelessHelperWin::nativeEventFilter(const QByteArray&, void*, QT_NATIVE_EVENT_RESULT_TYPE*)':
..\..\framelesshelper\src\core\framelesshelper_win.cpp:798:40: error: 'kAutoHideTaskBarThickness' was not declared in this scope
                     clientRect->top += kAutoHideTaskBarThickness;
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
..\..\framelesshelper\src\core\framelesshelper_win.cpp:800:43: error: 'kAutoHideTaskBarThickness' was not declared in this scope
                     clientRect->bottom -= kAutoHideTaskBarThickness;
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
..\..\framelesshelper\src\core\framelesshelper_win.cpp:802:41: error: 'kAutoHideTaskBarThickness' was not declared in this scope
                     clientRect->left += kAutoHideTaskBarThickness;
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
..\..\framelesshelper\src\core\framelesshelper_win.cpp:804:42: error: 'kAutoHideTaskBarThickness' was not declared in this scope
                     clientRect->right -= kAutoHideTaskBarThickness;
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ..\..\framelesshelper\src\core\framelesshelper_windows.h:1:0,
                 from ..\..\framelesshelper\src\core\utils_win.cpp:41:
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/framelesshelper_windows.h:310:1: error: 'EXTERN_C_START' does not name a type; did you mean 'EXTERN_C'?
 EXTERN_C_START
 ^~~~~~~~~~~~~~
 EXTERN_C
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/framelesshelper_windows.h:378:1: error: 'EXTERN_C_END' does not name a type; did you mean 'EXTERN_C'?
 EXTERN_C_END
 ^~~~~~~~~~~~
 EXTERN_C
..\..\framelesshelper\src\core\utils_win.cpp: In function 'void wangwenx190::FramelessHelper::Utils::disableOriginalTitleBarFunctionalities(WId, bool)':
..\..\framelesshelper\src\core\utils_win.cpp:1796:5: error: 'WTA_OPTIONS' was not declared in this scope
     WTA_OPTIONS options;
     ^~~~~~~~~~~
..\..\framelesshelper\src\core\utils_win.cpp:1796:5: note: suggested alternative: 'STGOPTIONS'
     WTA_OPTIONS options;
     ^~~~~~~~~~~
     STGOPTIONS
..\..\framelesshelper\src\core\utils_win.cpp:1797:23: error: 'options' was not declared in this scope
     SecureZeroMemory(&options, sizeof(options));
                       ^~~~~~~
..\..\framelesshelper\src\core\utils_win.cpp:1797:23: note: suggested alternative: 'optind'
     SecureZeroMemory(&options, sizeof(options));
                       ^~~~~~~
                       optind
..\..\framelesshelper\src\core\utils_win.cpp:1799:10: error: 'WTNCA_NODRAWCAPTION' was not declared in this scope
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
          ^~~~~~~~~~~~~~~~~~~
mingw32-make[1]: *** [Makefile.Debug:3928: debug/framelesshelper_win.o] Error 1
..\..\framelesshelper\src\core\utils_win.cpp:1799:10: note: suggested alternative: 'WM_NCUAHDRAWCAPTION'
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
          ^~~~~~~~~~~~~~~~~~~
          WM_NCUAHDRAWCAPTION
..\..\framelesshelper\src\core\utils_win.cpp:1799:32: error: 'WTNCA_NODRAWICON' was not declared in this scope
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
                                ^~~~~~~~~~~~~~~~
..\..\framelesshelper\src\core\utils_win.cpp:1799:32: note: suggested alternative: 'WM_QUERYDRAGICON'
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
                                ^~~~~~~~~~~~~~~~
                                WM_QUERYDRAGICON
..\..\framelesshelper\src\core\utils_win.cpp:1799:51: error: 'WTNCA_NOSYSMENU' was not declared in this scope
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
                                                   ^~~~~~~~~~~~~~~
..\..\framelesshelper\src\core\utils_win.cpp:1799:51: note: suggested alternative: 'WS_SYSMENU'
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
                                                   ^~~~~~~~~~~~~~~
                                                   WS_SYSMENU
In file included from ..\..\framelesshelper\src\core\sysapiloader_p.h:1:0,
                 from ..\..\framelesshelper\src\core\utils_win.cpp:43:
..\..\framelesshelper\src\core\utils_win.cpp:1800:42: error: '::SetWindowThemeAttribute' has not been declared
     const HRESULT hr = API_CALL_FUNCTION(SetWindowThemeAttribute,
                                          ^
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/private/sysapiloader_p.h:81:47: note: in definition of macro 'API_CALL_FUNCTION'
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                               ^~~~
..\..\framelesshelper\src\core\utils_win.cpp:1800:42: note: suggested alternative: 'kSetWindowThemeAttribute'
     const HRESULT hr = API_CALL_FUNCTION(SetWindowThemeAttribute,
                                          ^
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/private/sysapiloader_p.h:81:47: note: in definition of macro 'API_CALL_FUNCTION'
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                               ^~~~
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/private/sysapiloader_p.h:81:61: error: no matching function for call to 'wangwenx190::FramelessHelper::SysApiLoader::get<<expression error> >(const QString&)'
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                                             ^
..\..\framelesshelper\src\core\utils_win.cpp:1800:24: note: in expansion of macro 'API_CALL_FUNCTION'
     const HRESULT hr = API_CALL_FUNCTION(SetWindowThemeAttribute,
                        ^
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/private/sysapiloader_p.h:55:26: note: candidate: template<class T> T wangwenx190::FramelessHelper::SysApiLoader::get(const QString&)
     Q_NODISCARD inline T get(const QString &function)
                          ^~~
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/private/sysapiloader_p.h:55:26: note:   template argument deduction/substitution failed:
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/private/sysapiloader_p.h:81:61: error: template argument 1 is invalid
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                                             ^
..\..\framelesshelper\src\core\utils_win.cpp:1800:24: note: in expansion of macro 'API_CALL_FUNCTION'
     const HRESULT hr = API_CALL_FUNCTION(SetWindowThemeAttribute,
                        ^
..\..\framelesshelper\src\core\utils_win.cpp:1801:15: error: 'WTA_NONCLIENT' was not declared in this scope
         hwnd, WTA_NONCLIENT, &options, sizeof(options));
               ^
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/private/sysapiloader_p.h:81:64: note: in definition of macro 'API_CALL_FUNCTION'
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                                                ^~~~~~~~~~~
..\..\framelesshelper\src\core\utils_win.cpp:1801:15: note: suggested alternative: 'PRF_NONCLIENT'
         hwnd, WTA_NONCLIENT, &options, sizeof(options));
               ^
..\..\framelesshelper\src\core\../../include/FramelessHelper/Core/private/sysapiloader_p.h:81:64: note: in definition of macro 'API_CALL_FUNCTION'
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                                                ^~~~~~~~~~~
mingw32-make[1]: *** [Makefile.Debug:4116: debug/utils_win.o] Error 1
</pre>
</details>

What did I do wrong? Did I miss something? ``windows.h`` is available.

Many thanks!
Jan

**Comment by wangwenx190** [comment]
Hi, the issue should be fixed by now, please test the latest code from the main branch, thanks!

**Comment by yeahitsjan** [comment]
Hey! Many things are fixed. Still got the problems with some definitions:
```
..\..\framelesshelper\src\core\registrykey.cpp:52:5: error: 'HKEY_CURRENT_USER_LOCAL_SETTINGS' was not declared in this scope
     HKEY_CURRENT_USER_LOCAL_SETTINGS,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
..\..\framelesshelper\src\core\registrykey.cpp:52:5: note: suggested alternative: 'ENUM_CURRENT_SETTINGS'
     HKEY_CURRENT_USER_LOCAL_SETTINGS,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     ENUM_CURRENT_SETTINGS
..\..\framelesshelper\src\core\registrykey.cpp:56:1: error: static assertion failed
 static_assert(std::size(g_keyMap) == (static_cast<int>(RegistryRootKey::PerformanceNlsText) + 1));
 ^~~~~~~~~~~~~
..\..\framelesshelper\src\core\registrykey.cpp:70:1: error: static assertion failed
 static_assert(std::size(g_strMap) == std::size(g_keyMap));
 ^~~~~~~~~~~~~
mingw32-make[1]: *** [Makefile.Debug:3561: debug/registrykey.o] Error 1
mingw32-make[1]: *** Waiting for unfinished jobs....
```

**Comment by wangwenx190** [comment]
It should really be fixed now, please test again, thanks!
