### ISSUE TITLE
Windows Qt 5.15.2 MinGW 环境下编译报错

### ISSUE THREAD

**Issue by jason-yau** [wangwenx190/framelesshelper#154]
系统 windows Qt5.15.2 MinGW，输出如下：
``shell
E:/Projects/CXX/framelesshelper-2.2.1/include/FramelessHelper/Core/framelesshelper_windows.h:310:1: error: 'EXTERN_C_START' does not name a type; did you mean 'EXTERN_C'?
 EXTERN_C_START
 ^~~~~~~~~~~~~~
 EXTERN_C
E:/Projects/CXX/framelesshelper-2.2.1/include/FramelessHelper/Core/framelesshelper_windows.h:378:1: error: 'EXTERN_C_END' does not name a type; did you mean 'EXTERN_C'?
 EXTERN_C_END
 ^~~~~~~~~~~~
 EXTERN_C
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp: In function 'void wangwenx190::FramelessHelper::Utils::disableOriginalTitleBarFunctionalities(WId, bool)':
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1818:5: error: 'WTA_OPTIONS' was not declared in this scope
     WTA_OPTIONS options;
     ^~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1818:5: note: suggested alternative: 'STGOPTIONS'
     WTA_OPTIONS options;
     ^~~~~~~~~~~
     STGOPTIONS
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1819:23: error: 'options' was not declared in this scope
     SecureZeroMemory(&options, sizeof(options));
                       ^~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1819:23: note: suggested alternative: 'optind'
     SecureZeroMemory(&options, sizeof(options));
                       ^~~~~~~
                       optind
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1821:10: error: 'WTNCA_NODRAWCAPTION' was not declared in this scope
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
          ^~~~~~~~~~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1821:10: note: suggested alternative: 'WM_NCUAHDRAWCAPTION'
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
          ^~~~~~~~~~~~~~~~~~~
          WM_NCUAHDRAWCAPTION
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1821:32: error: 'WTNCA_NODRAWICON' was not declared in this scope
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
                                ^~~~~~~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1821:32: note: suggested alternative: 'WM_QUERYDRAGICON'
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
                                ^~~~~~~~~~~~~~~~
                                WM_QUERYDRAGICON
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1821:51: error: 'WTNCA_NOSYSMENU' was not declared in this scope
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
                                                   ^~~~~~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1821:51: note: suggested alternative: 'WS_SYSMENU'
         (WTNCA_NODRAWCAPTION | WTNCA_NODRAWICON | WTNCA_NOSYSMENU) : 0);
                                                   ^~~~~~~~~~~~~~~
                                                   WS_SYSMENU
In file included from E:/Projects/CXX/framelesshelper-2.2.1/src/core/sysapiloader_p.h:1,
                 from E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:43:
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1822:42: error: '::SetWindowThemeAttribute' has not been declared
     const HRESULT hr = API_CALL_FUNCTION(SetWindowThemeAttribute,
                                          ^~~~~~~~~~~~~~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/include/FramelessHelper/Core/private/sysapiloader_p.h:81:47: note: in definition of macro 'API_CALL_FUNCTION'
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                               ^~~~
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1822:42: note: suggested alternative: 'kSetWindowThemeAttribute'
     const HRESULT hr = API_CALL_FUNCTION(SetWindowThemeAttribute,
                                          ^~~~~~~~~~~~~~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/include/FramelessHelper/Core/private/sysapiloader_p.h:81:47: note: in definition of macro 'API_CALL_FUNCTION'
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                               ^~~~
E:/Projects/CXX/framelesshelper-2.2.1/include/FramelessHelper/Core/private/sysapiloader_p.h:81:61: error: no matching function for call to 'wangwenx190::FramelessHelper::SysApiLoader::get<<expression error> >(const QString&)'
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                                             ^
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1822:24: note: in expansion of macro 'API_CALL_FUNCTION'
     const HRESULT hr = API_CALL_FUNCTION(SetWindowThemeAttribute,
                        ^~~~~~~~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/include/FramelessHelper/Core/private/sysapiloader_p.h:55:26: note: candidate: 'template<class T> T wangwenx190::FramelessHelper::SysApiLoader::get(const QString&)'
     Q_NODISCARD inline T get(const QString &function)
                          ^~~
E:/Projects/CXX/framelesshelper-2.2.1/include/FramelessHelper/Core/private/sysapiloader_p.h:55:26: note:   template argument deduction/substitution failed:
E:/Projects/CXX/framelesshelper-2.2.1/include/FramelessHelper/Core/private/sysapiloader_p.h:81:61: error: template argument 1 is invalid
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                                             ^
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1822:24: note: in expansion of macro 'API_CALL_FUNCTION'
     const HRESULT hr = API_CALL_FUNCTION(SetWindowThemeAttribute,
                        ^~~~~~~~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1823:15: error: 'WTA_NONCLIENT' was not declared in this scope
         hwnd, WTA_NONCLIENT, &options, sizeof(options));
               ^~~~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/include/FramelessHelper/Core/private/sysapiloader_p.h:81:64: note: in definition of macro 'API_CALL_FUNCTION'
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                                                ^~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/src/core/utils_win.cpp:1823:15: note: suggested alternative: 'PRF_NONCLIENT'
         hwnd, WTA_NONCLIENT, &options, sizeof(options));
               ^~~~~~~~~~~~~
E:/Projects/CXX/framelesshelper-2.2.1/include/FramelessHelper/Core/private/sysapiloader_p.h:81:64: note: in definition of macro 'API_CALL_FUNCTION'
   ((SysApiLoader::instance()->get<decltype(&::func)>(k##func))(__VA_ARGS__))
                                                                ^~~~~~~~~~~
[16/64] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/FramelessHelperCore_autogen/EWIEGA46WW/qrc_framelesshelpercore.cpp.obj
ninja: build stopped: subcommand failed.
``

这是什么问题呢？

**Comment by yeahitsjan** [comment]
I attach mine to it #153.

**Comment by wangwenx190** [comment]
最新代码应该没问题了，请测试

**Comment by jason-yau** [comment]
> 最新代码应该没问题了，请测试

编译了一下，还是存在一些报错，完整输出如下：
`
$ cmake --build . --config Release --target all --parallel
[1/68] Automatic MOC and UIC for target FramelessHelperCore
[2/68] Automatic RCC for framelesshelpercore.qrc
[3/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/utils.cpp.obj
[4/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/framelessconfig.cpp.obj
[5/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/FramelessHelperCore_autogen/mocs_compilation.cpp.obj
[6/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/framelessmanager.cpp.obj
[7/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/framelesshelper_qt.cpp.obj
[8/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/framelesshelpercore_global.cpp.obj
[9/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/chromepalette.cpp.obj
[10/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/FramelessHelperCore_autogen/EWIEGA46WW/qrc_framelesshelpercore.cpp.obj
[11/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/registrykey.cpp.obj
FAILED: src/core/CMakeFiles/FramelessHelperCore.dir/registrykey.cpp.obj
C:\Qt\Tools\mingw810_64\bin\c++.exe -DFRAMELESSHELPER_CORE_LIBRARY -DFRAMELESSHELPER_CORE_STATIC -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DEPRECATED_WARNINGS_SINCE=0x070000 -DQT_DISABLE_DEPRECATED_BEFORE=0x070000 -DQT_DISABLE_DEPRECATED_UP_TO=0x070000 -DQT_GUI_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_FOREACH -DQT_NO_KEYWORDS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_URL_CAST_FROM_STRING -DQT_USE_QSTRINGBUILDER -DQT_WARN_DEPRECATED_UP_TO=0x070000 -IC:/Projects/CXX/framelesshelper/build/src/core -IC:/Projects/CXX/framelesshelper/src/core -IC:/Projects/CXX/framelesshelper/build/src/core/FramelessHelperCore_autogen/include -IC:/Projects/CXX/framelesshelper/src/core/../../include/FramelessHelper/Core -IC:/Projects/CXX/framelesshelper/src/core/../../include/FramelessHelper/Core/private -isystem C:/Qt/5.15.2/mingw81_64/include/QtCore/5.15.2 -isystem C:/Qt/5.15.2/mingw81_64/include/QtCore/5.15.2/QtCore -isystem C:/Qt/5.15.2/mingw81_64/include -isystem C:/Qt/5.15.2/mingw81_64/include/QtCore -isystem C:/Qt/5.15.2/mingw81_64/./mkspecs/win32-g++ -isystem C:/Qt/5.15.2/mingw81_64/include/QtGui/5.15.2 -isystem C:/Qt/5.15.2/mingw81_64/include/QtGui/5.15.2/QtGui -isystem C:/Qt/5.15.2/mingw81_64/include/QtGui -isystem C:/Qt/5.15.2/mingw81_64/include/QtANGLE -fvisibility=hidden -fno-keep-inline-dllexport -Wall -Wextra -Werror -std=c++17 -MD -MT src/core/CMakeFiles/FramelessHelperCore.dir/registrykey.cpp.obj -MF src\core\CMakeFiles\FramelessHelperCore.dir\registrykey.cpp.obj.d -o src/core/CMakeFiles/FramelessHelperCore.dir/registrykey.cpp.obj -c C:/Projects/CXX/framelesshelper/src/core/registrykey.cpp
C:/Projects/CXX/framelesshelper/src/core/registrykey.cpp:52:5: error: 'HKEY_CURRENT_USER_LOCAL_SETTINGS' was not declared in this scope
     HKEY_CURRENT_USER_LOCAL_SETTINGS,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Projects/CXX/framelesshelper/src/core/registrykey.cpp:52:5: note: suggested alternative: 'ENUM_CURRENT_SETTINGS'
     HKEY_CURRENT_USER_LOCAL_SETTINGS,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     ENUM_CURRENT_SETTINGS
C:/Projects/CXX/framelesshelper/src/core/registrykey.cpp:56:35: error: static assertion failed
 static_assert(std::size(g_keyMap) == (static_cast<int>(RegistryRootKey::PerformanceNlsText) + 1));
               ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Projects/CXX/framelesshelper/src/core/registrykey.cpp:70:35: error: static assertion failed
 static_assert(std::size(g_strMap) == std::size(g_keyMap));
               ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
[12/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/micamaterial.cpp.obj
[13/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/sysapiloader.cpp.obj
[14/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/framelesshelper_win.cpp.obj
[15/68] Building CXX object src/core/CMakeFiles/FramelessHelperCore.dir/utils_win.cpp.obj
ninja: build stopped: subcommand failed.
`

**Comment by wangwenx190** [comment]
刚才落下几个宏没补充，这次应该是真没问题了

**Comment by jason-yau** [comment]
> HKEY_CURRENT_USER_LOCAL_SETTINGS

编译成功，谢谢！

**Comment by wangwenx190** [comment]
😁
