### ISSUE TITLE
莫名的分界线

### ISSUE THREAD

**Issue by wogeri-zxs** [wangwenx190/framelesshelper#159]
从2.3第一次尝试您的demo，发现在我的第三屏会有分界线。win10，qt 5.15.2
![bug](https://user-images.githubusercontent.com/70737066/193016058-7b7cbf80-aa24-4d96-8c9d-92e277fa1635.png)
![set](https://user-images.githubusercontent.com/70737066/193016248-938542fa-5dac-431c-9de3-bc46a7f4c837.png)

**Comment by wangwenx190** [comment]
qt对多屏的支持不够完美。只要把demo的blurBehindWindow功能关掉就没这个现象了。

**Comment by wogeri-zxs** [comment]
确实可以 多谢
