### ISSUE TITLE
conflicts with the qml async object creation

### ISSUE THREAD

**Issue by micpub** [wangwenx190/framelesshelper#160]
i am attaching 2 qml files, one is working (the one using FramelessHelper) and the second one is not working (the one using FramelessWindow).
im not sure if its a bug in qt itself that this lib is triggering or if its causes by this lib.
the bug can be triggered on linux, windows (i havent tested mac - but prolly also affected).

reproducibility: always
qt used: 6.3.2

just replace MainWindow.qml in the lib Quick example with one of the 2 attached files and compile.

until its fixed i would say that qml apps(that use dynamic object creation) shouldnt use this library via FramelessWindow element as its breaks logic completly.

[test-case.zip](https://github.com/wangwenx190/framelesshelper/files/9733553/test-case.zip)

**Comment by micpub** [comment]
also regarding the problem:

--- when using FramelessHelper the app window shows immediately(console log), the objects created are not ready immediately (good - async way) and are created 'slowly' over time. - ui counter can be seen as they are created.

--- when using FramelessWindow the app window doesnt start immediately (cause it waits till all elements are created (which should be created over time[async]) - the ui counter cant be seen(cause all already created). The objects are ready immediately(console log) (shouldnt - shall be async)

**Comment by wangwenx190** [comment]
I'm sorry the qt quick implementation is having such critical issue. Replacing the top level element with FramelessWindow is not an ideal solution indeed, so I'm working on a WindowBorder element for Qt Quick so that you don't have to use FramelessWindow at all. It'll be merged to the main branch within a few days hopefully. And of course I will also fix the issues you mentioned here.

**Comment by wangwenx190** [comment]
> also regarding the problem:
> 
> --- when using FramelessHelper the app window shows immediately(console log), the objects created are not ready immediately (good - async way) and are created 'slowly' over time. - ui counter can be seen as they are created.
> 
> --- when using FramelessWindow the app window doesnt start immediately (cause it waits till all elements are created (which should be created over time[async]) - the ui counter cant be seen(cause all already created). The objects are ready immediately(console log) (shouldnt - shall be async)

This can be fixed, but it requires some re-structure of the current code, so I need to fix it after I done the implementation of WindowBorder, sorry.

**Comment by wangwenx190** [comment]
@micpub Hi, it seems the latest code doesn't have this issue anymore, can you check it?

**Comment by wangwenx190** [comment]
I'm closing this issue now, you can reopen it if you think it's not fixed

**Comment by micpub** [comment]
thank you very much.
