### ISSUE TITLE
在 MacOS  12.6 上窗口无法缩放

### ISSUE THREAD

**Issue by jason-yau** [wangwenx190/framelesshelper#163]
在 MacOS 12.6 上窗口无法缩放，而且没有圆角，见图
![image](https://user-images.githubusercontent.com/91023929/194891496-1818ba1e-a878-496d-bef8-efcf2172c05d.png)

**Comment by wangwenx190** [comment]
没法缩放是什么意思？是窗口没法调整大小吗？

**Comment by wangwenx190** [comment]
widget程序确实没有圆角，这个目前我没有办法。quick程序还是能保留圆角的。

**Comment by jason-yau** [comment]
> 没法缩放是什么意思？是窗口没法调整大小吗？

是的，没法调整窗口大小，右上角的最大化倒是可用

**Comment by wangwenx190** [comment]
圆角问题应该是解决了，先关了
