### ISSUE TITLE
gtk_settings_get_default() returns nullptr

### ISSUE THREAD

**Issue by trbogdanov** [wangwenx190/framelesshelper#170]
Hello again, @wangwenx190 !

I'm using Debian based Linux (not Ubuntu). Following your instructions in the readme I have installed the GTK3 development package (libgtk-3-dev:amd64 version 3.24.30), before building `framelesshelper` (tag 2.2.1). And it built without any related errors.

Now I'm trying to run a debug configuration of application linked to your lib. However `Q_ASSERT` triggered at the very beginning in the template function `gtkSetting` (*src/core/utils_linux.cpp*), because `gtk_settings_get_default()` returns `nullptr`.

Searching the GTK documentation I found that `gtk_init` (https://docs.gtk.org/gtk3/func.init.html) should be called first. This helped, but now I'm getting warning on start: _"Gtk-WARNING **: Theme parsing error: gtk.css:3877:13: Not using units is deprecated. Assuming 'px'."_

I'm not familiar with GTK, could you please explain, what I'm doing wrong?

**Comment by wangwenx190** [comment]
Maybe you can just ignore the warning message from GTK. However, it should not be necessary to call `gtk_init()` manually, it's strange. Can you try the latest code from the main branch instead? Do you still have this issue?

**Comment by wangwenx190** [comment]
> It would be great if you could call gtk_init() in the FramelessHelper::Core::initialize() function for example. Is it possible?

I'm not quite sure about this, because I'm not very familiar with GTK either. You can try this in your own fork to see if it can work reliably. If so, we can merge it to the main repository. What do you think?

**Comment by trbogdanov** [comment]
Take a look please

**Comment by wangwenx190** [comment]
Thanks! I've left a comment there.
