### ISSUE TITLE
求助：能不能实现多个无边框可缩放窗口？

### ISSUE THREAD

**Issue by jason-yau** [wangwenx190/framelesshelper#172]
如题

**Comment by wangwenx190** [comment]
现在的示例工程不就是多窗口的吗？你想实现什么效果？

**Comment by jason-yau** [comment]
项目中的示例都是单个窗口的啊，我没有见到有子窗体的啊，我自己在子窗体中继承了 `FramelessDialog`，但是编译后外层框架还在

**Comment by wangwenx190** [comment]
你用的是git上最新的代码吗？最新的代码中，widget和quick示例都是多窗口的

**Comment by wangwenx190** [comment]
你的意思是嵌套的窗口吗？这个暂时还不支持，目前只能支持互相独立的顶层窗口

**Comment by wangwenx190** [comment]
已解决
