### ISSUE TITLE
ERROR Install Qt 6.4.0 Mac OS 13.0

### ISSUE THREAD

**Issue by mirroI** [wangwenx190/framelesshelper#175]
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: no LC_RPATH load command with path: /Users/mirrol/Documents/A_TEMP_DIR/lib found in: /usr/local/./Quick.app/Contents/MacOS/Quick (for architecture x86_64), required for specified option "-delete_rpath /Users/mirrol/Documents/A_TEMP_DIR/lib"
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: no LC_RPATH load command with path: /Users/mirrol/Applications/Qt/6.4.0/macos/lib found in: /usr/local/./Quick.app/Contents/MacOS/Quick (for architecture x86_64), required for specified option "-delete_rpath /Users/mirrol/Applications/Qt/6.4.0/macos/lib"
CMake Error at /Users/mirrol/Applications/Qt/6.4.0/macos/lib/cmake/Qt6Qml/Qt6QmlDeploySupport.cmake:50 (message):
  No QML imports information recorded for target Quick.  The target must be
  an executable and qt_add_qml_module() must have been called with it.  If
  using a CMake version lower than 3.19, ensure that the executable is
  manually finalized with qt_finalize_target().  Missing file:

      /Users/mirrol/Documents/A_TEMP_DIR/.qt/deploy_qml_imports/Quick.cmake
Call Stack (most recent call first):
  .qt/deploy_qml_app_Quick_57a92c478e:3 (qt_deploy_qml_imports)
  examples/quick/cmake_install.cmake:52 (include)
  examples/cmake_install.cmake:62 (include)
  cmake_install.cmake:54 (include)

**Comment by wangwenx190** [comment]
For now you can use `-DFRAMELESSHELPER_EXAMPLES_DEPLOYQT =OFF` to fix this error temporarily.

**Comment by mirroI** [comment]
Thank.
When can you fix the quick example? <CRITICAL> The QML engine failed to create component: QUrl("qrc:/Demo/HomePage.qml")

**Comment by wangwenx190** [comment]
Why can't the QML engine create the component? Can you provide more debug log?

**Comment by mirroI** [comment]
QML debugging is enabled. Only use this in a safe environment.
[2022/10/31 12:35:04.632] <WARNING> QQmlApplicationEngine failed to load component
[2022/10/31 12:35:04.633] <WARNING> qrc:/Demo/HomePage.qml: module "QtQml" version 1.0 is not installed
[2022/10/31 12:35:04.633] <WARNING> qrc:/Demo/HomePage.qml: module "QtQml" version 1.0 is not installed
[2022/10/31 12:35:04.633] <WARNING> qrc:/Demo/HomePage.qml: Failed to load dependent import "QtQml" version 1.0
[2022/10/31 12:35:04.633] <WARNING> qrc:/Demo/HomePage.qml: Failed to load dependencies for module "org.wangwenx190.FramelessHelper" version 1.0
[2022/10/31 12:35:04.633] <WARNING> qrc:/Demo/HomePage.qml: Failed to load dependent import "org.wangwenx190.FramelessHelper" version 1.0
[2022/10/31 12:35:04.643] <CRITICAL> The QML engine failed to create component: QUrl("qrc:/Demo/HomePage.qml")

**Comment by wangwenx190** [comment]
You need to use the `macdeployqt` tool to copy the Qt dependencies to the binary folder.

**Comment by wangwenx190** [comment]
Or you can just drop the binary file to Qt's bin directory.

**Comment by mirroI** [comment]
Thank!

**Comment by mirroI** [comment]
ninja: build stopped: subcommand failed.

Log:
PS C:\Users\Alexe\Documents\A_TEMP_DIR> C:\Qt\Tools\CMake_64\bin\cmake.exe -DCMAKE_INSTALL_PREFIX:PATH="C:/Program Files (x86)\FramelessHelper" -DCMAKE_PREFIX_PATH:PATH="C:/Qt/6.4.0/msvc2019_64" -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/HostX64/x64/cl.exe" -DCMAKE_MAKE_PROGRAM:FILEPATG="C:\Qt\Tools\Ninja\ninja" -GNinja C:\Users\Alexe\Documents\framelesshelper
-- The CXX compiler identification is MSVC 19.33.31630.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/HostX64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/HostX64/x64/cl.exe - broken
CMake Error at C:/Qt/Tools/CMake_64/share/cmake-3.24/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/HostX64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Alexe/Documents/A_TEMP_DIR/CMakeFiles/CMakeTmp

    Run Build Command(s):C:\Qt\Tools\Ninja\ninja cmTC_c460f && [1/2] Building CXX object CMakeFiles\cmTC_c460f.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_c460f.exe
    FAILED: cmTC_c460f.exe
    cmd.exe /C "cd . && C:\Qt\Tools\CMake_64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_c460f.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_c460f.dir\testCXXCompiler.cxx.obj  /out:cmTC_c460f.exe /implib:cmTC_c460f.lib /pdb:cmTC_c460f.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_c460f.dir/manifest.res CMakeFiles\cmTC_c460f.dir/manifest.rc" failed (exit code 0) with the following output:
    Не удается найти указанный файл
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Alexe/Documents/A_TEMP_DIR/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Alexe/Documents/A_TEMP_DIR/CMakeFiles/CMakeError.log".

**Comment by wangwenx190** [comment]
From your CMake log, I can see CMake failed to compile a simple test program, so it stopped running. It even has not began to parse this project yet. You should check what's wrong with your toolchain.

**Comment by mirroI** [comment]
Thank!
