### ISSUE TITLE
Cannot resize or move window on Linux?

### ISSUE THREAD

**Issue by SineStriker** [wangwenx190/framelesshelper#178]
Either the master branch or 2.3.0 release, the window is not movable or resizable. Maybe there 're some new mistakes since it doesn't occur in early versions.

**Comment by wangwenx190** [comment]
What's your Qt version?

**Comment by SineStriker** [comment]
5.15.2

**Comment by wangwenx190** [comment]
Can you try to comment out the following line and check whether this issue is fixed or not?

https://github.com/wangwenx190/framelesshelper/blob/9715bd9d4b2143ddac99b8c557913fcc06fc17d2/src/core/framelesshelpercore_global.cpp#L149

**Comment by SineStriker** [comment]
> Can you try to comment out the following line and check whether this issue is fixed or not?
> 
> https://github.com/wangwenx190/framelesshelper/blob/9715bd9d4b2143ddac99b8c557913fcc06fc17d2/src/core/framelesshelpercore_global.cpp#L149

Doesn't work.

**Comment by wangwenx190** [comment]
OK. What's your system and desktop environment?

**Comment by wangwenx190** [comment]
这很奇怪，Linux方面的代码几乎没怎么动过，怎么可能突然就不能用了呢

**Comment by SineStriker** [comment]
ubuntu 20.04
kenel 5.15.0-48-generic
GNOME Shell 3.36.9

Cannot use Chinese due to lack of input method.

**Comment by SineStriker** [comment]
我也不知道为什么，中间版本几乎也没怎么试过，突然就有问题了。

**Comment by wangwenx190** [comment]
我需要装个虚拟机试一下。

**Comment by wangwenx190** [comment]
最新代码应该是没问题了，是我之前重构GTK代码时引入的问题
