### ISSUE TITLE
界面中弹出菜单 QMenu 后。 点击title区域菜单不会关闭

### ISSUE THREAD

**Issue by jackfong66** [wangwenx190/framelesshelper#179]
界面中弹出菜单 QMenu 后。 点击title区域菜单不会关闭 ， 还可以拖动窗口。

没有触发焦点丢失？

**Comment by wangwenx190** [comment]
不是很确定是什么导致的

**Comment by 0ices** [comment]
我使用的方法是写一个EventFilter来拿走焦点，但是这种处理方式也有很大的弊端，比如每一个输入框都要做特殊处理，因为点击一次会让主窗口先夺走焦点，特殊处理的方法一般是使用一个timer，timer结束后再处理焦点失去后要实现的效果

EventFilter的实现方式如下
`    EventFilter {
        source: window
        onPressed: {
            mainItem.focus = true
            window.requestActivate()
        }
    }`
`class EventFilter : public QObject {
		Q_OBJECT

		Q_PROPERTY(QObject* source READ getSource WRITE setSource) // 源
	public:
		explicit EventFilter(QObject* parent = nullptr);
		bool eventFilter(QObject* obj, QEvent* event) override;
		QObject* getSource() { return source; }
		void setSource(QObject* source)
		{
			source->installEventFilter(this);
			this->source = source;
		};
	Q_SIGNALS:
		Q_SIGNAL void moved(QPointF point);
        Q_SIGNAL void pressed(QMouseEvent* mouse);
        Q_SIGNAL void released(QMouseEvent* mouse);
		Q_SIGNAL void entered();
		Q_SIGNAL void exited();
	private:
		QObject* source;
	};`
如果有更好的方式请不吝赐教

**Comment by jackfong66** [comment]
> 我使用的方法是写一个EventFilter来拿走焦点，但是这种处理方式也有很大的弊端，比如每一个输入框都要做特殊处理，因为点击一次会让主窗口先夺走焦点，特殊处理的方法一般是使用一个timer，timer结束后再处理焦点失去后要实现的效果
> 
> EventFilter的实现方式如下'class EventFilter ： public QObject {Q_OBJECT` EventFilter { source: window onPressed: { mainItem.focus = true window.requestActivate() } }`
> 
> ```
> 	Q_PROPERTY(QObject* source READ getSource WRITE setSource) // 源
> public:
> 	explicit EventFilter(QObject* parent = nullptr);
> 	bool eventFilter(QObject* obj, QEvent* event) override;
> 	QObject* getSource() { return source; }
> 	void setSource(QObject* source)
> 	{
> 		source->installEventFilter(this);
> 		this->source = source;
> 	};
> Q_SIGNALS:
> 	Q_SIGNAL void moved(QPointF point);
>     Q_SIGNAL void pressed(QMouseEvent* mouse);
>     Q_SIGNAL void released(QMouseEvent* mouse);
> 	Q_SIGNAL void entered();
> 	Q_SIGNAL void exited();
> private:
> 	QObject* source;
> };`
> ```
> 
> 如果有更好的方式请不吝赐教

--------------------------------------
我在framelesshelper_win.cpp 点击后调用一个外部函数，在函数中：

```
//framelesshelper_win.cpp
            if (isTitleBar) {
                *result = HTCAPTION;
                data.params.closePopupWidget();
                return true;
            }

//framelesswidgethelper.cpp
    void FramelessWidgetsHelperPrivate::closePopupWidget()
    {
        auto popup = QApplication::activePopupWidget();
        if (popup)
        {
            popup->close();
        }
    }
```

**Comment by JulienMaille** [comment]
I cannot reproduce this issue, clicking the title will close the menu (unless this bug appeared with latest commits)

**Comment by wangwenx190** [comment]
我试了下，没遇到这个问题。你是怎么触发的？

**Comment by wangwenx190** [comment]
一直无法复现，先关了
