### ISSUE TITLE
win去除边框后无法固定窗口大小

### ISSUE THREAD

**Issue by wufangzhao** [wangwenx190/framelesshelper#18]
调用WinNativeEventFilter::addFramelessWindow后再调用setFixedSize固定窗口大小, 还是能用鼠标改变窗口大小. 
不调用WinNativeEventFilter::addFramelessWindow时正常, 窗口大小无法改变

qt版本 5.12.0

**Comment by wangwenx190** [comment]
不好意思忘记回复你了，耽误了这么多天，真的很抱歉。

请使用如下方法锁定窗口尺寸：

```cpp
WinNativeEventFilter::WINDOWDATA data;
data.fixedSize = TRUE;
WinNativeEventFilter::addFramelessWindow(reinterpret_cast<HWND>(widget.winId()), &data);
```

`fixedSize`这个成员变量是可以在运行时修改的，你也可以在执行`addFramelessWindow`后再设置这个：

```cpp
const auto data = WinNativeEventFilter::windowData(reinterpret_cast<HWND>(widget.winId()));
data.fixedSize = TRUE;
```

qt提供的接口不生效是因为我在内部把这个消息拦截了

**Comment by wangwenx190** [comment]
窗口的最小大小和最大大小也不能用qt的接口设置，要用`data.minimumSize`和`data.maximumSize`设置，这两个也可以在运行时修改。设置方法和前面提到的一样。

如果还是不起作用，请再来这里反馈。

感谢使用。

**Comment by wufangzhao** [comment]
好的，非常感谢
