### ISSUE TITLE
置顶状态双击标题栏无法最大化

### ISSUE THREAD

**Issue by 0ices** [wangwenx190/framelesshelper#180]

**Comment by wangwenx190** [comment]
自带的示例项目可以复现吗

**Comment by 0ices** [comment]
我刚编译了示例项目，但里面好像没有置顶按钮

**Comment by wangwenx190** [comment]
确实没有置顶按钮，但你可以直接用代码置顶。Qt自带置顶功能，或者你是直接用win32 api置顶的？

**Comment by 0ices** [comment]
我往window添加了flag Qt.WindowStaysOnTopHint

**Comment by wangwenx190** [comment]
我总感觉不是这个项目导致的，普通的Qt窗口也有这个问题吗？

**Comment by 0ices** [comment]
我试验了一个Qt的窗口，是没有这个问题的

**Comment by wangwenx190** [comment]
收到，我得看看是怎么回事

**Comment by SineStriker** [comment]
> 我往window添加了flag Qt.WindowStaysOnTopHint

这个Flag在Windows上没什么用的（我以前在普通Qt窗口用这个Flag似乎出过莫名其妙的问题），建议使用Windows API置顶。

**Comment by wangwenx190** [comment]
> 这个Flag在Windows上没什么用的

这话错了，这个flag一直都是可用的

> 我以前在普通Qt窗口用这个Flag似乎出过莫名其妙的问题

是不是置顶后窗口会消失？这个是已知的问题，也不知道算是bug还是Qt有意为之，总之只要再show()出来就好了

> 使用Windows API置顶

这个确实一直没什么问题，但缺点是会和Qt内部的一些数据失去同步。Qt内部是会根据window flag调整行为的。

**Comment by wangwenx190** [comment]
我这里没发现这个问题，窗口还是能正常最大化。

**Comment by wangwenx190** [comment]
我一直无法复现此问题，先关了
