### ISSUE TITLE
QLoggingRegistry死锁

### ISSUE THREAD

**Issue by SineStriker** [wangwenx190/framelesshelper#181]
因为2.3.1更新了关闭Debug输出，我就换了2.3.1，后来发现不改代码还是有一堆Debug，查看源码发现必须调用`FramelessHelper::Core::initialize`给QLoggingRegistry装事件过滤器才能关闭Debug输出。

但是我这个情况比较尴尬，因为我是在Qt的Plugin里调用的FramelessHelper，主程序是没有链接FramelessHelper库的，也就是说没有办法在QApplication初始化前调用`initialize`。然后我尝试在第一次加载FramelessHelper前调用`initialize`，之后就出现了死锁。

简单分析了下原因，`initialize`函数中安装事件过滤器前拿了`coreData`的全局锁，在最开始就调用`initialize`由于QLoggingCategory还未实例化，就不用执行`updateRules`，直到第一次需要输出内容QLoggingCategory才会实例化，这样两次拿锁就错开了。但是在我的程序的场景里，在FramelessHelper初始化之前需要输出一些内容，所以`initialize`和`updateRules`就嵌套了，出现了死锁。

我个人建议是，如果要屏蔽输出，可能没有必要采用这种给QLoggingCategory全局加锁的方式，因为主程序真的很有可能没办法调用`FramelessHelper::Core::initialize`函数，建议直接用条件编译。。。

这个问题现在没法解决。

**Comment by SineStriker** [comment]
有两种办法，要么不使用事件过滤器而直接用条件编译，要么实现QLoggingCategory事件过滤器运行时热重载。我推荐使用前者，作为一个库，改全局的东西越少越不容易出问题。

**Comment by wangwenx190** [comment]
> 我个人建议是，如果要屏蔽输出，可能没有必要采用这种给QLoggingCategory全局加锁的方式，因为主程序真的很有可能没办法调用FramelessHelper::Core::initialize函数，建议直接用条件编译。。。

你的意思是直接把锁去掉还是说不采用目前这种屏蔽日志的方式？

**Comment by SineStriker** [comment]
我觉得屏蔽日志可以直接用条件编译，比如说在NO_DEBUG的预设下，把`DEBUG`宏直接define成空。然后其实源码里为什么加事件过滤器之前还要拿锁我我没看懂...

**Comment by wangwenx190** [comment]
> 把DEBUG宏直接define成空

这个不好实现吧，我调用的形式都是 DEBUG << ... << ...，直接定义成空，后面的东西不会导致出错吗？

> 然后其实源码里为什么加事件过滤器之前还要拿锁我我没看懂...

可能不需要加锁，因为我有点滥用锁了……

**Comment by wangwenx190** [comment]
不加过滤器也是可以的，不过稍微麻烦点，我得实验一下。

**Comment by SineStriker** [comment]
> > 把DEBUG宏直接define成空
> 
> 这个不好实现吧，我调用的形式都是 DEBUG << ... << ...，直接定义成空，后面的东西不会导致出错吗？
> 
> > 然后其实源码里为什么加事件过滤器之前还要拿锁我我没看懂...
> 
> 可能不需要加锁，因为我有点滥用锁了……

Qt里面提供了一种替代的宏叫`QT_NO_QDEBUG_MACRO`，定义成这个就行，不是定义成空我说错了。

**Comment by wangwenx190** [comment]
> Qt里面提供了一种替代的宏叫QT_NO_QDEBUG_MACRO，定义成这个就行

第一次听说，我试试，如果可以的话，确实比安装过滤器优雅很多

**Comment by wangwenx190** [comment]
官方文档里没有，不过网上有博客讲的，确实不错，感谢

**Comment by SineStriker** [comment]
> 官方文档里没有，不过网上有博客讲的，确实不错，感谢

好像源码里为了实现不同条件输出不同的东西折腾了挺多的，用这个宏应该可以全去掉了）hhh

**Comment by wangwenx190** [comment]
总之非常感谢，学到了。我马上更新代码。

**Comment by wangwenx190** [comment]
FramelessHelper::Core::initialize() 这个函数，如果你没法手动调用，也建议你把里面一些函数执行一下，对于DPI缩放还有暗黑模式还是有些改进的。
