### ISSUE TITLE
银河麒麟V10界面抖动

### ISSUE THREAD

**Issue by programClown** [wangwenx190/framelesshelper#185]
https://user-images.githubusercontent.com/8369309/203090162-4396bc66-56d3-405c-84fb-5bc6b048032e.mp4

我在银河麒麟上测试，发现运行的时候会卡死界面，鼠标不停地抖动，关闭不了！整个界面无法操作了。

在运行可执行文件的时候有两个错误，
1，Failed to load module "canberra-gtk-module"
安装`sudo apt-get install libcanberra-gtk-module`后，必须sudo运行才不会报错，普通账号执行还是报这个错

2，bind-WARNING **: 23:00:57.900: AT-SPI: Error retrieving accessibility bus address: 
我搜索了安装了如下命令
`sudo apt-get install at-spi2-core`

上边两个问题都不报错了以后，sudo执行还是视频中所示

你有空看看这个问题，谢谢

**Comment by programClown** [comment]
我试了https://github.com/ONLYOFFICE/desktop-apps的无边框设计，没有抖动，您可以参考一下这个项目

**Comment by wangwenx190** [comment]
没听说Linux上有这么严重的问题，我需要亲自验证下

**Comment by wangwenx190** [comment]
> 我试了https://github.com/ONLYOFFICE/desktop-apps的无边框设计，没有抖动，您可以参考一下这个项目

感谢！

**Comment by programClown** [comment]
我是在虚拟机里面测试的，直接用的银河麒麟仓库里的是5.12.8，镜像地址`https://distro-images.kylinos.cn:8802/web_pungi/download/share/tXbGgIYCdQEv5z0lPypmKTqAse2rojJx/Kylin-Desktop-V10-SP1-General-Release-2203-ARM64.iso`

**Comment by programClown** [comment]
我自己又用实体机验证了一下，发现没有抖动，只有在VMWare里面有这个问题，不只是是不是虚拟化的问题，这个问题就这样吧 @wangwenx190
