### ISSUE TITLE
在实例mainwindow里面再次弹出dialog(无边框)程序崩溃

### ISSUE THREAD

**Issue by 1bbb** [wangwenx190/framelesshelper#188]
![image](https://user-images.githubusercontent.com/3361974/205894122-ed9c3c72-b9bd-4edd-a1a1-390e60f02ebc.png)
如上图：创建dialog的时候传入父指针，点击按钮程序崩溃。不传则可以正确运行。

**Comment by 1bbb** [comment]
![image](https://user-images.githubusercontent.com/3361974/205895754-9b4b2a87-08e0-427e-8b13-3055fc92bcd0.png)
windowhandle()指针为空

**Comment by 1bbb** [comment]
> 

感谢回复，我稍微改了下貌似是可以嵌套无边框了，目前没测出有啥bug，麻烦看下。
![image](https://user-images.githubusercontent.com/3361974/206108395-d37f9b15-362d-4dd3-abfc-b4a06048a3f2.png)
![image](https://user-images.githubusercontent.com/3361974/206108536-c5a9aa69-9f25-41b2-b4de-49c55c04f287.png)
![image](https://user-images.githubusercontent.com/3361974/206108583-6a99caba-cbd2-443d-b08a-6de9e6d9532a.png)

**Comment by wangwenx190** [comment]
那几个属性FramelessHelper默认都会设置的，你注释掉再看看呢。所以问题在于获取顶层窗口的方法不对吗？

**Comment by 1bbb** [comment]
> 那几个属性FramelessHelper默认都会设置的，你注释掉再看看呢。所以问题在于获取顶层窗口的方法不对吗？

![image](https://user-images.githubusercontent.com/3361974/206109863-011423c2-64e1-4527-85be-d21e97b21280.png)
这边必须先设置，不然构造FramelessDialogPrivate的时候会崩溃，应为windowhandle为空

**Comment by wangwenx190** [comment]
好的。同样的修改对FramelessWidget有效吗

**Comment by 1bbb** [comment]
> 

![image](https://user-images.githubusercontent.com/3361974/206114829-c545ea11-424e-4467-be0e-abb3af017366.png)
windowsFlag需要填Qt::Window

**Comment by wangwenx190** [comment]
> windowsFlag需要填Qt::Window

这个不是默认的吗

**Comment by 1bbb** [comment]
> > windowsFlag需要填Qt::Window
> 
> 这个不是默认的吗

我使用的QT是5.12.7版本，貌似必须要设置。感谢你开源这套无边框框架，确实很优秀，希望可以持续更新

**Comment by wangwenx190** [comment]
你可以提个PR，这也是一个不小的改进

**Comment by 1bbb** [comment]
> 



> 你可以提个PR，这也是一个不小的改进

好的，我有空提交下。

**Comment by wangwenx190** [comment]
已解决
