### ISSUE TITLE
能否实现窗体圆角效果？

### ISSUE THREAD

**Issue by jason-yau** [wangwenx190/framelesshelper#192]
问题如题。我看 `Global::Option::WindowUseRoundCorners` 的枚举，但是我设置了没有生效，想问一下怎样实现圆角效果？

**Comment by wangwenx190** [comment]
原本的实现不够好，已经删掉了。目前暂时想不到好办法。传统方法是使用透明窗口，这样能实现任意形状的窗口。

**Comment by jason-yau** [comment]
好吧，那看来只能用传统的方法了
