### ISSUE TITLE
关于编译问题

### ISSUE THREAD

**Issue by 1bbb** [wangwenx190/framelesshelper#193]
![image](https://user-images.githubusercontent.com/3361974/208039006-685b8020-9804-43f1-82e0-fceac99b48e7.png)
windows sdk 10.0.16299.0 有如上错误

**Comment by wangwenx190** [comment]
我这边是建议尽量用新的SDK，如果实在不方便，我可以加个开关，把合规性检查关掉。

**Comment by 1bbb** [comment]
> 我这边是建议尽量用新的SDK，如果实在不方便，我可以加个开关，把合规性检查关掉。
方便的话加个开关，我用的sdk确实比较老了

**Comment by wangwenx190** [comment]
代码更新了，试试设置`FRAMELESSHELPER_NO_PERMISSIVE_CHECKS`为ON呢
