### ISSUE TITLE
mac上dock栏图标上的菜单项丢失，没有系统圆角

### ISSUE THREAD

**Issue by liwey1985** [wangwenx190/framelesshelper#198]
<img width="476" alt="企业微信截图_d3d81166-2858-45ce-8c62-f3cad67790cd" src="https://user-images.githubusercontent.com/108964761/210197762-c1a9d14e-bfe5-43ef-81c7-cca4b5960a08.png">

如图，用在我的项目中，mac下会丢失上图的两个窗口菜单项（不过自带example并没有这个问题），另外没有系统圆角。我试着改动下面代码测试, 则没有这两个问题。 这里主要有一个疑问是为什么mac上要加上 `Qt::FramelessWindowHint`， 不加这个除了会显示出来原生系统按钮还有别的问题吗？ 如果只是这一个问题，这个倒是有方案去除。所以我想请教下不用  `Qt::FramelessWindowHint`会有哪些问题，如果没别的致命问题，我们准备去掉这个逻辑。
```cpp
const auto shouldApplyFramelessFlag = [&params]() -> bool {
#ifdef Q_OS_MACOS
        return true; // 这里直接返回true
        const auto widget = params.getWidgetHandle();
        return (widget && widget->isWidgetType());
#elif defined(Q_OS_LINUX)
        Q_UNUSED(params);
        return !Utils::isCustomDecorationSupported();
#else // Windows
        Q_UNUSED(params);
        return true;
#endif // Q_OS_MACOS
    }();
```

**Comment by wangwenx190** [comment]
没有`Qt::FramelessWindowHint`的话MainWindow那个demo还正常吗

**Comment by wangwenx190** [comment]
不用`Qt::FramelessWindowHint`确实没什么非常致命的问题，主要是有QMenuBar的情况会不太正常

**Comment by wangwenx190** [comment]
我用Qt 6.5 + macOS 13已经无法复现我之前遇到的问题了，看来确实可以按照你所说的这样修改。
