### ISSUE TITLE
Segmentation fault occurs in libX11 when a QFileDialog is opened on Linux

### ISSUE THREAD

**Issue by agosez** [wangwenx190/framelesshelper#199]
Hello @wangwenx190 !

I am a Debian user currently running **Debian GNU/Linux 11 (bullseye)** and I am using your library in a wide **Qt 5.15.2** project. I recently encountered a crash in my application when opening **QFileDialog** to browse a directory.

I was able to trace the issue down to the FramelessHelper lib and to the specific modification performed in [this](https://github.com/wangwenx190/framelesshelper/commit/78638a3e2350955392498679cf0257b58b391aed) commit.

I figured that the call to **gtk_init()** lead to this problem and as I was searching around for a solution I came around [this](https://github.com/sqweek/dialog/issues/51) issue linking to [this other](https://github.com/OpenDiablo2/dialog/pull/2) issue, suggesting that a call to [XInitThreads()](https://www.x.org/releases/X11R7.5/doc/man/man3/XInitThreads.3.html) could be a workaround to fix this.

I tested it locally and it seems to work fine, but I'm not an expert in this area so would you have time to investigate and see if you can reproduce this ?

Thank you very much !

**Comment by wangwenx190** [comment]
Thanks for your investigation! I'll fix this issue as soon as possible!
