### ISSUE TITLE
Not an issue, just to say you Thank You!(thanked a bit earlier, see my new issue)

### ISSUE THREAD

**Issue by shujaatak** [wangwenx190/framelesshelper#2]
This is the **_BEST EVER & TRUE_ Frameless Helper** ever made for Qt! You have done super outstanding job! Thank you so much!!!

**Comment by wangwenx190** [comment]
I'm very glad if this repository can help you.
Actually, at the very beginning, most of the code came from [rossy's repository](https://github.com/rossy/borderless-window), his/her repository works quite well however it's a pure Win32 project, I just migrate it to Qt. Now this repository is not so similar to it after many improvements (if they can be called improvements, haha). Anyway, there won't be this repository if rossy didn't create his/her repository.

**NOTICE**
If you are developing Windows applications, please use the `WinNativeEventFilter` class. The `FramelessHelper` class on Windows is just a simple wrapper of it and it's mainly designed to work on UNIX platforms.
