### ISSUE TITLE
[Windows] Restore after maximizing, the window goes out of the screen

### ISSUE THREAD

**Issue by jaredtao** [wangwenx190/framelesshelper#20]
-------------------------------------------------------------
系统：Windows10
Qt：5.9.3、5.14、5.15都有这个问题
编译器：msvc2017
效果图：
![image](https://user-images.githubusercontent.com/10269217/89609734-4b25d800-d8ab-11ea-92bb-b37fb5993785.png)

复现步骤：
1、窗口最大化
2、鼠标向下拖拽标题栏，让窗口从最大化变成常规大小，此时不要放开鼠标，再往上拖到屏幕顶部，触发Win10的Aero效果，自动变成最大化。
3、按Restore按钮，还原到常规大小。
此时窗口会跑到屏幕顶部，标题栏会超出去，如果标题栏高度比较小，就点不到了。

-------------------------------------------------------------
OS: Windows 10
Qt Version: 5.9.3 , 5.14 , 5.15.0
Compiler: msvc2017
Demo Image:
![image](https://user-images.githubusercontent.com/10269217/89609734-4b25d800-d8ab-11ea-92bb-b37fb5993785.png)
Reproduce：
1、make Window Maximize
2、Mouse drag-down title， make window change to normal from maximize， then not release mouse and drag-up caption to the top of screen, window will be maximized by Windows 10 Aero effect
3、Press Restore Button， window restore to normal.
now Window goes out of screen. if the title Bar is too short, you can't use it

**Comment by wangwenx190** [comment]
感谢反馈，按这个步骤确实能复现。我想一下是哪里的问题。

**Comment by wangwenx190** [comment]
目前已经确认是这个函数导致的：
https://github.com/wangwenx190/framelesshelper/blob/50036371a3c1d35c2f9312bc3055ac0180408496/winnativeeventfilter.cpp#L2076
但如果不把自定义的窗口边框传给Qt，会导致我们在改变窗口尺寸时，Qt输出一大堆警告信息。

这个问题我也有点摸不着头脑。不过感觉这个问题只是个小问题，虽然确实是个bug，但我觉得应该很少有人会专门去这么操作。

**Comment by wangwenx190** [comment]
试了一些老牌的商业控件，发现也有这个问题，看来对于Qt程序而言，这个问题普遍存在。

**Comment by jaredtao** [comment]
小问题，影响不大。老牌商业控件 要么没发现，要么发现了也觉得不重要。

**Comment by wangwenx190** [comment]
>
> 老牌商业控件 要么没发现，要么发现了也觉得不重要。
>
是，这个问题触发的条件很苛刻，必须严格按照你那个操作来才能触发，一步不对就触发不了。

我觉得这个问题应该是Qt内部没有考虑自定义边框的情况，最大化时记录的窗口几何位置没有减去自定义标题栏的高度导致的。其实你仔细看一下就会发现，被“吃掉”的高度正好等于你自定义标题栏的高度。如果要解决，还是要从Qt内部入手。

**Comment by wangwenx190** [comment]
由于是Qt内部问题，因此就不在这个项目的考虑范围内了。我抽空研究下，如果有能力解决的话，就贡献给Qt上游。

**Comment by wangwenx190** [comment]
最终发现不是Qt的bug，而是win32窗口普遍存在的问题。没有这个问题的窗口，都是开发者已经自行处理过了。如果使用了Windows默认的逻辑（即调用`DefWindowProc`），都会存在这个问题。现在已修复。Qt上游也马上会合入相关解决方案，预计6.5.1及之后的版本都会修复。

**Comment by JulienMaille** [comment]
Any hope for a Qt 5.15 patch?

**Comment by wangwenx190** [comment]
> Any hope for a Qt 5.15 patch?

@JulienMaille Qt 5.15 branch is in a really strict mode so won't accept any modifications unless it's really critical, such as security issue fixes. So this small fix won't be cherry-picked to Qt 5.15 and I've confirmed that with Qt engineers. However, if you can patch Qt yourself, I can give the link of the upstream patch. But I really recommend you upgrade to Qt6, because Qt6 has included so many Windows specific improvements and fixes which 5.15 don't have.

**Comment by JulienMaille** [comment]
I'm currently stuck with Qt5 due to the removal of QtScript. I'll look at the patch, currently working with KDE set of patches

**Comment by wangwenx190** [comment]
> I'm currently stuck with Qt5 due to the removal of QtScript. I'll look at the patch, currently working with KDE set of patches

@JulienMaille  OK. Here's the link of the upstream fix: <https://codereview.qt-project.org/c/qt/qtbase/+/472926>. You can cherry-pick it to your own custom build of Qt5.
