### ISSUE TITLE
perhaps update the screenshots on the front page?

### ISSUE THREAD

**Issue by PerBothner** [wangwenx190/framelesshelper#203]
Especially for macOS, I think you want to show off the nice "traffic light" buttons!

I'd also make the screen shots smaller, at least for the Widget demo. (I.e. make each window smaller before you take the screenshot.)

**Comment by wangwenx190** [comment]
Yes indeed, the screenshots are outdated and need to be updated. But currently I have very limited access to my mac and linux machine, if you can use your mac machine freely, can you make a pr to help me update the screenshots? Thanks!

**Comment by PerBothner** [comment]
I find the fork+branch PR dance an annoying hassle - but here is a simple screenshot you can use.
![frameless-mac](https://user-images.githubusercontent.com/10293361/217127873-d7cda744-747c-4a37-b7dc-1bef806968f5.png)

**Comment by wangwenx190** [comment]
Thanks! But if you can make a pr, I can add you to the contributor list...

**Comment by PerBothner** [comment]
I don't care.  Maybe if I later contribute something more substantial.

**Comment by wangwenx190** [comment]
OK. Thanks anyway!

**Comment by wangwenx190** [comment]
Do you have a screenshot in dark mode?

**Comment by PerBothner** [comment]
Sure.

![widget-macos-dark](https://user-images.githubusercontent.com/10293361/217145982-31280f2c-06c6-4142-b650-10b72396408f.png)
![widget-macos-light](https://user-images.githubusercontent.com/10293361/217145985-cfc89338-170a-4915-964c-d99ccdf0ecfd.png)

**Comment by wangwenx190** [comment]
Thanks!
