### ISSUE TITLE
标题栏上方存在一根白线

### ISSUE THREAD

**Issue by ifpelset** [wangwenx190/framelesshelper#204]
Windows10下，若将StandardTitleBarPrivate::paintTitleBar中的backgroundColor替换为黑色，则标题栏上会有一根白线，是否可以去掉那根白线呢？

**Comment by wangwenx190** [comment]
大概什么样子，能发个截图吗

**Comment by wangwenx190** [comment]
如果你要修改标题栏的颜色，可以使用我提供的ChromePalette这个类，为什么要直接去修改内部的代码？

**Comment by ifpelset** [comment]
因为标题栏是我这边自己提供的，然后我这边是深色，发现有一条白线，故将你自带的标题栏简单修改颜色为深色，也会出现一条白线。

**Comment by ifpelset** [comment]
![white](https://user-images.githubusercontent.com/5791303/218046022-09279b8f-82ff-4d42-bc55-2c21784d2133.png)
当窗口捕获焦点时会更明显点。

**Comment by ifpelset** [comment]
![image](https://user-images.githubusercontent.com/5791303/218046656-ff05c022-e931-4969-b445-411831d0283b.png)

**Comment by wangwenx190** [comment]
你系统缩放设置了多少？

**Comment by wangwenx190** [comment]
https://github.com/wangwenx190/framelesshelper/blob/2b9d810002905b3e4da46b3e244205f0bc964bca/include/FramelessHelper/Widgets/framelesswidgetshelper.h#L60

试试用这个接口获取WindowBorder对象，然后设置一下边框宽度或颜色

**Comment by wangwenx190** [comment]
或者也可能是我设置content margins了，你可以搜搜setContentsMargins，把margin都改成0，就没这个问题了

**Comment by ZhangHuanSir** [comment]
![12](https://user-images.githubusercontent.com/47553361/227831857-0fb70905-a9e0-4a65-b61d-454d3d7cf7ab.jpg)
直接运行2.3.4版本程序，确实会有条白线。
环境：4k屏，150%缩放，标题栏颜色设置为深色会比较明显

**Comment by wangwenx190** [comment]
白线这个，我从多个用户那里收到了反馈，应该确实是个bug，不过我暂时没触发出来。你是设置了自定义的标题栏颜色才出现这个问题的吗，还是什么都不动就会遇到这个问题？

**Comment by ZhouYing-bit** [comment]
最新的master分支依然有这个bug啊， 在win10 1920x1080分辨率，qt 6.5 msvc2019 
 
 
![image](https://github.com/wangwenx190/framelesshelper/assets/13702789/01d5ca4b-6628-4a21-9131-6bb045355828)
