### ISSUE TITLE
大佬，询问下您是怎么实现最小化和显示动画

### ISSUE THREAD

**Issue by diaoyujiuyongzhezhao** [wangwenx190/framelesshelper#208]
如题，打扰了

**Comment by wangwenx190** [comment]
最小化？直接调用`showMinimized()`就可以了啊。如果你要用原生API，就用`ShowWindow(hwnd, SW_MINIMIZE)`。动画的话，要确保有以下几个flag：`WS_THICKFRAME` + `WS_MINIMIZEBOX`（最小化动画）+`WS_MAXIMIZEBOX`（最大化动画）。

**Comment by diaoyujiuyongzhezhao** [comment]
好的，大佬我解决了，感谢
