### ISSUE TITLE
跨屏幕移动，底部绘制出现异常

### ISSUE THREAD

**Issue by liyangfamily** [wangwenx190/framelesshelper#21]
![image](https://user-images.githubusercontent.com/18086085/94402498-b8186880-019e-11eb-86d2-2643e883f838.png)

1、我尝试过网络上其他很多无边框的方案，都会有这个问题，他们底部和右边会出现这个绘制重复的问题，但是作者您的代码只有底部会出现这个绘制问题。我感觉您找到了解决办法。不知道是我个人的问题还是怎样。希望作者能够花时间在Windows10平台上进行多屏幕测试。感谢作者~

**Comment by liyangfamily** [comment]
windows10+Qt5.12.4 三个屏幕，我是2020/9/26下载的代码，应该是最新的

**Comment by liyangfamily** [comment]
![image](https://user-images.githubusercontent.com/18086085/94404444-9a98ce00-01a1-11eb-9e59-4f8f5d08250d.png)

https://github.com/qtdevs/FramelessHelper

我用这个项目也试过，跨屏幕移动都有问题。

**Comment by wangwenx190** [comment]
我曾经用多个屏幕测试过，如果两个屏幕的DPI不同，有很大的概率会出现类似的问题（表现很像，但不知道是不是同一个问题）。当时我发现，其实控件都没有错位，只是窗口画面没有刷新而已，我采用手动调用resize的方式触发窗口重绘，这个问题就解决了。

我本来想通过Windows API解决的，但是Qt接管了窗口的绘制，很难从外部干预。如果只是单纯的调用`UpdateWindow`或者`RedrawWindow`是没有任何效果的，必须通过Qt自己的绘制流程实现画面的重绘。我暂时还不知道如何实现这个，可能要通过QPA函数实现吧。

**Comment by wangwenx190** [comment]
你可以试试在`WM_DPICHANGED`这个分支里调用一下resize，强制窗口重绘，看看能不能有所改善。最好在resize之前加一个延时（50ms或者100ms），不要在DPI改变后立刻resize，否则可能没有效果。

**Comment by liyangfamily** [comment]
作者您好，我使用WM_MOVE消息，在消息内响应updateWindow(msg->hwnd);
这个问题就解决了，在跨不同DPI屏幕上移动，没有出现过这个情况了。我感觉我这是歪门邪道。。。
不知道这样做有什么风险
![image](https://user-images.githubusercontent.com/18086085/94537765-c38a9300-0275-11eb-8b9e-cc79cfd81fc9.png)

**Comment by wangwenx190** [comment]
你这样做，每次窗口移动都要刷新，别有性能问题就行。而且这样做还是没有处理DPI的问题，如果用户不是移动窗口，而是改变了当前屏幕的DPI呢？

**Comment by wangwenx190** [comment]
这个问题在DPI改变时大概率复现，而DPI改变不一定是窗口被移动到另一个屏幕了，从win10开始，当前屏幕的DPI也可以动态改变了。所以我感觉，如果要根治这个问题，要从DPI方面考虑。

**Comment by wangwenx190** [comment]
有一点要说一下，最新的代码其实没有去掉系统边框，只是把标题栏隐藏了，而一般的做法都是把整个系统边框隐藏，这两种做法的效果不太一样，这个行为通过`shouldHaveWindowFrame`这个函数控制，你可以切换一下看看效果，选一个最满意的。这个只影响Win10系统，Win7~8.1都是完全隐藏的。

**Comment by liyangfamily** [comment]
目前在我的电脑上整体拖动没有出现卡顿，和平时一样流畅。使用该函数前后，VS诊断中CPU占用最高在25。两者图形类似下图：
![image](https://user-images.githubusercontent.com/18086085/94539622-0d747880-0278-11eb-92cf-f7a8c2a26b22.png)
看样子是需要去测试改变DPI的情况。

**Comment by wangwenx190** [comment]
没有卡顿最好了。能解决问题就行，管它是不是“歪门邪道”呢i😂

**Comment by liyangfamily** [comment]
之前我有直接将`shouldHaveWindowFrame`函数`return false；`，发现界面右边和底部都出现了问题，如果保持作者您的策略不变，就只会有底部有问题，所以我还是选择win10中隐藏😂

**Comment by liyangfamily** [comment]
我刚刚试了，直接动态改变DPI，100%->175%，没有问题。但是我从175%->100%，界面就有问题了😂

**Comment by wangwenx190** [comment]
> 
> 
> 我刚刚试了，直接动态改变DPI，100%->175%，没有问题。但是我从175%->100%，界面就有问题了😂
>
>
这个问题是Qt自身的问题，跟有没有窗口边框没有关系。你编译一个正常的Qt程序，也按这个步骤去操作，大概率也会有这个问题的。

**Comment by JulienMaille** [comment]
Hello I noticed the same issue when moving across 2 similar screens (so same dpi). What is the suggested fix? The `WM_MOVE` trick?

**Comment by liyangfamily** [comment]
我使用`WM_MOVE`处理，你可以试试。另外一个问题是DPI从175%到100%会出现刷新问题，需要重新改变窗口大小，这个问题目前还不知道怎么解决

**Comment by JulienMaille** [comment]
THank you @liyangfamily
I'm less concerned by the dpi bug, this is not something you do on a daily basis.

**Comment by JulienMaille** [comment]
> Hello author, I use the WM_MOVE message to respond to updateWindow(msg->hwnd)
Have you tried using WM_EXITSIZEMOVE instead?
https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-exitsizemove

**Comment by wangwenx190** [comment]
> 
> 
> > Hello author, I use the WM_MOVE message to respond to updateWindow(msg->hwnd)
> 
> Have you tried using WM_EXITSIZEMOVE instead?
> https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-exitsizemove

I'm also wondering calling `updateWindow()` in `WM_MOVE` may cause performance issue. What you said is reasonable. It's worth trying.

**Comment by JulienMaille** [comment]
I just tried and unfortunately it doesn't work with `WM_EXITSIZEMOVE`
You need to move a little bit after changing screen for the bottom to be "cleaned up"

**Comment by wangwenx190** [comment]
> 
> 
> I just tried and unfortunately it doesn't work with `WM_EXITSIZEMOVE`
> You need to move a little bit after changing screen for the bottom to be "cleaned up"

It's a bad news. Calling `updateWindow()` will cause the whole window be repainted, if you call this function too often, it may cause performance issue.

**Comment by liyangfamily** [comment]
> > I just tried and unfortunately it doesn't work with `WM_EXITSIZEMOVE`
> > You need to move a little bit after changing screen for the bottom to be "cleaned up"
> 
> It's a bad news. Calling `updateWindow()` will cause the whole window be repainted, if you call this function too often, it may cause performance issue.

性能问题具体表现是什么呢？在哪些情况下会出现呢？我看看会不会有大问题

**Comment by wangwenx190** [comment]
>
> 性能问题具体表现是什么呢？在哪些情况下会出现呢？我看看会不会有大问题
>
我只是从理论上猜测的，因为调用`updateWindow()`会导致整个窗口被重绘，如果窗口比较复杂的话，我怕会有卡顿之类的。我只是这样猜测的，并没有实际测试过。

我去看了`WM_MOVE`的文档，也不确定这个消息是窗口移动结束才会触发还是只要窗口在移动就一直在触发，如果是前者，那我就是杞人忧天了，如果是后者，就有可能会出现我所担心的问题。

See: <https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-move>

**Comment by liyangfamily** [comment]
> > 性能问题具体表现是什么呢？在哪些情况下会出现呢？我看看会不会有大问题
> 
> 我只是从理论上猜测的，因为调用`updateWindow()`会导致整个窗口被重绘，如果窗口比较复杂的话，我怕会有卡顿之类的。我只是这样猜测的，并没有实际测试过。
> 
> 我去看了`WM_MOVE`的文档，也不确定这个消息是窗口移动结束才会触发还是只要窗口在移动就一直在触发，如果是前者，那我就是杞人忧天了，如果是后者，就有可能会出现我所担心的问题。
> 
> See: https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-move

有没有检测应用程序移到不同屏幕的消息呢？如果有的话就可以使用屏幕改变的消息来重绘了。另外我发现在Areo特效左右分屏时还是会出现绘制问题。要响应 `WM_SIZE`重绘窗口😂

**Comment by wangwenx190** [comment]
>
> 有没有检测应用程序移到不同屏幕的消息呢？如果有的话就可以使用屏幕改变的消息来重绘了。
>
我看了看文档，没有这个消息。但我发现有`WM_MOVING`和`WM_SIZING`这种消息，这证明`WM_MOVE`和`WM_SIZE`都是动作结束后才会触发，因此我之前的担心是杞人忧天了。看来我应该把这个小技巧加入到这个repo里，省的用户自己去处理了。
>
> 另外我发现在Areo特效左右分屏时还是会出现绘制问题。要响应 WM_SIZE重绘窗口😂
>
什么绘制问题？还是你在一楼提到的那个吗？

**Comment by wangwenx190** [comment]
> 
> 
> I just tried and unfortunately it doesn't work with `WM_EXITSIZEMOVE`
> You need to move a little bit after changing screen for the bottom to be "cleaned up"

@JulienMaille After reading MS's docs, I now realized it's OK to do this in the `WM_MOVE` block because it seems that it's fired after the window has been moved. It won't be fired during the moving process.

**Comment by liyangfamily** [comment]
WM_MOVE在移动过程中也会触发，我加入debug信息看到。有点不知所措了，我对比电脑版Wechat客户端和我的应用程序，在反复移动过程中，电脑CPU的占用率都比较高，在11%-13%左右。
![image](https://user-images.githubusercontent.com/18086085/95844223-3c601380-0d7b-11eb-99e3-68c5fc954996.png)
![image](https://user-images.githubusercontent.com/18086085/95844913-15eea800-0d7c-11eb-84a9-301ab3110bbc.png)


左右分屏的时候也会出现1楼的那个绘制问题

**Comment by JulienMaille** [comment]
> > 
> > 
> > I just tried and unfortunately it doesn't work with `WM_EXITSIZEMOVE`
> > You need to move a little bit after changing screen for the bottom to be "cleaned up"
> 
> @JulienMaille After reading MS's docs, I now realized it's OK to do this in the `WM_MOVE` block because it seems that it's fired after the window has been moved. It won't be fired during the moving process.

I think I put a breakpoint in WM_MOVE and it was called while moving

**Comment by wangwenx190** [comment]
分屏按理说不应该出现那个问题，因为我自己也用这个代码，分屏时没遇到过那个问题。

而且刚才我用Qt Quick程序测了一下，在`WM_SIZE`和`WM_MOVE`时都执行`updateWindow()`，如果你用窗口的右边或者下边调整窗口的大小，会导致窗口非常卡，而且Quick绘制的内容也跟不上趟，debug版和release版都会这样，看来你看到的现象是对的，`WM_MOVE`会在移动时一直被触发。看来这样搞还是有些问题的。

**Comment by wangwenx190** [comment]
> 
> 
> > > I just tried and unfortunately it doesn't work with `WM_EXITSIZEMOVE`
> > > You need to move a little bit after changing screen for the bottom to be "cleaned up"
> > 
> > 
> > @JulienMaille After reading MS's docs, I now realized it's OK to do this in the `WM_MOVE` block because it seems that it's fired after the window has been moved. It won't be fired during the moving process.
> 
> I think I put a breakpoint in WM_MOVE and it was called while moving

Yes, you are right. Sorry for the wrong conclusion. And after some testing, I found it will cause huge performance regression, at least for Qt Quick applications.

**Comment by liyangfamily** [comment]
我尝试在`WM_MOVE`中使用`QApplication::desktop()->screenNumber(this)`判断屏幕Number，如果数值改变，就调用刷新重绘，这样就只会在跨屏幕时重绘一次啦~应该就不会又性能问题了。 @wangwenx190 @JulienMaille

**Comment by wangwenx190** [comment]
> 
> 
> 我尝试在`WM_MOVE`中使用`QApplication::desktop()->screenNumber(this)`判断屏幕Number，如果数值改变，就调用刷新重绘，这样就只会在跨屏幕时重绘一次啦~应该就不会又性能问题了。 @wangwenx190 @JulienMaille

有道理

**Comment by liyangfamily** [comment]
![image](https://user-images.githubusercontent.com/18086085/95850803-f5c2e700-0d83-11eb-80fc-dc62bce6576a.png)
你可以看到在分屏的时候，底部会出现绘制问题。我现在是用`WM_SIZE`来处理这个问题，但是你说在手动改变大小时，会出现比较大的性能问题。我不知道还有什么办法能够解决这个问题😥

**Comment by wangwenx190** [comment]
>
> 你可以看到在分屏的时候，底部会出现绘制问题。我现在是用WM_SIZE来处理这个问题，但是你说在手动改变大小时，会出现比较大的性能问题。我不知道还有什么办法能够解决这个问题😥
>
是的，我刚才又测了下，发现不管是`WM_MOVE`还是`WM_SIZE`，还是两个一起，都会导致严重卡顿，不过你没遇到的话，可以先用着，可能是Qt Quick特有的问题

**Comment by liyangfamily** [comment]
通过判断屏幕序号可以解决WM_MOVE刷新性能的问题，但是分屏绘制异常使用WM_SIZE就不知道怎么解决性能问题了

**Comment by wangwenx190** [comment]
如果你没遇到性能问题的话，就暂时先这么用吧，我用QWidget测也没遇到性能问题

**Comment by liyangfamily** [comment]
那么至此总结一下：
1、跨屏幕出现绘制异常，可以通过在`nativeEvent`中响应`WM_MOVE`，实现以下代码可以解决。
```
case WM_MOVE:
	{
		if (isScreenChanged()) //用于判断是否跨屏幕，可以解决窗口在移动过程中的性能问题
		{
			updateWindow(msg->hwnd);
		}
	}
	break;
```
```
int m_screenNum = -1; //定义
m_screenNum = QApplication::desktop()->screenNumber(this); //构造函数中获取屏幕序号

bool isScreenChanged()
{
	int curScreenNum = QApplication::desktop()->screenNumber(this);
	if (curScreenNum != m_screenNum)
	{
		m_screenNum = curScreenNum;
		return true;
	}
	else
	{
		return false;
	}
}
```

2、在Areo特效中，左右分屏出现绘制问题，可以通过在`nativeEvent`中响应`WM_SIZE`，实现以下代码可以解决。（🚨该方法无法解决手动改变窗口时的性能问题，会一直触发WM_SIZE）
```
case WM_SIZE:
	{
		updateWindow(msg->hwnd);
	}
	break;
```
❕如果各位有更好的解决办法，欢迎回复。
 如果以上代码有任何问题，也希望大家能够指出，大家一起来完善Qt无边框的解决办法。

**Comment by wangwenx190** [comment]
> 
> 
> 那么至此总结一下：
> 1、跨屏幕出现绘制异常，可以通过在`nativeEvent`中响应`WM_MOVE`，实现以下代码可以解决。
> 
> ```
> case WM_MOVE:
> 	{
> 		if (isScreenChanged()) //用于判断是否跨屏幕，可以解决窗口在移动过程中的性能问题
> 		{
> 			updateWindow(msg->hwnd);
> 		}
> 	}
> 	break;
> ```
> 
> ```
> int m_screenNum = -1; //定义
> m_screenNum = QApplication::desktop()->screenNumber(this); //构造函数中获取屏幕序号
> 
> bool isScreenChanged()
> {
> 	int curScreenNum = QApplication::desktop()->screenNumber(this);
> 	if (curScreenNum != m_screenNum)
> 	{
> 		m_screenNum = curScreenNum;
> 		return true;
> 	}
> 	else
> 	{
> 		return false;
> 	}
> }
> ```
> 
> 2、在Areo特效中，左右分屏出现绘制问题，可以通过在`nativeEvent`中响应`WM_SIZE`，实现以下代码可以解决。（🚨该方法无法解决手动改变窗口时的性能问题，会一直触发WM_SIZE）
> 
> ```
> case WM_SIZE:
> 	{
> 		updateWindow(msg->hwnd);
> 	}
> 	break;
> ```
> 
> ❕如果各位有更好的解决办法，欢迎回复。
> 如果以上代码有任何问题，也希望大家能够指出，大家一起来完善Qt无边框的解决办法。

@liyangfamily 我把第一个问题的解决方案集成到这个repo里了，不过判断当前显示器的方法和你的有所不同，你能测一下最新的代码吗？我这边只有一个显示器，这种问题没法亲自测试。

**Comment by liyangfamily** [comment]
> > 那么至此总结一下：
> > 1、跨屏幕出现绘制异常，可以通过在`nativeEvent`中响应`WM_MOVE`，实现以下代码可以解决。
> > ```
> > case WM_MOVE:
> > 	{
> > 		if (isScreenChanged()) //用于判断是否跨屏幕，可以解决窗口在移动过程中的性能问题
> > 		{
> > 			updateWindow(msg->hwnd);
> > 		}
> > 	}
> > 	break;
> > ```
> > 
> > 
> > ```
> > int m_screenNum = -1; //定义
> > m_screenNum = QApplication::desktop()->screenNumber(this); //构造函数中获取屏幕序号
> > 
> > bool isScreenChanged()
> > {
> > 	int curScreenNum = QApplication::desktop()->screenNumber(this);
> > 	if (curScreenNum != m_screenNum)
> > 	{
> > 		m_screenNum = curScreenNum;
> > 		return true;
> > 	}
> > 	else
> > 	{
> > 		return false;
> > 	}
> > }
> > ```
> > 
> > 
> > 2、在Areo特效中，左右分屏出现绘制问题，可以通过在`nativeEvent`中响应`WM_SIZE`，实现以下代码可以解决。（🚨该方法无法解决手动改变窗口时的性能问题，会一直触发WM_SIZE）
> > ```
> > case WM_SIZE:
> > 	{
> > 		updateWindow(msg->hwnd);
> > 	}
> > 	break;
> > ```
> > 
> > 
> > ❕如果各位有更好的解决办法，欢迎回复。
> > 如果以上代码有任何问题，也希望大家能够指出，大家一起来完善Qt无边框的解决办法。
> 
> @liyangfamily 我把第一个问题的解决方案集成到这个repo里了，不过判断当前显示器的方法和你的有所不同，你能测一下最新的代码吗？我这边只有一个显示器，这种问题没法亲自测试。

@wangwenx190 我在多个显示器上测试没有问题，看最新的代码还解决了左上调整大小右边会闪烁的问题。越来越棒了~

**Comment by liyangfamily** [comment]
@wangwenx190 我在多个显示器上测试没有问题，看最新的代码还解决了左上调整大小右边会闪烁的问题。越来越棒了~

**Comment by wangwenx190** [comment]
> 
> 
> @wangwenx190 我在多个显示器上测试没有问题，看最新的代码还解决了左上调整大小右边会闪烁的问题。越来越棒了~

@liyangfamily  但是现在这个方案还是会有性能问题，如果你把窗口**高速**来回拖动，窗口会在移动的途中发生明显卡顿，慢慢的拖动没事。我估计是在`WM_MOVE`里获取当前显示器的序列号并对比两个`QString`的开销并不小。

**Comment by liyangfamily** [comment]
> @liyangfamily 但是现在这个方案还是会有性能问题，如果你把窗口**高速**来回拖动，窗口会在移动的途中发生明显卡顿，慢慢的拖动没事。我估计是在`WM_MOVE`里获取当前显示器的序列号并对比两个`QString`的开销并不小。

目前在我电脑上，除Quick的程序没测试外，其他两个程序高速拖动都没有出现卡顿，但是CPU占用率最高到了19%。 i5-7300HQ，三个显示器

**Comment by wangwenx190** [comment]
> 
> 
> > @liyangfamily 但是现在这个方案还是会有性能问题，如果你把窗口**高速**来回拖动，窗口会在移动的途中发生明显卡顿，慢慢的拖动没事。我估计是在`WM_MOVE`里获取当前显示器的序列号并对比两个`QString`的开销并不小。
> 
> 目前在我电脑上，除Quick的程序没测试外，其他两个程序高速拖动都没有出现卡顿，但是CPU占用率最高到了19%。 i5-7300HQ，三个显示器

@liyangfamily 我测的是Quick程序，而且界面比较复杂。你测的程序界面复杂吗？而且你多拖一会，别拖一下就停了，来回快速的拖动试试，拖动的距离也长一些试试。

**Comment by wangwenx190** [comment]
这个issue我先关了，有问题可以再重新打开。

**Comment by wangwenx190** [comment]
@JulienMaille  @liyangfamily  Can you test this pr: <https://github.com/wangwenx190/framelesshelper/pull/31> ? I don't know whether this issue exists or not and whether this pr fixed it or not due to I don't have multiple monitors.

**Comment by JulienMaille** [comment]
I have no issues with dual screens (with or withou PR #31)
