### ISSUE TITLE
Unable to drag titlebar on high-resolution display

### ISSUE THREAD

**Issue by zxcv1884** [wangwenx190/framelesshelper#210]
On a screen with a 2K resolution and a 125% scale, I'm unable to drag the titlebar.
After investigating, I found that the issue line in the calculation of the `qtScenePos`:
https://github.com/wangwenx190/framelesshelper/blob/b864e398940cb8fb9d9e51ec3a689aecad6418de/src/core/framelesshelper_win.cpp#L1004-L1005

When I changed `fromNativePixels` to `fromNativeLocalPosition`, the problem was resolved:
https://github.com/wangwenx190/framelesshelper/blob/b864e398940cb8fb9d9e51ec3a689aecad6418de/src/core/utils.cpp#L410

However, I'm not sure if this is the correct solution.

**Comment by zxcv1884** [comment]
Added info:
When using only one 2K screen, this issue does not occur. It only happens when extending the display with a 1080p screen at 100% scale and a 2K screen at 125% scale.

**Comment by wangwenx190** [comment]
Thanks for your investigation! It seems your solution is more sensible indeed! I'll address this issue as soon as possible!

**Comment by wangwenx190** [comment]
Can you check whether commit 5ade3cfb74dbcb8a154cde596e3ab8b066d0526c fixed the issue or not? Thanks!
