### ISSUE TITLE
``nullptr`` initialization on Qt 5.15 seems still unsupported

### ISSUE THREAD

**Issue by yeahitsjan** [wangwenx190/framelesshelper#211]
It seems like initializing QPointer's with ``nullptr`` still does not work on Qt 5.15. [Example](https://github.com/yeahitsjan/pawxel/issues/6).

The point were it steps out is [here](https://github.com/wangwenx190/framelesshelper/blob/main/include/FramelessHelper/Widgets/private/widgetssharedhelper_p.h#L72-L80):
```cpp
#if (QT_VERSION < QT_VERSION_CHECK(5, 15, 0))
    // Due to a Qt bug, we can't initialize the QPointer objects with nullptr.
    // The bug was fixed in Qt 5.15.
    QPointer<QWidget> m_targetWidget;
    QPointer<QScreen> m_screen;
#else
    QPointer<QWidget> m_targetWidget = nullptr;
    QPointer<QScreen> m_screen = nullptr;
#endif
```

I removed the nullptr on my branch: https://github.com/yeahitsjan/framelesshelper/commit/b76bba65f1f0ee65ae42e2993b3d15b9a53168e3 and tested it against Qt 5.15.2 and 5.15.8. Works fine now. Did you get a similar behavior? As I understand, the QPointer should either be initialized with a type like ``QPointer<type>`` or left alone as it get's [constructed](https://doc.qt.io/qt-5/qpointer.html#QPointer) with ``nullptr``.

**Comment by wangwenx190** [comment]
OK. Thanks for testing this ! I'll update the code according to your suggestion, or you could make a pr if you want quicker respond :)

**Comment by yeahitsjan** [comment]
Does this work on Qt 6? I don't have any Qt6 version currently up and running and the question would be if we should increase the version check or completely remove it...

**Comment by wangwenx190** [comment]
I didn't test every Qt6 version, but at least Qt 6.4 & 6.5 works well

**Comment by wangwenx190** [comment]
Maybe just increase to 6.0.0 will be enough
