### ISSUE TITLE
关于编译时的路径

### ISSUE THREAD

**Issue by RoachLin** [wangwenx190/framelesshelper#212]
cmake -DCMAKE_PREFIX_PATH=<YOUR_QT_SDK_DIR_PATH> -DCMAKE_INSTALL_PREFIX=<WHERE_YOU_WANT_TO_INSTALL> -DCMAKE_BUILD_TYPE=Release -GNinja <PATH_TO_THE_REPOSITORY>

<YOUR_QT_SDK_DIR_PATH>
<PATH_TO_THE_REPOSITORY>

请问这两个路径是哪里？可以给一个示例命令吗？

**Comment by wangwenx190** [comment]
cmake -DCMAKE_PREFIX_PATH=**C:/Qt/6.5.0/msvc2019** -DCMAKE_INSTALL_PREFIX=**D:/projects/framelesshelper** -DCMAKE_BUILD_TYPE=Release -GNinja ..

CMAKE_INSTALL_PREFIX 这个是install命令的目的文件夹，你自己决定位置

**Comment by RoachLin** [comment]
上面那条命令解决了，还要在最后加上`-G "Visual Studio 17 2022"`指定c++编译器

还有一个问题，我运行`cmake --build . --config Release --target all --parallel`报错
```
MSBuild version 17.5.1+f6fdcf537 for .NET Framework
MSBUILD : error MSB1009: 项目文件不存在。
开关:all.vcxproj
```
是不是`all.vcxproj`改名为`ALL_BUILD.vcxproj`了？

**Comment by wangwenx190** [comment]
我命令行里有`-GNinja`，这个是指定用Ninja编译，不需要再指定vs了。你是不是没装ninja？用vs编译我没测试过，或许你需要去掉`--config Release`以及`--target all`这两个参数

**Comment by wangwenx190** [comment]
ninja去这里下载：<https://ninja-build.org/>，绿色版，不需要安装，解压出来就行，然后添加到环境变量中。修改环境变量一般都需要重启电脑。

**Comment by wangwenx190** [comment]
ninja会自动调用你的vs去编译

**Comment by RoachLin** [comment]
我换了种方式，我新建了一个工程，把项目源代码放进去，然后`CMakeLists.txt`添加`add_subdirectory(framelesshelper)`，然后`qt creator`编译通过了
我有个问题是我在`main.cpp`里应该包含哪个头文件呢？
是这样吗：`#include <framelesshelper/include/FramelessHelper/Quick/Global>`

**Comment by wangwenx190** [comment]
头文件是这样引用，但具体用哪个文件，看你用到的类或者函数在哪个头文件中。不清楚的话可以参考自带的示例项目。

**Comment by RoachLin** [comment]
可以帮忙看看哪里不对吗？按照你的`README`写的
<img width="960" alt="Snipaste_2023-04-17_15-21-11" src="https://user-images.githubusercontent.com/33180391/232413745-f4d33639-52ac-492d-b3dc-bab46ab0111b.png">

**Comment by wangwenx190** [comment]
你没有按我的示例工程来，头文件引用错了。而且估计你没链接到库。我要看看你CMakeList怎么写的

**Comment by RoachLin** [comment]
```cmake
cmake_minimum_required(VERSION 3.16)

project(untitled111 VERSION 0.1 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD_REQUIRED ON)

include(framelesshelper/cmake/utils.cmake)

find_package(Qt6 6.5 REQUIRED COMPONENTS Quick)

add_subdirectory(framelesshelper)

qt_standard_project_setup(REQUIRES 6.5)

qt_add_executable(appuntitled111
    main.cpp
)

qt_add_qml_module(appuntitled111
    URI untitled111
    VERSION 1.0
    QML_FILES Main.qml
)

set_target_properties(appuntitled111 PROPERTIES
    MACOSX_BUNDLE_GUI_IDENTIFIER my.example.com
    MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
    MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
    MACOSX_BUNDLE TRUE
    WIN32_EXECUTABLE TRUE
)

target_link_libraries(appuntitled111 PRIVATE
    Qt6::Quick
    Qt6::QuickPrivate
    FramelessHelper::Core
    FramelessHelper::Quick
)

install(TARGETS appuntitled111
    BUNDLE DESTINATION .
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR})

``` 

<img width="960" alt="Snipaste_2023-04-17_15-54-59" src="https://user-images.githubusercontent.com/33180391/232421134-dc146bb9-1fe0-4ecc-b632-150305d9b5df.png">

**Comment by wangwenx190** [comment]
include(framelesshelper/cmake/utils.cmake) 这一行不需要；引用路径里去掉 framelesshelper/include/ 这个前缀

**Comment by wangwenx190** [comment]
加上FRAMELESSHELPER_USE_NAMESPACE，在main函数上面

**Comment by RoachLin** [comment]
好的，谢谢，已经成功运行了
我还有个问题是，如何运行`examples`里面的示例项目呢？用`qt creator`直接打开他们的`CMakeLists.txt`好像不行

**Comment by wangwenx190** [comment]
还是打开顶层的CMakeList，只不过要指定一个额外的参数：FRAMELESSHELPER_BUILD_EXAMPLES，把它设置为ON，重新编译就行了

**Comment by RoachLin** [comment]
谢谢你，我先close了，有问题再发issue
