### ISSUE TITLE
cmake 配置项目

### ISSUE THREAD

**Issue by yansong1221** [wangwenx190/framelesshelper#214]
Unknown CMake command "query_qt_paths".

**Comment by yansong1221** [comment]
[main] Configuring project: framelesshelper 
[driver] Removing e:/code/framelesshelper/build/CMakeCache.txt
[driver] Removing e:\code\framelesshelper\build\CMakeFiles
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=F:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md -DCMAKE_PREFIX_PATH=F:/Qt/5.15.2/msvc2019_64 -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -SE:/code/framelesshelper -Be:/code/framelesshelper/build -G "Visual Studio 16 2019" -T host=x64 -A x64
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
[cmake] -- The C compiler identification is MSVC 19.29.30148.0
[cmake] -- The CXX compiler identification is MSVC 19.29.30148.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] --------------------------- Toolchain ----------------------------
[cmake] CMake version: 3.25.0-rc2 (C:/Program Files/CMake/bin/cmake.exe)
[cmake] Host system: Windows-10.0.22621
[cmake] Host processor: AMD64
[cmake] C++ compiler: MSVC (C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe)
[cmake] C++ compiler version: 19.29.30148.0
[cmake] Linker: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/link.exe
[cmake] Make program: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe
[cmake] Generator: Visual Studio 16 2019
[cmake] Build type: 
[cmake] Configuration types: Debug;Release;MinSizeRel;RelWithDebInfo
[cmake] Install prefix: C:/Program Files/FramelessHelper
[cmake] Prefix paths: F:/vcpkg/installed/x64-windows-static-md/debug;F:/vcpkg/installed/x64-windows-static-md;F:/Qt/5.15.2/msvc2019_64
[cmake] Toolchain file: F:/vcpkg/scripts/buildsystems/vcpkg.cmake
[cmake] ------------------------------ Qt -------------------------------
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "E:/code/framelesshelper/build/CMakeFiles/CMakeOutput.log".
[cmake] CMake Error at CMakeLists.txt:163 (query_qt_paths):
[cmake]   Unknown CMake command "query_qt_paths".
[cmake] 
[cmake] 
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=F:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md -DCMAKE_PREFIX_PATH=F:/Qt/5.15.2/msvc2019_64 -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -SE:/code/framelesshelper -Be:/code/framelesshelper/build -G "Visual Studio 16 2019" -T host=x64 -A x64 exited with code: 1

**Comment by wangwenx190** [comment]
把子模块也一起拉下来

**Comment by yansong1221** [comment]
👌
