### ISSUE TITLE
Unknown CMake command "qt_query_qml_module".

### ISSUE THREAD

**Issue by mentalfl0w** [wangwenx190/framelesshelper#215]
`qt_query_qml_module` was introduced in Qt 6.3, So it doesn't work under Qt 6.2, this cmake code needs to be changed.
<img width="664" alt="image" src="https://github.com/wangwenx190/framelesshelper/assets/30333935/3f979521-3aa9-4057-867d-b079ecb58621">

**Comment by wangwenx190** [comment]
Thanks for telling me this! Really sorry for the inconvenience! I'll fix it as soon as possible.
