### ISSUE TITLE
Feature Request: Toggle manually to control dark mode

### ISSUE THREAD

**Issue by mentalfl0w** [wangwenx190/framelesshelper#216]
As title says, sometimes the auto dark mode change is unstable in macOS, which is normal in the quick example but is not in [the other app](https://github.com/zhuzichu520/FluentUI/actions/runs/4994207468/jobs/8944440263?pr=109). 
The FramelessUtils.systemTheme is changed when system dark mode changed, but it didn't trigger the FramlessStandardTitle and blur background to change.
<img width="1161" alt="image" src="https://github.com/wangwenx190/framelesshelper/assets/30333935/6b013d40-ad99-4fd7-917e-fdd9789ae0d7">

**Comment by wangwenx190** [comment]
标题栏和窗口背景没有及时刷新是吗？Widget例子也有这个问题吗

**Comment by wangwenx190** [comment]
我在Windows上用6.5测了下，深色浅色主题切换是正常的

**Comment by wangwenx190** [comment]
你用6.5测一下试试呢

**Comment by mentalfl0w** [comment]
> 你用6.5测一下试试呢

我之后测试一下

**Comment by wangwenx190** [comment]
总之你是希望加一个可以手动控制主题的开关是吧？可以的

**Comment by mentalfl0w** [comment]
> 总之你是希望加一个可以手动控制主题的开关是吧？可以的

哈哈哈是的，谢谢😊，自动控制好像在我这边有点毛病，所以如果有个手动控制就会方便调整一点

**Comment by wangwenx190** [comment]
试试我新加的接口呢，`FramelessManager::setOverrideTheme()`。设置为`SystemTheme::Unknown`可以重新换回自动模式。

**Comment by wangwenx190** [comment]
代码我又重构了下，拉取最新代码试试效果呢，macOS上接口运行正常吗

**Comment by wangwenx190** [comment]
我检查了代码，模糊背景应该能正常切换了

**Comment by mentalfl0w** [comment]
> 代码我又重构了下，拉取最新代码试试效果呢，macOS上接口运行正常吗

是的，运行已正常，效果很好，谢谢☺️
<img width="1064" alt="image" src="https://github.com/wangwenx190/framelesshelper/assets/30333935/c46b258f-d376-4529-b3ff-eb26e1d4cc91">
<img width="1069" alt="image" src="https://github.com/wangwenx190/framelesshelper/assets/30333935/d168170f-7c10-4ee7-94e4-fcb1e72dedc5">
