### ISSUE TITLE
Error: Unknown method parameter type: QuickGlobal::SystemButtonType

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#223]
FramelessHelper.setSystemButton(titleBar.minButton, FramelessHelperConstants.Minimize)
FramelessHelper.setSystemButton(titleBar.maxButton, FramelessHelperConstants.Maximize)
FramelessHelper.setSystemButton(titleBar.closeButton, FramelessHelperConstants.Close)

使用这个会报错: Unknown method parameter type: QuickGlobal::SystemButtonType

**Comment by wangwenx190** [comment]
main函数里要注册FramelessHelper的类型

**Comment by wangwenx190** [comment]
你Qt版本是5.14？

**Comment by ohPigFly** [comment]
是的

**Comment by wangwenx190** [comment]
FramelessHelper的Quick部分对老版本的Qt兼容性有点问题，你那边能升级到5.15吗

**Comment by ohPigFly** [comment]
后续应该可以升，暂时还没升。其实我只想实现个支持window11的贴边停靠的功能

**Comment by ohPigFly** [comment]
我找个时间试一下迁移到5.15版本，再试一下，看能不能通过。

**Comment by mentalfl0w** [comment]
#240 新的PR应该已经解决了这个问题。

**Comment by ohPigFly** [comment]
鉴于不方便迁移版本，我参考去实现一个较为简单适配windows的窗口，但是遇到一个问题没方向，想请教一下大神，就从1920*1080移动去2560*1080的屏幕，窗口都会自动变大了10几个像素，顶栏会下移大概一个顶栏高度了，需要鼠标下移一点才可以拉动，但是实际看到的窗体大小是没变化内容也是没有变化，需要重新拉动一下窗体，才会变成正常。
