### ISSUE TITLE
macOS Qt 6.2.4编译example后打开状态栏无原生按钮

### ISSUE THREAD

**Issue by mentalfl0w** [wangwenx190/framelesshelper#224]
只有把[这里](https://github.com/wangwenx190/framelesshelper/blob/e67a91d668cd296980115e8d076582503e930688/src/core/framelesshelper_qt.cpp#L106)设置成true才可以和README的截图一致。
奇怪的是，似乎Qt 6.4.3和Qt 6.5.0编译出来的就是正常的。
<img width="836" alt="image" src="https://github.com/wangwenx190/framelesshelper/assets/30333935/5545c802-0aed-4c60-8bfd-f0a30a7d64e0">

**Comment by wangwenx190** [comment]
macOS版本的代码，并没有像Windows平台那样针对多个Qt版本单独适配（除了判断系统版本的部分），可能是Qt自身修改了什么地方？macOS平台的开发我也不是特别专业，没法很深入研究

**Comment by wangwenx190** [comment]
此issue需等Qt5相关情况确认后才能关闭

**Comment by mentalfl0w** [comment]
> 此issue需等Qt5相关情况确认后才能关闭

Qt 5.15.2测试也存在此问题，估计Qt 6.2.4以下都存在这个问题。我重新发起一个PR修改一下判断条件。
