### ISSUE TITLE
qtquick项目使用问题

### ISSUE THREAD

**Issue by N4v1zzZ** [wangwenx190/framelesshelper#230]
已按照使用说明完成了build和install，新建了Qt Quick项目尝试使用，在qml import始终有问题，求指教。

CMakeList like this 

![image](https://github.com/wangwenx190/framelesshelper/assets/9866711/242fa25a-5a66-47a2-bf47-7b7e580e23b8)

main.cpp like this 

![image](https://github.com/wangwenx190/framelesshelper/assets/9866711/ac8e171e-d24e-49da-b415-0f4a2ac2a01b)

main.qml like this 

![image](https://github.com/wangwenx190/framelesshelper/assets/9866711/8cc080e5-fdc3-496b-bb70-7ef17ce98976)

**Comment by N4v1zzZ** [comment]
Qt版本6.5

**Comment by wangwenx190** [comment]
这个警告可以不用管，不过我还是更新一下自述文件，讲一下怎么解决这个问题

**Comment by wangwenx190** [comment]
你的qml文件也不对，你是照搬了我自述文件里的代码，肯定不行的，要替换成你自己的控件

**Comment by N4v1zzZ** [comment]
> 你的qml文件也不对，你是照搬了我自述文件里的代码，肯定不行的，要替换成你自己的控件

额 qml的内容我稍后改一下，import那里编译不过我就没往下写了 - -

**Comment by wangwenx190** [comment]
自述文件已经更新了，你可以参考下

**Comment by wangwenx190** [comment]
import那里不影响编译的，因为我这个是纯C++的插件，不需要外置的qml文件，只是不专门设置一下会没有语法高亮。

**Comment by N4v1zzZ** [comment]
改了下cmakelist 
![image](https://github.com/wangwenx190/framelesshelper/assets/9866711/5f06431e-467e-4690-8308-25d4b472638b)
编译出问题
![image](https://github.com/wangwenx190/framelesshelper/assets/9866711/453a3dc9-2638-4788-883f-253d186e4fd2)
main.qml like this 
![image](https://github.com/wangwenx190/framelesshelper/assets/9866711/847d3775-c80b-4ec4-b7f4-3752a4883059)

**Comment by N4v1zzZ** [comment]
install完的目录里没有.lib后缀的文件
![image](https://github.com/wangwenx190/framelesshelper/assets/9866711/99382b5c-14c5-4997-bb68-e0b6642a8aea)

**Comment by wangwenx190** [comment]
这一看就是mingw编译的，你编译器不对。编译时要指定msvc

**Comment by wangwenx190** [comment]
不对，我搞错了。看来你确实要用mingw，那我得改一下cmake脚本

**Comment by N4v1zzZ** [comment]
嗯 是用mingw编译的 装qt 6.5只选了mingw - -

**Comment by wangwenx190** [comment]
脚本更新了，需要拉取最新代码后重新编译和install

**Comment by N4v1zzZ** [comment]
好的 我去试试

**Comment by wangwenx190** [comment]
脚本更新了，需要拉取最新代码后重新编译和install

**Comment by N4v1zzZ** [comment]
OK了 可算是运行起来了 - -
