### ISSUE TITLE
module "QtQml" version 1.0 is not installed

### ISSUE THREAD

**Issue by satchelwu** [wangwenx190/framelesshelper#233]
编译完成，启动程序FramelessHelperDemo-Quick出现这个错误：
module "QtQml" version 1.0 is not installed
Qt version: 6.4.3

`[2023/06/07 14:55:38.937] <WARNING> QQmlApplicationEngine failed to load component`
`[2023/06/07 14:55:38.937] <WARNING> qrc:/qml/HomePage.qml:28:5: Type Window unavailable`
`[2023/06/07 14:55:38.937] <WARNING> qrc:/qml/Window.qml:27:1: module "QtQml" version 1.0 is not installed`
`[2023/06/07 14:55:38.939] <CRITICAL> The QML engine failed to create component: QUrl("qrc:/qml/HomePage.qml")`

请问可能是什么原因呢？

**Comment by wangwenx190** [comment]
QtQml这个模块找不到，大概率是你环境没配置好，这个正常QtQuick工程都不会找不到的

**Comment by CarlosSimon02** [comment]
@satchelwu did you fixed the problem?

**Comment by wangwenx190** [comment]
@CarlosSimon02 Please try latest code. This issue should be fixed now.
