### ISSUE TITLE
macOS下创建多窗口在析构时出现错误

### ISSUE THREAD

**Issue by mentalfl0w** [wangwenx190/framelesshelper#235]
如图所示：
<img width="735" alt="image" src="https://github.com/wangwenx190/framelesshelper/assets/30333935/b33ae93a-4f2a-4d32-9751-bd9fdc8e9e8f">
我在macOS 13.5系统下，首先打开一个窗口，然后再打开一个子窗口，关闭此子窗口时出现此报错，进入调试模式后发现是此函数中的nswindow访问的地址已经被释放了。

**Comment by wangwenx190** [comment]
restoreState这个东西其实没必要调用

**Comment by wangwenx190** [comment]
我之前就想过这个东西可能会崩溃，因为调用的时机太晚了

**Comment by wangwenx190** [comment]
没问题的话就close吧

**Comment by mentalfl0w** [comment]
好的，谢谢😊
