### ISSUE TITLE
kubuntu23.04 ,qt5.5.1 编译失败

### ISSUE THREAD

**Issue by zhoucheng2021** [wangwenx190/framelesshelper#242]
platformsupport_linux.cpp:299:10: error: ambiguating new declaration of ‘QString gtkSettings(const char*)’
platformsupport_linux.cpp:493: error: ‘g_object_get’ was not declared in this scope; did you mean ‘g_object_unref’?

**Comment by zhoucheng2021** [comment]
是qt6.5.1

**Comment by wangwenx190** [comment]
需要安装libxcb-dev和libgtk-3-dev

**Comment by zhoucheng2021** [comment]
谢谢
