### ISSUE TITLE
QT5.15 msvc2019编译quick example问题

### ISSUE THREAD

**Issue by ld886312** [wangwenx190/framelesshelper#249]
我在使用qt5.15.2和msvc2019编译examples/quick/quick.pro 文件，出现
**quickstandardtitlebar.obj:-1: error: LNK2019: 无法解析的外部符号 "public: __cdecl QQuickRow::QQuickRow(class QQuickItem *)" (??0QQuickRow@@QEAA@PEAVQQuickItem@@@Z)，函数 "private: void __cdecl wangwenx190::FramelessHelper::QuickStandardTitleBar::initialize(void)" (?initialize@QuickStandardTitleBar@FramelessHelper@wangwenx190@@AEAAXXZ) 中引用了该符号**
我注释掉quickstandardtitlebar.cpp里第520行"m_systemButtonsRow = new QQuickRow(this);"编译通过，请问大佬这个是什么原因呀，需要修改QQuickRow类所在的库吗？
![2023-07-21_003559](https://github.com/wangwenx190/framelesshelper/assets/107361030/d4601638-0fbd-4140-af61-1dd4fa91eefe)

**Comment by wangwenx190** [comment]
Qt5没法编quick实例，因为我用到的一些类只有Qt6才导出
