### ISSUE TITLE
请问如何才能去掉白边？

### ISSUE THREAD

**Issue by leoxiaofei** [wangwenx190/framelesshelper#25]
系统：Windows10 2004
Qt：5.9.9
编译器：msvc2015

感谢作者贡献。
我测试时，窗口处于激活状态时，左下右三边一个像素的白边。请问如何才能去掉白边？

测试代码如下：
```C++
QWidget* p = new QWidget;
WinNativeEventFilter::addFramelessWindow(p);
p->setStyleSheet("border: 1px solid #444851;");
p->show();
```
![Screenshot 2020-10-13 111437](https://user-images.githubusercontent.com/11505055/95811467-f2a90600-0d45-11eb-9ab2-0424b83fdd9d.png)

**Comment by wangwenx190** [comment]
最新的代码应该不会有这个问题，你拉一下最新的代码再试试。如果你曾经用过这个repo，代码更新后还需要rebuild。如果还是有白边，请检查是不是布局导致的。

**Comment by wangwenx190** [comment]
这个repo自带的例子，能复现这个问题吗？我自己测试的时候，没发现有这个问题。

**Comment by wangwenx190** [comment]
现在的例子大概会在窗口顶部绘制一条边框线，比较违和，过会我会更新例子，把边框线去掉。但无论如何，白边是不会有的。

**Comment by wangwenx190** [comment]
这个白边也不是bug，而是我专门为win10准备的某个特性导致的，但那个特性体验下来效果不太好，所以最新的代码里，我关闭了这个特性。

**Comment by leoxiaofei** [comment]
> 
> 
> 最新的代码应该不会有这个问题，你拉一下最新的代码再试试。如果你曾经用过这个repo，代码更新后还需要rebuild。如果还是有白边，请检查是不是布局导致的。

谢谢，我昨天早上拉的代码出现的问题，现在用你最新代码已经好了。
我也有注意到：昨天的代码，resize区域（左下右）是在窗口外，现在的代码(8bc4c0155ab2149f46e5aecfd5036257b27222d2)是在窗口内。

**Comment by wangwenx190** [comment]
>
> 我也有注意到：昨天的代码，resize区域（左下右）是在窗口外，现在的代码([8bc4c01](https://github.com/wangwenx190/framelesshelper/commit/8bc4c0155ab2149f46e5aecfd5036257b27222d2))是在窗口内。
>
是的，就是这个特性，原来我是把左右下三边的resize的区域放在窗口外边的，但是导致了很多问题，所以最新的代码我就关了这个特性

**Comment by wangwenx190** [comment]
这个特性是用一个函数控制的，代码内部并没有大的修改

**Comment by wangwenx190** [comment]
你可以去看下`shouldHaveWindowFrame`这个函数

**Comment by leoxiaofei** [comment]
> 
> 
> > 我也有注意到：昨天的代码，resize区域（左下右）是在窗口外，现在的代码([8bc4c01](https://github.com/wangwenx190/framelesshelper/commit/8bc4c0155ab2149f46e5aecfd5036257b27222d2))是在窗口内。
> 
> 是的，就是这个特性，原来我是把左右下三边的resize的区域放在窗口外边的，但是导致了很多问题，所以最新的代码我就关了这个特性

这个特性感觉好拉风啊，感觉和原生窗口行为一致。（目前我也只发现那个白边问题：实际大小和Qt绘制大小有点不一致）

**Comment by wangwenx190** [comment]
是拉风，就是小问题不少，大问题是没有的

**Comment by wangwenx190** [comment]
而且这个特性只支持win10

**Comment by leoxiaofei** [comment]
> 
> 
> 你可以去看下`shouldHaveWindowFrame`这个函数

我觉得应该有这个frame，但是我试着调了一下，实在没找到到底如何修改Qt的窗口的绘制尺寸（或者DWM绘制尺寸）

**Comment by wangwenx190** [comment]
这个白边是窗口边框的一部分，是去不掉的，跟qt没关系

**Comment by wangwenx190** [comment]
你可以看看文件管理器，在浅色主题下也有白边

**Comment by wangwenx190** [comment]
没有API能在这个白边上绘图，除非彻底隐藏窗口边框

**Comment by leoxiaofei** [comment]
> 
> 
> 你可以看看文件管理器，在浅色主题下也有白边

确实如你所说，浅色主题下，都有（包括edge和firefox）

**Comment by wangwenx190** [comment]
> > 你可以看看文件管理器，在浅色主题下也有白边
> 
> 确实如你所说，浅色主题下，都有（包括edge和firefox）

这个白边就是窗口边框的一部分，没有任何程序能在这个地方绘图，所以跟qt没关系

**Comment by wangwenx190** [comment]
这个issue我先关了，有问题可以在这里继续讨论。
