### ISSUE TITLE
请问qml里窗口左右和底部的黑色border怎么去掉或隐藏？

### ISSUE THREAD

**Issue by YUPANZHAO** [wangwenx190/framelesshelper#256]
``` qml
Window {
    id: mainWin
    visible: false
    width: 800
    height: 500

    Item {
        id: titleBar
        width: parent.width
        height: 36
        Rectangle {
            color: "red"
            anchors.fill: parent
        }
    }

    FramelessHelper.onReady: {
        FramelessHelper.titleBarItem = titleBar
        FramelessHelper.moveWindowToDesktopCenter()
        mainWin.visible = true
    }
}
```

![_7B934C611B-6A4C-4aa6-98D9-BE161FFFBAFC_7D.png](https://img1.imgtp.com/2023/08/06/070gVhTB.png)

我想过把整个Window都设为透明的，然后内部自定义一个页面。我设置Window的`color: "transparent"`，但好像并不起作用。
而设置`opacity: 0`的话，内部的页面也会随之变透明。

我还尝试了将两个Window重叠在一起，底层的Window装配FramelessHelper，并设置为透明，而上层的Window设置`flags: Qt.FramelessWindowHint`，但这个方案存在的问题是鼠标事件貌似无法穿透Window，去拖动底层的标题栏区域，使用`MouseArea`也无济于事。

我应该怎么做才能隐藏掉Window的边框呢？

**Comment by wangwenx190** [comment]
你只是要隐藏窗口外边那个边框吗？这个可以设置一个选项来实现，不要搞透明窗口什么，边框不是Qt渲染的，你弄成透明也没用。

https://github.com/wangwenx190/framelesshelper/blob/8d3ef93885dd6df704c2e2bf1c279ad254de7ff1/include/FramelessHelper/Core/framelesshelpercore_global.h#L285C8-L285C8

用`FramelessConfig`这个类来设置各种选项

**Comment by YUPANZHAO** [comment]
赵煜潘已收到你的邮件:)

**Comment by YUPANZHAO** [comment]
我在main.cpp中加入这行代码，效果是我希望看到的了。
``` cpp
FramelessConfig::instance()->set(Global::Option::ForceHideWindowFrameBorder);
```
还有个问题是FramelessConfig是没有注入到QML里吗，因为我在main.qml里调用如下代码，报错是`ReferenceError: FramelessConfig is not defined`，而且我不清楚后面的参数中应该以什么为前缀。

``` qml
FramelessConfig.set(FramelessConfig.ForceHideWindowFrameBorder)
```

**Comment by wangwenx190** [comment]
这个类暂时是私有的，所以没有注册到QML里。以后如果转成公开的接口了，可以注册到QML里。现在暂时只能从C++层面进行操作。

**Comment by YUPANZHAO** [comment]
好的，感谢大佬
