### ISSUE TITLE
5.15.2编译报QSurface::Direct3DSurface未定义

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#258]
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/7bcc46d8-97df-4e3d-8a5a-7467ad226465)

**Comment by ohPigFly** [comment]
我暂时屏蔽了，但是不知道会不会导致其他问题，可编译通过使用。

**Comment by wangwenx190** [comment]
OK，我马上修复，不好意思了。屏蔽没问题的。

**Comment by wangwenx190** [comment]
最新代码应该没问题了

**Comment by ohPigFly** [comment]
请问，顶栏支持变更自定义的颜色么？
