### ISSUE TITLE
请问，顶栏有开放接口变更自定义的颜色么？

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#259]

**Comment by wangwenx190** [comment]
你是指顶部的边框线还是标题栏？

设置边框线的颜色：
https://github.com/wangwenx190/framelesshelper/blob/9265735ac72dfb769faaa644f9c27fafd39ad3e1/include/FramelessHelper/Widgets/framelesswidgetshelper.h#L60

设置标题栏颜色：
https://github.com/wangwenx190/framelesshelper/blob/9265735ac72dfb769faaa644f9c27fafd39ad3e1/include/FramelessHelper/Widgets/standardtitlebar.h#L74

**Comment by wangwenx190** [comment]
QtQuick接口也是一样的

**Comment by ohPigFly** [comment]
感谢！
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/cddad962-921d-42e5-8212-2be03dee36ef)
我的理解这个配置是关闭窗框圆角，但是我设置了，没变化，我是不是理解错了？

**Comment by wangwenx190** [comment]
这个选项暂时没有实现功能。如果你是Win11平台，可以调用下面这个函数来手动设置圆角直角：

https://github.com/wangwenx190/framelesshelper/blob/9265735ac72dfb769faaa644f9c27fafd39ad3e1/include/FramelessHelper/Core/utils.h#L137C45-L137C45

这个函数对win10及以下的系统无效

**Comment by ohPigFly** [comment]
感谢！有效，我的是windows11的，我在framelesshelper_win.cpp的naviveEventFilter的WM_NCCALCSIZE里调用，但是不知道会不会引起其他问题。
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/7cfd79fe-06aa-44c4-be7e-8e20e5d16c98)
