### ISSUE TITLE
QMenuBar位置问题

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#260]
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/db6bf5a8-8f6f-4eed-a5dd-f55361a50a77)
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/18f4fb4d-fa5d-40f4-acc1-4b4015bba6cb)

QMenuBar的位置只能放在顶栏里面么？如果不设进去，就显示不了，不能按照原风格，排在标题栏的下面么？

**Comment by wangwenx190** [comment]
可以的，但有些麻烦。不能用QMainWindow了，要用QWidget，然后把QMenuBar通过布局的方式放到你自定义标题栏的下方。

**Comment by ohPigFly** [comment]
不过这个暂时没用到，我只是好奇，为何QtDesigner上面看到有，但是如果我不设置到标题栏，就显不出来。
