### ISSUE TITLE
utils.cmake的作用

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#263]
请问，例程里面的CMakeLists.txt是有include(../../cmake/utils.cmake)，这个主要作用是什么？我自己的工程只是加入了相应的库来直接使用，没有去包含这个utils.cmake，会不会出现什么问题。

**Comment by wangwenx190** [comment]
我自己的项目用到一些我自己写的cmake函数，都在那个文件里，多个项目共享。你自己的项目不需要包含这个
