### ISSUE TITLE
顶栏图标隐藏，可以调整标题边距么？

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#264]
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/7beae10f-46a9-482b-8f97-7122154a383a)
请问这种情况，有没开放接口调整标题的左边距？
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/81759b20-7366-4a8f-99ec-f1fd6fb3f856)
我尝试用这种来，可以变小，但是1的是最小了，再往下，就出现崩溃的了。

**Comment by wangwenx190** [comment]
按理说你隐藏icon之后，文本就会左对齐到边界的，不需要再手动调整icon尺寸。我看看代码是不是有bug

**Comment by wangwenx190** [comment]
是一个小bug，已经解决。请拉取最新代码试试

**Comment by ohPigFly** [comment]
验证可以了，就是开启那里必须保证要放在设置图标之后，不然就会崩溃。
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/59444cbe-d918-49a3-9cab-a07e9423c0e5)
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/15bc321e-f54e-4613-8ef7-9e80010feffc)

**Comment by ohPigFly** [comment]
感谢，学到了！以前没用到，的确对Debug阶段很有好处。
