### ISSUE TITLE
Dialog双击标题栏，出现白边

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#266]
Qt版本5.15.2，Demo-dialog双击标题栏，自动置屏幕左上角，会出现如下图白边。
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/130251d7-06f2-458a-bd6f-9586e57b0fb5)

更改为黑色，就会很明显。
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/6faff353-afd9-4ca0-9b5a-5cf7ead88d08)

**Comment by ohPigFly** [comment]
在屏幕左上角时候，再双击标题栏，就会如下图那样。按着标题栏拖动一下，就会变回正常。
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/5c7173ca-fae6-4c2b-98a3-5e0fecccbc8c)

**Comment by wangwenx190** [comment]
OK，知道问题在哪了，我马上修复
