### ISSUE TITLE
dialog设置最小大小

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#267]
我更改了demo-dialog，想调试一下那个设置最小大小的，里面只放个标题栏和一个空白的QWidget，开头设置了最小大小，但是没有效果。
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/bd750c96-5425-4da0-a35f-d686bcf3e2c5)
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/8951435d-cefb-4978-814c-9e93fbdd46d1)

**Comment by wangwenx190** [comment]
dialog不支持resize，所以你设置minimumSize干嘛？你应该设置fixedSize。而且要在FramelessHelper给你ready信号之后做

**Comment by ohPigFly** [comment]
我基于这个封个QMessageBox出来，我想根据内容显示来变大，最小不小于某个大小，所以就使用了minimumSize了
