### ISSUE TITLE
最小化按钮触发后，按钮样式未复位

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#268]
在按下最小化按钮后，再从任务栏按下软件图标显示，就能看到最小化按钮没恢复常规状态。
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/b732c50d-2511-4be4-a862-99231a2aa40f)

**Comment by ohPigFly** [comment]
把鼠标悬浮在随便一个按钮上，然后移除窗口外，也会不恢复，移入窗内就可以。

**Comment by wangwenx190** [comment]
这个是snap layout代码导致的，这周一直在重构，预计这几天彻底完善

**Comment by wangwenx190** [comment]
重构已经完成，麻烦看看最新代码是否还存在这个问题

**Comment by ohPigFly** [comment]
可以了
