### ISSUE TITLE
方便完善win11以上可控制圆角的功能么？

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#274]
因为我增加了在farmelesshelper_win，这文件更改频率相对较高，就冲突。

**Comment by wangwenx190** [comment]
行，我得单独加一个OPtion，毕竟win11默认圆角，我要加一个方角的选项

**Comment by wangwenx190** [comment]
最新代码加了一个新的Option，WindowUseSquareCorners，可以在win11关闭圆角
