### ISSUE TITLE
cmake failed on debian testing

### ISSUE THREAD

**Issue by wuruxu** [wangwenx190/framelesshelper#277]
`
root@ubuntu: /tmp/framelesshelper/build$ cmake -DCMAKE_BUILD_TYPE=Release  -DCMAKE_CXX_COMPILER=g++ ..
CMake Error at CMakeLists.txt:84 (include):
  include could not find requested file:

    cmake/utils.cmake

CMake Error at CMakeLists.txt:106 (setup_project):
  Unknown CMake command "setup_project".

-- Configuring incomplete, errors occurred!`

**Comment by SineStriker** [comment]
git clone的时候没拉submodule，检查下有没有加--recursive选项。
