### ISSUE TITLE
[macOS] startSystemResize() is not supported on macOS

### ISSUE THREAD

**Issue by luozikuan** [wangwenx190/framelesshelper#28]
Qt 文档说 `Returns true if the operation was supported by the system.`
但是 mac 系统上 startSystemResize 返回 false

**Comment by wangwenx190** [comment]
macOS竟然不支持这个函数吗？那不好办了啊，这种情况下你可以参考<https://github.com/Bringer-of-Light/Qt-Nice-Frameless-Window>这个仓库。

**Comment by luozikuan** [comment]
它这个库我看了，不支持在 widget 里放 QTabWidget，放了 QTabWidget 之后标题栏就出来了

**Comment by wangwenx190** [comment]
我本身没有mac，而且我也没有在mac上进行开发的经验，如果Qt不能提供相关的功能，那我确实帮不了你了，不好意思啊

**Comment by wangwenx190** [comment]
2.0版本修复了这个问题，先close了
