### ISSUE TITLE
FRAMELESSHELPER_VERSION等宏未定义

### ISSUE THREAD

**Issue by czyt1988** [wangwenx190/framelesshelper#283]
我想在一个库里引入[framelesshelper](https://github.com/wangwenx190/framelesshelper)，目前我在使用qmake（暂时还没用cmake），在pro文件中include qmake文件夹下的`qmake/core.pri` `qmake/core.pri`后，报了如下错误:
```shell
framelesshelper\src\core\framelesshelpercore_global.cpp:185: error: C2065: “FRAMELESSHELPER_VERSION”: 未声明的标识符
framelesshelper\src\core\framelesshelpercore_global.cpp:187: error: C2065: “FRAMELESSHELPER_COMMIT_HASH_STR”: 未声明的标识符
framelesshelper\src\core\framelesshelpercore_global.cpp:189: error: C2065: “FRAMELESSHELPER_COMMIT_AUTHOR_STR”: 未声明的标识符
...
```
![错误截图](https://github.com/wangwenx190/framelesshelper/assets/7260393/3f6f059c-5d66-43a2-9527-294556ece407)

我看你的版本信息是位于`framelesshelper\qmake\inc\core\framelesshelper.version`，应该是cmake生成的，但貌似缺少一些定义

请问这如何解决

**Comment by wangwenx190** [comment]
我同步一下文件内容就可以了

**Comment by wangwenx190** [comment]
最新代码应该没这个问题了。麻烦验证一下

**Comment by razaqq** [comment]
still has it
