### ISSUE TITLE
mocs_compilation.cpp.obj:-1: error: LNK2005: "public: bool __thiscall QByteArray::isNull(void)const " (?isNull@QByteArray@@QBE_NXZ) 已经在 Qt6Core.lib(removed_api.cpp.obj) 中定义

### ISSUE THREAD

**Issue by fgfxf** [wangwenx190/framelesshelper#285]
mocs_compilation.cpp.obj:-1: error: LNK2005: "public: bool __thiscall QByteArray::isNull(void)const " (?isNull@QByteArray@@QBE_NXZ) 已经在 Qt6Core.lib(removed_api.cpp.obj) 中定义

**Comment by wangwenx190** [comment]
是否是静态编译的Qt？

**Comment by fgfxf** [comment]
对，vs2022静态编译的QT6.5.2

**Comment by wangwenx190** [comment]
你是直接用CMake编译的还是用那个configure.bat编译的？

**Comment by fgfxf** [comment]
QT打开cmakelist编译，出现的。
msvc.bat不管用，就算配置了vs2022的环境变量prompt也不行。

**Comment by fgfxf** [comment]
借助configure.bat

**Comment by wangwenx190** [comment]
编译Qt时，加一个参数重新编译：`-disable-deprecated-up-to 0x070000`，看看能不能解决

**Comment by wangwenx190** [comment]
最新代码应该是没这个问题了，有时间请验证一下
