### ISSUE TITLE
[Windows] Frameless windows are flickering when resizing

### ISSUE THREAD

**Issue by wangwenx190** [wangwenx190/framelesshelper#29]
Workaround:
https://github.com/wangwenx190/framelesshelper/blob/72db8e7043c3230dfa8dbb485cdc865b79f344aa/winnativeeventfilter.cpp#L1625
Make the client area a little smaller than it should be.

In this way, the flickering problem is gone indeed but it also causes many issues when we want to draw something manually by QPainter. Qt Quick is affected as well.

Another finding: most frameless windows have this issue. For example, Google Chrome, Mozilla Firefox, Microsoft Office and etc.

**Comment by wangwenx190** [comment]
Find one solution when you preserve the window frame: return `WVR_REDRAW` when `wParam` is `TRUE`.

**Comment by razaqq** [comment]
yeah this is still persistent in the latest version for me
the `clientRect->top -= 1; ` did fix it, the second solution did not (maybe i used it wrong)

**Comment by JulienMaille** [comment]
Are there any drawbacks using this _trick_?

**Comment by wangwenx190** [comment]
@razaqq It seems the little trick we use is making Qt calculate the wrong window size. It thinks the window is 1px larger than the real window. So we may get some warnings due to this kind of mismatch.

But I can't remove that block of code since it's fixing a multimonitor bug. You says the window size will increase 1px, then what about we just decrease 1px everytime when you drag the window to another screen? Will this solution help?

**Comment by wangwenx190** [comment]
I'm trying to find out how to hack into Qt to modify the size or geometry of the window/widget it stores internally.

**Comment by camgaertner** [comment]
Hi, this project is working great for me except for this issue. I noticed most other apps don't have this problem recently. As you noted it's only from the top or left resizing that causes a minor issue. Have you put any thought into how to solve it? My use case is Qt-Quick.

>I'm trying to find out how to hack into Qt to modify the size or geometry of the window/widget it stores internally.

Looking at QWindow, the geometry seems to be stored in QPlatformWindow::d->rect. But I don't think there's a way to modify this besides calling setGeometry.

Thanks again - this project is very useful nonetheless.

**Comment by wangwenx190** [comment]
@camgaertner  This issue exists commonly on any Win32 applications, it doesn't matter whether you are using Qt Widgets or Qt Quick. The solution for it is also the same for Qt Widgets and Qt Quick. You said this issue is gone for most applications **RECENTLY**, do you know their Qt version? If it's **>= 6.2.2**, then it may be fixed by my own contribution to Qt. I submited a patch to upstream Qt to fix the jitter issue during window resize, but that fix only works if the window still has some non-client area. For this repo, we have get rid of the whole non-client area, so the fix is not suitable for us. Actually, it's a very hard to solve problem when there's no non-client area. The `clientRect->top -= 1;` trick works due to it can give us some non-client area as well. But if the Qt version is not greater or equal to 6.2.2, then I don't know what happened, and I'm also very eager to know how do the other application solve this issue. But as for Qt Quick applications, there are many improvements to the rendering mechanism recently, maybe they also help to reduce the flicker.

**Comment by wangwenx190** [comment]
if you are not sure about it, you can give me some links to the applications, I'll try to dig into it to see what happened.

**Comment by camgaertner** [comment]
@wangwenx190 Thanks for your response.

>The solution for it is also the same for Qt Widgets and Qt Quick. You said this issue is gone for most applications RECENTLY, do you know their Qt version?

Mostly, I was looking at the apps you mentioned - Chrome and Firefox don't seem to have this problem on my machine. Electron apps as well (Spotify / Discord). Perhaps it's possible to look at how chromium is handling it, since they're open source

**Comment by wangwenx190** [comment]
It would be great if you can provide their exact version number, your os version and optionally, your graphics card model, because they are all very important to locate the issue. I will surely dig into their source code to see how they improve the situation, if I know from which version, the diff is also very important.

**Comment by camgaertner** [comment]
Sure, I have..

OS:
`Microsoft Windows 10 Pro`
`Version	10.0.19042 Build 19042`

Chrome:
`Version 98.0.4758.82 (Official Build) (64-bit)`

Firefox:
`96.0.3 (64-bit)`

Graphics Card:
`NVIDIA GeForce GTX 1080 Ti`

By the way, we would be happy to offer a $200 (USD) bounty for this issue if a proper fix can be done. Thanks!

**Comment by JulienMaille** [comment]
I just tried on Chrome `98.0.4758.81` / Win11 `build 22543` and the right side will flicker when resizing from both left and right.
Same with Edge `97.0.1072.76`

**Comment by wangwenx190** [comment]
@camgaertner @JulienMaille Thanks for your information!

Currently I’m on holiday so I cannot really do something about it, but I have some guesses about the solution. I also have a perfect solution which won’t flicker at all in any situation, but that solution is only suitable for win 10 and greater, and for the Qt framework it requires some little modification to the QPA, so I didn’t merge the code into this repo. But I’m working on a patch to bring it to Qt itself, and the Qt engineers seem to welcome it if it doesn’t break anything. If it has any constructive progress, I can inform you. If you don’t care about running on win 7, you can try my new solution once it’s ready. I received several suggestions from Qt engineers so I still need some time to modify the patch.

**Comment by camgaertner** [comment]
@wangwenx190 Ok, sounds good. We don't care about Windows prior to version 10, so your solution should work for us if it can be merged into Qt.

Have a nice holiday, 新年快乐!

**Comment by wangwenx190** [comment]
I just tested Microsoft Edge 98.0.1108.43 and Mozilla Firefox 96.0.3 on Windows 11 (version 10.0.22000.469), the flicker still exists and it has no difference compared with before.

> by flickering what do you guys mean exactly?
>> the full windows flickering, like this? https://drive.google.com/file/d/1nBdo0L8XYLYcFDeqVmh0YQnlQr0o2f6J/view
>> or just the right side not refreshing fast enough so you see everything drawn in the wrong position for a few millisec?

@JulienMaille  I've never seen the first kind of flickering before, so the flickering issue **I** am talking about refers to the second one, though I'm not sure @camgaertner is refering to which one.

**Comment by camgaertner** [comment]
Maybe things have changed in Windows 11. I will setup a VM and test some of these apps soon. I can provide a video of the flickering I'm referring to soon also.

**Comment by camgaertner** [comment]
> I just tested Microsoft Edge 98.0.1108.43 and Mozilla Firefox 96.0.3 on Windows 11 (version 10.0.22000.469), the flicker still exists and it has no difference compared with before.
> 
> > by flickering what do you guys mean exactly?
> > > the full windows flickering, like this? https://drive.google.com/file/d/1nBdo0L8XYLYcFDeqVmh0YQnlQr0o2f6J/view
> > > or just the right side not refreshing fast enough so you see everything drawn in the wrong position for a few millisec?
> 
> @JulienMaille I've never seen the first kind of flickering before, so the flickering issue **I** am talking about refers to the second one, though I'm not sure @camgaertner is refering to which one.

https://user-images.githubusercontent.com/10566658/153373986-cd5ae7cd-0644-4db6-901b-9a99fa470323.mp4

So I've also not seen the flickering that you have @JulienMaille (looks like flashing). This is the flickering that I'm seeing.

BTW @wangwenx190 could you link me to your proposed Qt patch? I might want to test it out in the meantime. Thanks :)

**Comment by wangwenx190** [comment]
> So I've also not seen the flickering that you have @JulienMaille (looks like flashing). This is the flickering that I'm seeing.

What we are talking about is the same with what you observe, at least the same with the screen recording you uploaded here. The window contents are not repainted in time during resize, so there will be flickers. It can be workaround by leaving some space for the non-client area (for some unknown reason) in `WM_NCCALCSIZE`. We are having this issue due to FramelessHelper has removed the whole non-client area. We don't keep some non-client area because the window will look ugly on Windows 7~8.1 and it also has some weird appearance on Win10, but the latter issue can be solved by changing some of QPA's code, and that's what I'm trying to bring to Qt itself.

> BTW @wangwenx190 could you link me to your proposed Qt patch? I might want to test it out in the meantime. Thanks :)

I've break it into several different small patches, I'm waiting for them to be merged first. The main patch also need some tweaks, I'll give you the link when I think it's ready.

**Comment by wangwenx190** [comment]
> BTW @wangwenx190 could you link me to your proposed Qt patch? I might want to test it out in the meantime. Thanks :)

@camgaertner Here's the Qt patch: <https://codereview.qt-project.org/c/qt/qtbase/+/384712>, I think it's somewhat in good shape now.

**Comment by JulienMaille** [comment]
@wangwenx190 what is this patch covering? The complete frameless feature or just a fix for flickering?

**Comment by wangwenx190** [comment]
> @wangwenx190 what is this patch covering? The complete frameless feature or just a fix for flickering?

@JulienMaille  It's the complete frameless feature, but only works on Win10 and onwards (currently Win10 ~ 11). For this patch, only the title bar is removed, all other parts such as frame shadow and frame border are still there. And because there still exists some non-client area, the flicker issue is also fixed (but not for Qt Quick due to it uses D3D/OpenGL/Vulkan to draw everything, they also have flicker issue, but the reason is totally different).

**Comment by JulienMaille** [comment]
Thanks, does it means it also improves the resting area on borders?

**Comment by wangwenx190** [comment]
> Thanks, does it means it also improves the resizing area on borders?

The resizing area will be outside of the window, just like native Win32 windows.

**Comment by JulienMaille** [comment]
Wow that's flawless then!
Is it hard to implement a switch to this repository when win7/8 is detected?

**Comment by wangwenx190** [comment]
> Is it hard to implement a switch to this repository when win7/8 is detected?

No it's not hard, but the akward thing is for my Qt patch, we need to modify QPA's code to make it work, that's what we can't achieve in this repo. If you mean let that patch supports Win7, from the code perspective it of course can, but I guess the Qt engineers won't accept, because Win7 is not supported officially and add support for win7 will increase the code quite some bit, from their point of view, I may be adding a lot of code that won't be usable at all, so I just only add the Win10 code to be safe.

> seems like there is a bit of work to port it to Qt5

I once tried to bring it to Qt5, there's not much work. But Qt5 is in LTS mode so it won't accept such new feature. And Qt6 offcially dropped Win7/8/8.1 support, so there's nothing stopping this patch now.

If my patch can be accepted in the end, I can send you the diff for both Qt5 & Qt6, which includes win7 support, you can build from source with the patch applied if you want a complete feature.

**Comment by camgaertner** [comment]
> the flicker issue is also fixed (but not for Qt Quick due to it uses D3D/OpenGL/Vulkan to draw everything, they also have flicker issue, but the reason is totally different).

What's the reason for the flicker on QtQuick? Wonder if you have any idea of how to fix it for QtQuick

**Comment by wangwenx190** [comment]
> > the flicker issue is also fixed (but not for Qt Quick due to it uses D3D/OpenGL/Vulkan to draw everything, they also have flicker issue, but the reason is totally different).
> 
> What's the reason for the flicker on QtQuick? Wonder if you have any idea of how to fix it for QtQuick

For Win32 applications: mostly use GDI to draw everything. There are some DWM magic that causes windows can't paint in time, the repainting is delayed behind the actual resizing operation, so flicker is observed. In theory if the resizing and repainting are in sync with each other, then there will be no more flickering. The only way to reduce flicker is to try our best to make resizing and repainting keep in sync, and avoid repainting the whole window. Instead, try to only repaint the "dirty" area, to decrease the repaint overhead.

For UWP/WPF/Qt Quick applications: use DX (D3D11) to draw everything (Qt Quick addtionally supports OpenGL and Vulkan). UWP create windows with the `WS_EX_NOREDIRECTIONBITMAP` style (with this style, the window will become totally transparent, Windows won't draw anything on it, any processing of `WM_PAINT` will be useless), and draw everything manully through DX, so it won't flicker at all, because there's nothing to flicker. WPF and Qt Quick applications won't have the Win32 flicker issue, because they use DX to draw everything, but still there are flickers can be observed, why? According to what I learned from Qt graphics experts, D3D11 (and including Vulkan) has some rendering issues if frame size mismatch, that is, during window resizing. I don't know how UWP solved this, neither do Qt experts. Probably some internal Windows magic? Who knows.

**Comment by JulienMaille** [comment]
> I once tried to bring it to Qt5, there's not much work. But Qt5 is in LTS mode so it won't accept such new feature. And Qt6 offcially dropped Win7/8/8.1 support, so there's nothing stopping this patch now.

Well the lack of support for 32bit and Win7 forces me to stay with Qt5.15
I'm working with [Kde](https://invent.kde.org/qt/qt/qt5.git) branch who is cherry picking the most important fixes from Qt6 (in agreement with Digia) so I'm already recompiling Qt5 for my needs.
I would love to test your Qt5 patch on my codebase, maybe you could clone `qtbase` and commit on it? I could then test, debug and submit PR if needed

**Comment by wangwenx190** [comment]
> > I once tried to bring it to Qt5, there's not much work. But Qt5 is in LTS mode so it won't accept such new feature. And Qt6 offcially dropped Win7/8/8.1 support, so there's nothing stopping this patch now.
> 
> Well the lack of support for 32bit and Win7 forces me to stay with Qt5.15 I'm working with [Kde](https://invent.kde.org/qt/qt/qt5.git) branch who is cherry picking the most important fixes from Qt6 (in agreement with Digia) so I'm already recompiling Qt5 for my needs. I would love to test your Qt5 patch on my codebase, maybe you could clone `qtbase` and commit on it? I could then test, debug and submit PR if needed

Currently Qt engineers haven't review my new patchset, so the implementation may change, once it's done, I can fork qtbase on Github and port my patch to it.

**Comment by wangwenx190** [comment]
Fixed in 2.0
