### ISSUE TITLE
可以给一个能用的compile教程吗

### ISSUE THREAD

**Issue by 2042Third** [wangwenx190/framelesshelper#297]
说实话到现在我还没能在windows上成功build过framelesshelper。是教程太老了还是什么原因，我已尝试过好几个月了。mac版本的还是我用了一个老的版本才能用的。

`ninja: error: 'C:/Users/user/Documents/framelesshelperBuild/lib/FramelessHelperCore.lib', needed by 'CMakeFiles/project_autogen_timestamp_deps', missing and no known rule to make it`

Compile完了然后install到framelesshelperBuild文件夹里，然后我的project就死活不认这玩意。。。。。；。

**Comment by 2042Third** [comment]
我刚刚试到了2.3.6 可以compile了。

**Comment by wangwenx190** [comment]
可能我早期的cmakelist没写对导致的，尽量用最新代码

**Comment by wangwenx190** [comment]
编译不过的话尽早提issue，我会尽快看的
