### ISSUE TITLE
编译过程报错：表达式的计算结果不是常数。

### ISSUE THREAD

**Issue by Jozoooooo** [wangwenx190/framelesshelper#298]
cmake过程正常，但是build时报错：“表达式的计算结果不是常数”。
使用Windows11，Visual Studio 2019，Qt 6.2.4版本。
下面是build日志：
[BuildLog.txt](https://github.com/wangwenx190/framelesshelper/files/13037751/BuildLog.txt)

**Comment by wangwenx190** [comment]
换个Qt版本试试

**Comment by Jozoooooo** [comment]
OK，换版本之后可正常编译。
