### ISSUE TITLE
[Windows] [Win10] The top frame is missing

### ISSUE THREAD

**Issue by wangwenx190** [wangwenx190/framelesshelper#30]
```cpp
case WM_NCCALCSIZE: {
    const auto mode = static_cast<BOOL>(msg->wParam);
    *result = mode ? WVR_REDRAW : 0;
    const auto clientRect = mode
                                ? &(reinterpret_cast<LPNCCALCSIZE_PARAMS>(msg->lParam)->rgrc[0])
                                : reinterpret_cast<LPRECT>(msg->lParam);
    const UINT dpi = GetDpiForWindow(msg->hwnd);
    const int sizeFrameX = GetSystemMetricsForDpi(SM_CXSIZEFRAME, dpi);
    const int sizeFrameY = GetSystemMetricsForDpi(SM_CYSIZEFRAME, dpi);
    const int paddedBorder = GetSystemMetricsForDpi(SM_CXPADDEDBORDER, dpi);
    const int bw = sizeFrameX + paddedBorder;
    const int bh = sizeFrameY + paddedBorder;
    const RECT originalRect = *clientRect;
    const LRESULT ret = DefWindowProcW(msg->hwnd, WM_NCCALCSIZE, msg->wParam, msg->lParam);
    if (ret != 0) {
        *result = ret;
        return true;
    }
    *clientRect = originalRect;
    clientRect->top += 1;
    clientRect->bottom -= 0;
    clientRect->left += bw;
    clientRect->right -= bw;
    *result = 0;
    return true;
}
```
It's quite easy to preserve the left frame and right frame, so now let's talk about the top frame and bottom frame.

### The bottom frame

- `clientRect->bottom -= 0;` makes the bottom frame totally removed, including the resize area, but the bottom frame shadow is still there.
- `clientRect->bottom -= 1;` preserves the bottom frame, the resize area is still there as well, but it's only 1px height now so it's very hard to grab. The bottom frame shadow is still there.
- `clientRect->bottom -= bh;` preserves the full bottom frame, which means the resize area is 8px height (when DPI is 96), the same with standard windows. The bottom frame shadow is still there, of course.

### The top frame

- `clientRect->top += 0;` makes the top frame totally removed, including the system title bar (including the window icon, the title text and the 3 system buttons) and the resize area, but the top frame shadow is still there.
- `clientRect->top += 1;` preserves the top frame, the resize area is still there as well, but it's only 1px height now so it's very hard to grab. The top frame shadow is still there.
- `clientRect->top += bh;` preserves the full top frame, which means the resize area is 8px height (when DPI is 96), the same with standard windows, but sadly the system title bar comes back at the same time. The top frame shadow is still there, of course.

### Conclusion

I tried to combine `clientRect->top += 1;` with `clientRect->bottom -= bh;` or `clientRect->bottom -= 1;` to preserve the full window frame, however, the title bar comes back.

The conclusion for now: we can only preserve the top frame or the bottom frame, it's not possible to preserve them both without extra work.

**Comment by wangwenx190** [comment]
Current solution: preserve the bottom frame and draw the top frame manually through QPainter. The appearance is not bad.

**Comment by JulienMaille** [comment]
This is one is fixed, isn't it?

**Comment by wangwenx190** [comment]
> 
> 
> This is one is fixed, isn't it?
>
For this issue, I want to use the native window frame. But currently we are drawing the window frame ourself. I think it's two different thing. I still want to find a solution to preserve the native frame. I think I'll leave it open until I can find a solution.

**Comment by wangwenx190** [comment]
Seems impossible to fix this issue without modifying Qt itself. Close this issue for now. Only fixable inside Qt.
