### ISSUE TITLE
Dialog顶栏触摸区域的优化

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#308]
下图这个区域，是不能拖动Dialog的，这个可以优化么？
![image](https://github.com/wangwenx190/framelesshelper/assets/88725450/15207629-e706-4f3e-85f9-c94bc3c275d5)

**Comment by wangwenx190** [comment]
那个是resize区域，当然不能拖动了

**Comment by ohPigFly** [comment]
我理解是，如果这个框是不可以变化大小的了，这里这个区域应该是可触摸区域。

**Comment by wangwenx190** [comment]
目前没有实现这个功能，不过你的建议很合理

**Comment by wangwenx190** [comment]
试试最新代码呢，应该是实现了你想要的效果

**Comment by ohPigFly** [comment]
SHA-1: 85a3fe1b2f718ff94f83833241c202ee9ef9908a
测试，可以了。
