### ISSUE TITLE
Window Content keeps getting clipped when resizing 

### ISSUE THREAD

**Issue by Qmlio** [wangwenx190/framelesshelper#310]
https://github.com/wangwenx190/framelesshelper/assets/65741732/7f5924ae-1c01-4877-9087-cb8577ede20c

Greetings.
Am really glad about this project, but while using the FramelessHelper in qml, every time i try to resize the window, its content gets clipped especially around the footer and header of the ApplicationWindow.

*** Steps to reproduce***
Using the ***FramelessHelperDemo-Quick*** examples project, add a ***Label*** and position it at the bottom or add a footer to the ***ApplicationWindow***, run the project and try resizing the window from from the top.

**Comment by wangwenx190** [comment]
Looks like a Qt bug. What's your Qt version? And are you using the latest code from the main branch?

**Comment by Qmlio** [comment]
Am using Qt 6.5.3 , Visual Studio  2019. A using the latest code from the branch because i fetched it two days back!

**Comment by Qmlio** [comment]
I have noticed its a Qt 6.5.3 bug, because i have tested with Qt 6.5.1 and Qt 6.3.2 and every thing worked as expected, indeed you were right.. thanks for the help

**Comment by wangwenx190** [comment]
Please check <https://github.com/wangwenx190/framelesshelper/commit/33a6f0df91010473cc05b4c980151c4a2b329571>

**Comment by Qmlio** [comment]
Ah Yes!....Thanks kindly

**Comment by wangwenx190** [comment]
And the upstream fix: <https://github.com/qt/qtbase/commit/58a6a92f688fccf9e841dea6976409d97a6dd3b0>

**Comment by Qmlio** [comment]
I see.....thanks again!
