### ISSUE TITLE
Dialog窗体阴影闪烁效果

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#313]
请问就是在MainWindow的demo里面，通过按键触发显示的Dialog，然后点击Dialog范围外，窗体的阴影闪烁效果，这个是需要去类似直角配置项那样去设置的么？

**Comment by wangwenx190** [comment]
阴影是系统提供的，和原生窗口的表现是一模一样的。不是FramelessHelper能控制的。

**Comment by ohPigFly** [comment]
好的，我找到原因了，原来是没有把主窗口当父类传递进去，就不会有闪烁效果。
