### ISSUE TITLE
系统按键使能或禁用

### ISSUE THREAD

**Issue by ohPigFly** [wangwenx190/framelesshelper#314]
请问顶栏的系统按键，有开放接口可控制使能或禁用的么？

**Comment by wangwenx190** [comment]
什么系统按键？你是指标题栏的右键菜单吗？你要如何定制？

**Comment by ohPigFly** [comment]
下图，就是有需求在dilog的时候，关闭按键不可使用。
![Uploading image.png…]()

**Comment by ohPigFly** [comment]
> 下图，就是有需求在有些dilog界面，关闭按键不可使用。 ![image](https://user-images.githubusercontent.com/88725450/280908635-8d51a621-c6f1-426c-894a-9519ef0c3be2.png)

**Comment by wangwenx190** [comment]
你可以直接用自己的标题栏，就能随心所欲的控制这些按钮了

**Comment by ohPigFly** [comment]
我只是看到Qt的窗体有这个用法，所以就突想到的。刚找到了，你有开发可以获取到这些button出来，就可以设置了。

**Comment by ohPigFly** [comment]
> 你可以直接用自己的标题栏，就能随心所欲的控制这些按钮了

你这个意思是不是，FramelessHelper是可以支持，塞入一个自己写的TitleBar进去，不一定是使用里面提供的StandardTitleBar。

**Comment by wangwenx190** [comment]
> 我只是看到Qt的窗体有这个用法，所以就突想到的。刚找到了，你有开放可以获取到这些button出来，就可以设置了。

确实，我是有提供接口的，但只是针对我默认的那个标题栏，定制性比较弱，所以没有在这里和你说。

**Comment by wangwenx190** [comment]
> > 你可以直接用自己的标题栏，就能随心所欲的控制这些按钮了
> 
> 你这个意思是不是，FramelessHelper是可以支持，塞入一个自己写的TitleBar进去，不一定是使用里面提供的StandardTitleBar。

是的，我有一个`setTitleBarWidget`函数，你可以把任意的`QWidget`塞进去作为你自己的标题栏的。你当然可以继续使用我提供的那个`StandardTitleBar`，如果它本身能满足你的需求的话。
