### ISSUE TITLE
Frameless Window can't be resized on Mac OS X

### ISSUE THREAD

**Issue by skarnproject** [wangwenx190/framelesshelper#32]
I am having an issue, the Window does not resize with dragging borders on Mac OS. I can see a drag cursor for a moment, but it does not move.

**Comment by wangwenx190** [comment]
Several people told me about this issue, it seems the `startSystemResize()` function is unusable on macOS.

**Comment by wangwenx190** [comment]
See: <https://doc.qt.io/qt-5/qwindow.html#startSystemResize>

**Comment by skarnproject** [comment]
Yeah, thanks for pointing the issue out. Is there a way to track those mouse movements on the edge manually? 
It seems we can check against system resize support by doing this:

if (!window.startSystemResize(edges)) {
    // fallback code for setting window.width/height manually
}

It should return false if not supported.

**Comment by wangwenx190** [comment]
> 
> 
> Yeah, thanks for pointing the issue out. Is there a way to track those mouse movements on the edge manually?
> It seems we can check against system resize support by doing this:
> 
> if (!window.startSystemResize(edges)) {
> // fallback code for setting window.width/height manually
> }
> 
> It should return false if not supported.

Sounds reasonable. I'll try to implement this.

**Comment by wangwenx190** [comment]
Now I know the frameless window can't be resized, but can it be moved by dragging the custom title bar?

**Comment by wangwenx190** [comment]
New commit uploaded. Can you test the latest code?

**Comment by wangwenx190** [comment]
If this issue still exists, please inform me.

**Comment by skarnproject** [comment]
> Now I know the frameless window can't be resized, but can it be moved by dragging the custom title bar?

Yes, it works. It also gets resized by double clicking on the titlebar.



> If this issue still exists, please inform me.

Yes, the issue still exists. It does resize now, but does not resize with delta, it jumps to a certain extent. The video is below.
https://youtu.be/l3NAXiTq9Ow

**Comment by wangwenx190** [comment]
> 
> 
> > Now I know the frameless window can't be resized, but can it be moved by dragging the custom title bar?
> 
> Yes, it works. It also gets resized by double clicking on the titlebar.
> 
> > If this issue still exists, please inform me.
> 
> Yes, the issue still exists. It does resize now, but does not resize with delta, it jumps to a certain extent. The video is below.
> https://youtu.be/l3NAXiTq9Ow

OK, I see. I'm working on it.

**Comment by wangwenx190** [comment]
New commit uploaded. Can you the latest code? I suggest you try more test cases: top bottom left right top-left top-right bottom-left bottom-right

**Comment by wangwenx190** [comment]
I don't have a mac so I'm relying on my imagination to debug this code. I want to see a screen record if possible, thanks.

**Comment by skarnproject** [comment]
> New commit uploaded. Can you test the latest code? I suggest you try more test cases: top bottom left right top-left top-right bottom-left bottom-right

Nope. Very wrong now. I suggest you turn off system resize logic for your case temporarily, so you can test it on your machine.

https://youtu.be/xxApuQhrsKQ

**Comment by wangwenx190** [comment]
> 
> 
> > New commit uploaded. Can you test the latest code? I suggest you try more test cases: top bottom left right top-left top-right bottom-left bottom-right
> 
> Nope. Very wrong now. I suggest you turn off system resize logic for your case temporarily, so you can test it on your machine more easily.
> 
> https://youtu.be/xxApuQhrsKQ

It does look very strange now. Working on it.

**Comment by wangwenx190** [comment]
I made a bug report to the Qt company: <https://bugreports.qt.io/browse/QTBUG-88218>

If the Qt company are not willing to fix it in the near future, I'll implemenet an alternative solution.

**Comment by skarnproject** [comment]
> I made a bug report to the Qt company: https://bugreports.qt.io/browse/QTBUG-88218
> 
> If the Qt company are not willing to fix it in the near future, I'll implemenet an alternative solution.

Afaik it is not supported on other platforms as well. The other machine this was tested on running on Debian/GNOME/X11. Also returns falls. Works on Windows though.

**Comment by wangwenx190** [comment]
>
> Afaik it is not supported on other platforms as well. The other machine this was tested on running on Debian/GNOME/X11. Also returns false.
>
I tested this repo on Fedora KDE (X11) and it works well. And it should not return false on Linux:

![图片](https://user-images.githubusercontent.com/17877450/98315536-5c4dc480-2013-11eb-9b4f-ed0a41a9f914.png)

**Comment by skarnproject** [comment]
> > Afaik it is not supported on other platforms as well. The other machine this was tested on running on Debian/GNOME/X11. Also returns false.
> 
> I tested this repo on Fedora KDE (X11) and it works well. And it should not return false on Linux:
> 
> ![图片](https://user-images.githubusercontent.com/17877450/98315536-5c4dc480-2013-11eb-9b4f-ed0a41a9f914.png)

Maybe the issue is tied to GNOME environment?

**Comment by wangwenx190** [comment]
>
> Maybe the issue is tied to GNOME environment?
>
Not sure. I didn't test in GNOME. One point: recent versions of GNOME is using Wayland instead of X11.

**Comment by wangwenx190** [comment]
Sadly the Qt engineer told me it's not possible to implement `startSystemResize()` on macOS. I'm not a macOS developer, so I don't know why, but it sounds like a technical limitation.

**Comment by wangwenx190** [comment]
Fixed in 2.0
