### ISSUE TITLE
Windows下标题栏按钮tooltip重复显示

### ISSUE THREAD

**Issue by kira-96** [wangwenx190/framelesshelper#325]
**系统：Windows 11**

Win11 标题栏按钮的tooltip和系统的重复了，暂时不清楚Win10及以下版本是否会出现这个问题。

![image](https://github.com/wangwenx190/framelesshelper/assets/22876709/843ff1f2-71a0-4d52-adac-bbe3c310411f)

相关代码：

https://github.com/wangwenx190/framelesshelper/blob/096d30b8cf81392fde2b54abe41be82423a125ae/src/widgets/standardtitlebar.cpp#L339-L346

**Comment by wangwenx190** [comment]
行，我处理下

**Comment by kira-96** [comment]
https://github.com/wangwenx190/framelesshelper/commit/2765d18634299a738cb689b055511a51ac947b53 改的不彻底，还是会显示，我又改了一下。#326

**Comment by wangwenx190** [comment]
确实忘记了，已经合并，谢谢！
