### ISSUE TITLE
closeEvent事件，对QCloseEvent事件进行ignore后，原来无边框的窗体会出现边框

### ISSUE THREAD

**Issue by czyt1988** [wangwenx190/framelesshelper#327]
closeEvent事件，对QCloseEvent事件进行ignore后，原来无边框的窗体会出现边框

```cpp
void MainWindow::closeEvent(QCloseEvent* e)
{
    auto res = QMessageBox::question(this, tr("question"), tr("Confirm whether to exit"));
    if (res == QMessageBox::Yes) {
        e->accept();
    } else {
        e->ignore();
    }
}
```

此问题是对ignore后出现的

正常状态：
![image](https://github.com/wangwenx190/framelesshelper/assets/7260393/a2d2c141-8023-409c-8efc-81c2948afd6a)

在closeEvent进行ignore后，边框出现了，且原来可移动的区域失效

![image](https://github.com/wangwenx190/framelesshelper/assets/7260393/3e52b28f-a158-45b4-91bd-a68d4349c7bd)

**Comment by wangwenx190** [comment]
前几周才改了个相关问题。最新代码还能复现吗

**Comment by czyt1988** [comment]
经验证最新版已经修复此问题
