### ISSUE TITLE
Click the taskbar icon to restore the window

### ISSUE THREAD

**Issue by Caprey** [wangwenx190/framelesshelper#35]
After the window is maximized, click the minimize button, and then click the taskbar icon to restore the window. At this time, the window size is incorrect
![T2](https://user-images.githubusercontent.com/28674556/98654470-53455600-2379-11eb-9dc2-53b501844dda.gif)

**Comment by wangwenx190** [comment]
我这边用QWidget、QMainWindow和Win32Demo这三个例子都无法复现，只有Quick例子能复现

**Comment by Caprey** [comment]
我使用了双屏，主屏才会出现上面的情况，副屏是正常的

**Comment by wangwenx190** [comment]
> 
> 
> 我使用了双屏，主屏才会出现上面的情况，副屏是正常的

正常的Qt窗口有这个问题吗？

**Comment by Caprey** [comment]
正常的窗口是没有这个问题的

**Comment by wangwenx190** [comment]
> 
> 
> 正常的窗口是没有这个问题的

你拉下最新的代码，然后把`WM_GETMINMAXINFO`这个里面所有的代码都注释掉，重新编译，看看能不能解决这个问题

**Comment by wangwenx190** [comment]
我这边没有第二个显示器，唯一的显示器还不是高分屏，所以类似的bug我都没法亲自测试，只能靠你们手动反馈了

**Comment by JulienMaille** [comment]
I just tried Win32Demo and latest code. I can't reproduce it on both screens

**Comment by yanzichu** [comment]
最新代码，win10 20H2，Qt 5.15.2，当主窗口中间包含一个原生窗口（使用了Qt::WA_NativeWindow等一系列属性，负责渲染d3d画面）时，复现描述中的步骤，会出现原生窗口渲染不正常的现象。但是只要操作一下取消最大化，窗口立刻恢复正常

**Comment by wangwenx190** [comment]
> 最新代码，win10 20H2，Qt 5.15.2，当主窗口中间包含一个原生窗口（使用了Qt::WA_NativeWindow等一系列属性，负责渲染d3d画面）时，复现描述中的步骤，会出现原生窗口渲染不正常的现象。但是只要操作一下取消最大化，窗口立刻恢复正常
> 
> PS:当我把WM_NCCALCSIZE消息最后的result值直接赋予0而不是WVR_REDRAW时，似乎看起来解决了问题

这个是已知问题，无条件返回0就可以避免d3d绘制出现问题。但我记得代码中绝大多数时候都是返回0吧？返回WVR_REDRAW的条件也比较苛刻

**Comment by wangwenx190** [comment]
> 最新代码，win10 20H2，Qt 5.15.2，当主窗口中间包含一个原生窗口（使用了Qt::WA_NativeWindow等一系列属性，负责渲染d3d画面）时，复现描述中的步骤，会出现原生窗口渲染不正常的现象。但是只要操作一下取消最大化，窗口立刻恢复正常
> 
> PS:当我把WM_NCCALCSIZE消息最后的result值直接赋予0而不是WVR_REDRAW时，似乎看起来解决了问题

最新的代码已经无条件返回0了，应该是没这个问题了

**Comment by wangwenx190** [comment]
感觉应该解决了。先close了，有问题再重新open吧

**Comment by camgaertner** [comment]
Hi @wangwenx190  I'm seeing this issue still. It can be reproduced with the QtQuick example.. Video attached.

Reproduce: 
1. Maximize via MaximizeButton. 
2. Minimize via MinimizeButton. 
3. Restore via Windows Toolbar.

Note: This doesn't occur if you minimize via windows toolbar for step 2. 

What I tried: Installing a Qt event filter and saving whether or not the window was previously maximized. If it was, then when it is restored I maximized it again. However, this gives a bad flickering effect.
Example Code:
```
bool FramelessQuickHelper::eventFilter(QObject* object, QEvent* event)
{
    Q_ASSERT(object);
    Q_ASSERT(event);
    if (!object || !event) {
        return false;
    }

    // Only monitor window events.
    if (!object->isWindowType()) {
        return false;
    }

  const QEvent::Type type = event->type();
  if (type == QEvent::WindowStateChange) {
        if (window()->windowState() & Qt::WindowMaximized)
            m_maximized = true;
        else if (window()->windowState() & Qt::WindowNoState)
            m_maximized = false;
  
        QWindowStateChangeEvent* ev = static_cast<QWindowStateChangeEvent*>(event);
        if (ev->oldState() & Qt::WindowMinimized && m_maximized) {
            window()->setWindowState(Qt::WindowMaximized);
        }
    }
  
      return false;
  }
```

OS
```
Microsoft Windows 10 Pro
Version 10.0.19042 Build 19042
```
Qt: 5.15.2

Thanks!

https://user-images.githubusercontent.com/10566658/153202666-2ed91c3c-3154-4ad9-b7b8-da2be233a9a2.mp4

**Comment by camgaertner** [comment]
After looking at it more, it seems to be a QtQuick issue - not related to your code at all. In fact, calling showMinimize from a QtQuick application will cause this issue. If future people need to fix it, you can do this

https://bugreports.qt.io/browse/QTBUG-69711

i.e...
```
void FramelessQuickHelper::minimize() const
{
    // Qt bug: https://bugreports.qt.io/browse/QTBUG-69711
#ifdef OS_WINDOWS
    ShowWindow((HWND)window()->winId(), SW_SHOWMINIMIZED);
#elif
	window()->showMinimized();
#endif
}
```

If you want to add this to the example it's doable, but maybe not necessary since this is a QT bug. Thx

**Comment by wangwenx190** [comment]
@camgaertner Thanks for the information! It's really helpful!

**Comment by wangwenx190** [comment]
@camgaertner I've added the workaround to the demo application. Thanks for your solution!

**Comment by camgaertner** [comment]
@wangwenx190 Awesome! Thanks :)
