### ISSUE TITLE
[Windows] [Win10] Assert error after enabling Acrylic effect

### ISSUE THREAD

**Issue by Caprey** [wangwenx190/framelesshelper#37]
![image](https://user-images.githubusercontent.com/28674556/99481854-f9a2e400-2995-11eb-955b-8a77bd1b5e39.png)

**Comment by wangwenx190** [comment]
最新的代码为了去除对Qt Widgets和Qt Quick这两个模块的依赖，重构了很多，接口也改了，主要是原来接收的是`QObject`指针，现在只能接受`QWindow`指针了，但由于`QWindow`是`QObject`的派生类，所以如果你代码没改，编译时也不会报错，但运行时肯定会报错，现在只能手动修改了。`FramelessWindowsManager`和`WinNativeEventFilter`（包括为UNIX平台设计的`FramelessHelper`这个类）现在只接受`QWindow`指针了，你改改你代码里相关的地方，应该就不会报错了。

还有个跟你这个截图直接相关的已知问题：对于Win32Demo这个示例程序，如果勾选了“强制开启亚克力效果”，然后启用模糊特效，会报断言错误，就是你这个截图。普通的模糊特效不会这样，只有启用亚克力后才会这样。目前暂时不知道怎么回事，还在研究。

真的非常抱歉了。

**Comment by JulienMaille** [comment]
QMainWindow also crashes when interacting with Menu or QDockWidgets
![image](https://user-images.githubusercontent.com/182520/100439909-6871f280-30a4-11eb-9734-dbc5b5ea69a0.png)

**Comment by wangwenx190** [comment]
@JulienMaille Don't quite understand what's happening behind all these. For now you could revert commit b672851f515ca6caa812bbfaa6ca3a27b9dff093 to fix it.
