### ISSUE TITLE
See through issue during maximizing and minimizing the window.

### ISSUE THREAD

**Issue by shujaatak** [wangwenx190/framelesshelper#4]
Related to `master `branch:
I noticed that as soon as I **maximize** or **minimize** the window by **double clicking on the title bar**, momentarily I can see through the window as if window becomes transparent. This problem doesn't occur in `win10_only `branch.

You can verify it by having some colorful background and then try to maximize and minimize the window.

**Comment by wangwenx190** [comment]
Thanks for your testing!
Is it looks like the window becomes totally transparent at that moment and it becomes not transparent after it's maximized, just like flashing? If it is, I'm aware of it, it's a known bug from the very beginning, but I don't have much clue about what caused it.

**Comment by shujaatak** [comment]
> just like flashing?

Yes

**Comment by wangwenx190** [comment]
After some randomly trying, I succeeded solving this issue, within one minute. Maybe this day is my lucky day.
