### ISSUE TITLE
[Windows] [Win10] [msvc] When moves widget in double screen, the layout is misplaced

### ISSUE THREAD

**Issue by XwAdmin** [wangwenx190/framelesshelper#41]
在实际项目中使用时，发现在两个屏幕中移动时，布局里的组件会发生错位的情况。
单独创建了一个小工程复现了一下，如下图。
![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-b1ebbd3c-ca49-405b-957b-effe60782276/75169338-a569-4b0c-861e-e2e6819d5a90.png)

环境：msvc2019 + win10 + qt5.15 + 双屏
![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-b1ebbd3c-ca49-405b-957b-effe60782276/0599bfd7-0cde-47a1-901c-ec0a4cc0df59.png)

**Comment by wangwenx190** [comment]
手动resize一下就好了，可能是qt的bug

**Comment by XwAdmin** [comment]
刚刚尝试了一下，在moveEvent中使用resize
resize(size()); 没有效果
resize(width(), height() + 1); 才可以
但是每次移动，都会设置一下大小，就有点疑惑，这是目前的最优方案嘛，还是我操作有误呢。不吝赐教。

**Comment by wangwenx190** [comment]
我测试得到的结论是这样的，单个显示器不存在这个问题，多个显示器，跨显示器移动窗口时大概率会遇到这个问题，但也不是必现的。这个问题跟自定义边框没什么关系，你可以用一个正常的qt窗口试试，也会遇到这个问题。我看了很多开源项目的源码，发现基本没有处理这个问题的，所以我建议你也不用去管。如果你想解决，可以监听qt的screenChanged信号，当屏幕发生改变时手动触发一次resize，和原来大小相同肯定没用，但为了尽可能减小用户的感知，可以只改变一个像素。这也是临时的解决方案，最终的解决方案还是要qt自身做出修改。

**Comment by XwAdmin** [comment]
辛苦，thanks.

**Comment by wangwenx190** [comment]
这个问题我去年就发现了，不过这是个普遍问题，qt程序都存在，也没见有去解决的，你可以不用管

**Comment by wangwenx190** [comment]
> FYI @wangwenx190 this bug is back when using code from latest commit (with the "widget" example)

The word "back" may not be accurate. The issue always exists. We indeed fixed this issue long time ago. But I was wondering the performance and reliability of our workaround, so I removed it some time ago, last year some day. I think we may just live with it because most frameless Qt applications have this issue.
