### ISSUE TITLE
With QSplitter

### ISSUE THREAD

**Issue by XwAdmin** [wangwenx190/framelesshelper#44]
当使用QSplitter作为一个界面最边缘侧组件时，
QSplitter 拖拽最小化，将无法再最大化。
考虑是不是因为边框调整大小的宽度遮住了QSplitter 的 handle 。
如下动图：
鼠标拖动QSplitter 到界面最边缘，鼠标松开后，界面的边框会遮挡QSplitter。
![](https://www.toopan.cn/view.php/e9739a4f993bdeca64c2b5dfe09494cd.gif)

**Comment by wangwenx190** [comment]
>
> 是不是因为边框调整大小的宽度遮住了QSplitter 的 handle
>
应该是这个问题，但不好解决啊，因为原生窗口的行为是窗口的拖拽区域位于窗口外部，你内部控件再怎么拖也拖不到外面去，所以不会有这个问题。现在我们的拖拽区域放到窗口里面了，所以就产生了这个问题。

**Comment by XwAdmin** [comment]
好吧。我尝试调整handle宽度 或者 写一个还原函数来解决吧。

**Comment by XwAdmin** [comment]
3Q

**Comment by wangwenx190** [comment]
这我也没办法，只能想办法绕过了
