### ISSUE TITLE
win10 19042  widget demo背景有缓存

### ISSUE THREAD

**Issue by zyb920** [wangwenx190/framelesshelper#51]
![3](https://user-images.githubusercontent.com/14181765/111279178-65ac0500-8675-11eb-9aa7-df8517950120.png)

背后数字有上一次的缓存，移动过程中没有。很奇怪。背景色是白色，移动过程中 无背景色

**Comment by wangwenx190** [comment]
我也发现这个问题了，正在找原因

**Comment by wangwenx190** [comment]
最新代码已修复
