### ISSUE TITLE
Flickers when resizing from left or top border

### ISSUE THREAD

**Issue by JulienMaille** [wangwenx190/framelesshelper#52]
The readme advertises `No flickers when resizing`, however with latest code I think the flicker is back but only from 2 sides out of the 4.
Do you confirm?

**Comment by wangwenx190** [comment]
Yes, the README needs an update. The original solution works but not perfect. I'll try these days to see whether the solution is appropriate or not. If it's not easy to solve, I'll update the README file to remove that line.

**Comment by wangwenx190** [comment]
The solution is easy: just let the client area smaller than it should be, in the WM_NCCALCSIZE message. But it will cause some coordinate issues.

**Comment by JulienMaille** [comment]
I think it would be cool to have a list of tips "you can do fix _this_ issue, with _this_ little drawback"
What kind of coordinate issues would that trigger?

**Comment by wangwenx190** [comment]
>
> I think it would be cool to have a list of tips "you can do fix this issue, with this little drawback"
>
Good idea. I'll update the README file later.

>
> What kind of coordinate issues would that trigger?
>
That trick is to reduce the client area size, you can do it by cut-off some pixels from one of the four edges. If you choose the top or the left edge, the coordinate origin point of Qt's coordinate system will shift some pixels. I can't remember clearly, I'll verify it these days.

**Comment by wangwenx190** [comment]
I tested that trick on Win7 just now. It looks like that trick doesn't work on Win7. I'll try on Win10 later. I remember it works well on Win10, but has the coordinate drawback.

**Comment by wangwenx190** [comment]
Update: Tested on Win10 20H2 x64, that trick doesn't work well anymore. It still works, though.

**Comment by wangwenx190** [comment]
I've updated the README file, that line was removed now. The little trick doesn't work well anymore, and have draw backs, not a good solution.

**Comment by wangwenx190** [comment]
The flicker is gone if you run the demo application on Win10. Tested on Win7 just now, seems still flickering.

**Comment by wangwenx190** [comment]
We can continue discussing this issue in #29 , close this issue for now.
