### ISSUE TITLE
拖动窗口的时候很卡，特别是移出屏幕边缘的时候

### ISSUE THREAD

**Issue by sleepyW** [wangwenx190/framelesshelper#53]
官方示例quick和widget都试过，都很卡，Win10 20H2+QT6.0，请问是什么原因？

**Comment by wangwenx190** [comment]
由于窗口移动会导致背景重绘（我自己模拟的亚克力模糊特效），所以对电脑的性能有一定的要求，但卡肯定不至于，我赛扬的电脑都很流畅。难道你是在虚拟机里运行的？

**Comment by wangwenx190** [comment]
那个模糊特效能关，你试试关了还卡吗？用`setAcrylicEnabled(false)`关闭。

**Comment by wangwenx190** [comment]
我自己的开发机就是Win10 20H2，Qt 6.1和5.15.2都试过，也在Win7的电脑上测过，都不卡。

**Comment by wangwenx190** [comment]
如果你那边实在找不到原因，最好录个屏粘贴上来，不然我确实想象不出来究竟是怎么回事

**Comment by sleepyW** [comment]
`setAcrylicEnabled(false)`
加了这句，没那么卡了。

**Comment by wangwenx190** [comment]
你运行的是自带的例子，无论如何都不应该卡的，而且你说的是“很卡”，这就更不应该了。我实在想不明白为什么。我在配置特别差的电脑上测试过，运行的还是特别老的Win7，不管是Qt5.15.2还是Qt6.1，效果都还不错。虚拟机里我也测试过，也没遇到卡顿的现象。这个问题之前也没人跟我提到过，所以我觉得问题应该不在我这边。

**Comment by wangwenx190** [comment]
刚才我又试了下，发现debug模式下确实有些卡，但不会很卡，release模式下是一点都不卡。
