### ISSUE TITLE
QScreen *QWidget::screen() const since 5.14

### ISSUE THREAD

**Issue by xiaoyanLG** [wangwenx190/framelesshelper#54]
建议尽量使用低版本存在的API，比如这个screen()改成windowHandle()->screen(),或者如果是低版本，直接拷贝源码实现一份screen()，因为你写的windows依赖qt版本>=5.6

**Comment by wangwenx190** [comment]
哦哦，确实，可能没注意到，我改下

**Comment by wangwenx190** [comment]
只有这个问题吗

**Comment by xiaoyanLG** [comment]
你那个最大化/还原的图标使用的时机也不对，双击标题栏最大化的时候图标就没变了。全屏的时候绘制也有一点问题。

**Comment by wangwenx190** [comment]
>
> 双击标题栏最大化的时候图标就没变了
>
那个是示例工程，细节方面没怎么注意，我这个repo毕竟只是一个库，具体怎么用要各位开发者自己考虑

>
>  全屏和最大化切换的时候绘制也有一点问题
>
什么问题？你这描述也太简单了，也没有截图之类的，我从哪里开始判断。。。。

**Comment by wangwenx190** [comment]
在`changeEvent`里判断窗口的状态，再重新设置标题栏的图标就行了，做法我是知道的，只是示例工程没做得那么细致

**Comment by wangwenx190** [comment]
标题栏是用户自己控制的，我这个库只是负责把边框去掉，然后提供标题栏的功能，不负责别的。
