### ISSUE TITLE
QImage wrong argument order

### ISSUE THREAD

**Issue by razaqq** [wangwenx190/framelesshelper#55]
https://github.com/wangwenx190/framelesshelper/blob/16f7d78035136b8f52e5a06a4078f6cfe694ab5d/utilities.cpp#L168

arguments are in wrong order, the constructor is `QImage(int width, int height, QImage::Format format)`

**Comment by wangwenx190** [comment]
Thanks for pointing this out! Nice catch! I can fix it right now, however, this block of code is copied from Qt Widgets module, it means it's a bug of Qt itself. It has not been touched since 2016, means the latest version of Qt still has this bug.

**Comment by wangwenx190** [comment]
After some testing, it turns out it's not a bug. It's intended to be wrote like that. If you change the argument order, the application will crash.

**Comment by wangwenx190** [comment]
I've added a comment in the source code.

**Comment by razaqq** [comment]
ok good to know, closing
