### ISSUE TITLE
使用setResizable固定大小后多屏来回移动窗体变小最后消失

### ISSUE THREAD

**Issue by DarinLi** [wangwenx190/framelesshelper#56]
1、使用FramelessWindowsManager::setResizable(windowHandle(), false)固定程序大小时在双屏幕情况下，来回拖动，程序的窗体越变越小，最后消失。

备注：使用setFixedSize(size())没有这个问题。

2、固定窗体后，窗体边缘部分几个像素点鼠标选中后窗体无法移动。

**Comment by wangwenx190** [comment]
第一个问题听起来像是以前的代码导致的问题，你是用最新的代码测的吗？

第二个问题是因为那部分区域是窗口用来调整尺寸的预留区域，所以不接受除此以外的操作，不过是个可以改进的地方，我这几天改一下。

**Comment by wangwenx190** [comment]
新代码提交了，你试试看第二个问题有没有改善。

**Comment by wangwenx190** [comment]
2.0应该没这个问题了
