### ISSUE TITLE
Frame not properly displayed in mainwindow example

### ISSUE THREAD

**Issue by JulienMaille** [wangwenx190/framelesshelper#57]
It seems like it broke back in April when you removed acrylic from this repository.
Before, `setContentsMargins(1, 1, 1, 1);` fixed it as you suggested in https://github.com/wangwenx190/framelesshelper/issues/48#issuecomment-797311487
Now it seems `setContentsMargins` is ignored or overwritten later
![image](https://user-images.githubusercontent.com/182520/120886979-e6352e80-c5f0-11eb-9256-3c5d74ab94c9.png)

**Comment by JulienMaille** [comment]
If I _hack_ `setContentsMargins(1, 1, 1, 1);` in the `paintEvent()` it works.

**Comment by wangwenx190** [comment]
Sorry for breaking the main window example again. I'll try to fix it tomorrow.

**Comment by wangwenx190** [comment]
> If I _hack_ `setContentsMargins(1, 1, 1, 1);` in the `paintEvent()` it works.

Could you show me how you _hack_ the paint event?

**Comment by JulienMaille** [comment]
The paintevent is reimplements in this example. But it was just a way to tell you it's. Ot _completely_ broken

**Comment by JulienMaille** [comment]
Ok so I think it broke when `updateContentMargin()` was removed from that commit https://github.com/wangwenx190/framelesshelper/commit/cdb7b87eb4ed1b7974bb53d9b634736964aaa9d0
You replaced `setContentsMargins(m, m, m, m);` with `layout()->setContentsMargins(m, m, m, m);` which doesn't seem to do what we want.
You also removed the call from `::showEvent(QShowEvent *event)` which seems to be needed.
Do you agree?

**Comment by wangwenx190** [comment]
>
> You replaced `setContentsMargins(m, m, m, m);` with `layout()->setContentsMargins(m, m, m, m);` which doesn't seem to do what we want.
>
I thought they were the same thing, but now it apparently weren't.

>
> You also removed the call from `showEvent(QShowEvent *event)` which seems to be needed.
>
It shouldn't be removed indeed. But I can't remember the exact reason why I removed it that time, maybe just a mistake.
