### ISSUE TITLE
Ignore areas method as shown in example doesn't work quite well for the widgets in layouts.

### ISSUE THREAD

**Issue by shujaatak** [wangwenx190/framelesshelper#6]
**I think** passing the **references of the Widgets** to the framelesshelper would work nice. There in framelesshelper you can dynamically check the geometries of the Widgets and use them for ignoring the areas.

**Comment by wangwenx190** [comment]
Yes, you are right, the current way is not flexible enough. I'll improve this in the next commit.

**Comment by wangwenx190** [comment]
Try the new member of WINDOWDATA: `ignoreObjects`.
