### ISSUE TITLE
support Round corners in windows 10 and using designer ui files?

### ISSUE THREAD

**Issue by YouKnow-sys** [wangwenx190/framelesshelper#62]
Hi, sorry if its not a good question, I don't test your project Properly yet.
I just curious to know 2 things:

- this code support Round corners in windows 10?
I tested many projects, but none of them work as I excepted...
![image](https://user-images.githubusercontent.com/17937017/126049992-cce997b1-e2fd-4dcd-b290-e0b5972d7272.png)
the real window corner are still visible if I make the windows corner round...

- its possible to use ui file that generated with Qt designer?

thanks for your good work.

**Comment by wangwenx190** [comment]
>
> this code support Round corners in windows 10?
>
Of course you can make the window have round corners, but it's not related to this repo. You need the Win32 API `SetWindowRgn` to do this. You can always make window have round corners with that API, no matter the window is frameless or not. And it's not related the OS version either, you can always use that API on any Windows versions.

>
> its possible to use ui file that generated with Qt designer?
>
Of course. Just remember to call `FramelessWindowsManager::addWindow()` after the window is created.

**Comment by YouKnow-sys** [comment]
> You need the Win32 API `SetWindowRgn` to do this.

thank you for fast reply, I'm new to c++ so I don't know much about it, (especially winapi function)
if you have some free time can you please show me how can I do this in your code?

**Comment by YouKnow-sys** [comment]
and also i think its will be good to add support of qt in visual studio too

**Comment by wangwenx190** [comment]
>
> and also i think its will be good to add support of qt in visual studio too
>
Qt has official support for Visual Studio, you need to install a tool/extension called "Qt VS Tool", which is developed by The Qt Company. As for this repo, it offers the traditional QMake pro file, it also offers the CMake project files. If you have installed Qt VS Tool, you can open .pro files directly in VS. VS can always open CMakeLists.txt with or without Qt VS Tool.

>
> how can I do this in your code
>
I have to say again, it's totally not related to my code. You can call that API at anywhere and anytime, on any versions of Windows. The only thing you have to take care of is you should call it after the window is created.

>
> I'm new to c++ so I don't know much about it, (especially winapi function)
>
Doesn't matter, it's a quite simple function. You can refer to the official documentation to get more info: <https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowrgn>

>
> can you please show me an example
>
Sorry I don't remember the exact code clearly. All I know is it doesn't need much code so it's very easy to achieve. You could be able to achieve it by yourself after some searching.

**Comment by YouKnow-sys** [comment]
thank you for reply, yes I know about qt extension for vs (im using it for a long time)
but seems like I cant compile this project in vs 2019, every time it give me this errors
```
Error	LNK2001	unresolved external symbol "__declspec(dllimport) void __cdecl __flh_ns::FramelessWindowsManager::addWindow(class QWindow *)" (__imp_?addWindow@FramelessWindowsManager@__flh_ns@@YAXPEAVQWindow@@@Z)	mainwindow	G:\Project\framelesshelper-master\examples\mainwindow\mainwindow.obj	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) void __cdecl __flh_ns::FramelessWindowsManager::setHitTestVisibleInChrome(class QWindow *,class QObject *,bool)" (__imp_?setHitTestVisibleInChrome@FramelessWindowsManager@__flh_ns@@YAXPEAVQWindow@@PEAVQObject@@_N@Z)	mainwindow	G:\Project\framelesshelper-master\examples\mainwindow\mainwindow.obj	1	
Error	LNK1120	2 unresolved externals	mainwindow	G:\Project\framelesshelper-master\bin\MainWindow.exe	1	
```
and I don't know what I'm doing wrong, first I'm build the lib (both release and debug and then try to build example for test, but its give me this errors

**Comment by wangwenx190** [comment]
If you are using CMake, please make sure you are building shared library, the CMake project files work fine.

If you are using QMake, maybe I forgot to update pro files, let me check.

**Comment by YouKnow-sys** [comment]
oh, so I cant statically link the project to main?
and one other thing, there is a problem in 
```c++
QPointF getGlobalMousePosition(const QWindow *window)
```
function in utilitie, the compiler say there is no possible conversion from QPointF to const QPoint, so I have to change this function to QPoint

**Comment by wangwenx190** [comment]
>
> so I cant statically link the project to my project?
>
Yes you can but for the demo projects you'll get compilation errors because the library project links to the Qt Quick module but the demo widget project doesn't link to it, so there will be link errors. Shared library doesn't have this issue. If you use it in your own project, either link to the Qt Quick module or remove Qt Quick related files.

>
>  the compiler say there is no possible conversion from QPointF to const QPoint
>
Maybe you are using an old Qt version? I'll update the code to fix it

**Comment by wangwenx190** [comment]
What Qt version are you using? I don't get the QPoint error while building with 5.12

**Comment by YouKnow-sys** [comment]
> What Qt version are you using? I don't get the QPoint error while building with 5.12

im using version 5.15.1

**Comment by wangwenx190** [comment]
I got the same error now. It exists in Qt 5.15 only. QWindow::mapFromGlobal()'s parameter is QPoint in Qt 5 while it's QPointF in Qt 6. I've pushed new code to fix it.

**Comment by wangwenx190** [comment]
Sorry for the inconvenience!

**Comment by YouKnow-sys** [comment]
> If you are using QMake, maybe I forgot to update pro files, let me check.

and one other thing, as you said cmake working without any problem, and I can build both lib and all example with it.
but when I try to use qmake its always give me this error when try to build the examples, looks like its cant find the libary
![image](https://user-images.githubusercontent.com/17937017/126896801-6584f50c-d94c-40ee-98f1-a37c0dd76779.png)

**Comment by wangwenx190** [comment]
>
> looks like its cant find the libary
>
From the picture yes the library can't be found. But for QMake, there's no easy way to specify the library path, I have to hard code the library path:
![图片](https://user-images.githubusercontent.com/17877450/126897034-5f971312-2a3e-4b47-b168-9c06d2c1b908.png)
You can change it to absolute path to avoid this issue. It's located in `examples/common.pri`

**Comment by YouKnow-sys** [comment]
> ```
> Error	LNK2001	unresolved external symbol "__declspec(dllimport) void __cdecl __flh_ns::FramelessWindowsManager::addWindow(class QWindow *)" (__imp_?addWindow@FramelessWindowsManager@__flh_ns@@YAXPEAVQWindow@@@Z)	mainwindow	G:\Project\framelesshelper-master\examples\mainwindow\mainwindow.obj	1	
> Error	LNK2001	unresolved external symbol "__declspec(dllimport) void __cdecl __flh_ns::FramelessWindowsManager::setHitTestVisibleInChrome(class QWindow *,class QObject *,bool)" (__imp_?setHitTestVisibleInChrome@FramelessWindowsManager@__flh_ns@@YAXPEAVQWindow@@PEAVQObject@@_N@Z)	mainwindow	G:\Project\framelesshelper-master\examples\mainwindow\mainwindow.obj	1	
> Error	LNK1120	2 unresolved externals	mainwindow	G:\Project\framelesshelper-master\bin\MainWindow.exe	1	
> ```

I removed all reference to QtQuick from library and then rebuild it statically, but still Im getting the same errors
I also tried to create a full new project (in vs2019) and use library in it, but I still get some errors, I dont know why...

**Comment by YouKnow-sys** [comment]
I manage to make it compile finally, the way I used is I simple removed `FRAMELESSHELPER_API` from code, so its no longer try to import function from dll and instead its using static library
but still there is a problem, I dont know why but after doing this program become very slow, but working as I excepted...

**Comment by wangwenx190** [comment]
Well, I have to say, I don't get all these issues because I mainly use Qt Creator, it looks like Qt doesn't play well with VS. If you want to build it as a static library, you'll have to add `FRAMELESSHELPER_STATIC` to your `DEFINES`, which I already take care of in the project files, so it seems VS may not add it to `DEFINES` as we expected. I guess it can't be fixed smoothly unless I provide a VS solution file.

**Comment by wangwenx190** [comment]
>
> but after doing this program become very slow
>
Strange thing, don't remove that macro, instead, define `FRAMELESSHELPER_STATIC`

**Comment by YouKnow-sys** [comment]
thank you for reply, so what I done now is define `FRAMELESSHELPER_STATIC` in the library, and after that load up example mainwindow project and include all header and library in it (I also define `FRAMELESSHELPER_STATIC` in header itself again) now Im able to build project without any problem, but still its very slow and laggy
the only thing that come in my mind is problem coming from using a static build of qt...

**Comment by wangwenx190** [comment]
I have no idea about the slow and laggy issue because it doesn't happen on my side. You said you are linking against a static version of Qt, that's a case I didn't test. Not sure if it's related to static Qt or not ...

**Comment by YouKnow-sys** [comment]
so im closing there issues...
its going off topic, because my problem with round corner fixed
maybe I open another issues in future

**Comment by wangwenx190** [comment]
>
> because my problem with round corner fixed
>
How did you fix it? Is it the win32 API `SetWindowRgn()`?

**Comment by YouKnow-sys** [comment]
> How did you fix it? Is it the win32 API `SetWindowRgn()`?

yes I used
```c++
HRGN hRegion = ::CreateRoundRectRgn(0, 0, w, h, 12, 12);
SetWindowRgn(hwnd, hRegion, true);
```
after using it, I cant no longer resize window, but hopefully there is some solution to keep resizing (as described [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/6a7091df-991d-43aa-aee5-f44fae3a6490/setwindowrgn-function-and-resize-window?forum=vcgeneral))

btw I Installed Qt6 Dynamic build for VS2019, Im going to test the lib and example project in that too, to make sure what cause the lagging problem, vs or static build
