### ISSUE TITLE
标题栏按钮，实际可点击范围小于按钮大小，有时候出现，点击按钮没有反应的情况，

### ISSUE THREAD

**Issue by Fishguys** [wangwenx190/framelesshelper#63]
![image](https://user-images.githubusercontent.com/20129667/126972180-839f838a-0399-4ba9-9a54-a54e11f50e06.png)
红色区域点击按钮有效

**Comment by wangwenx190** [comment]
代码里把那个区域判断为窗口边框了，所以按钮会不响应鼠标事件。你可以把按钮往下移一点，避开那个区域

**Comment by wangwenx190** [comment]
那个区域的高度是8个像素，下面的标题栏区域高度是23个像素

**Comment by wangwenx190** [comment]
其实我也在纠结要不要这样判断

**Comment by Fishguys** [comment]
QPointF Utilities::mapOriginPointToWindow(const QObject *object)
{
    Q_ASSERT(object);
    if (!object) {
        return {};
    }
    if (!object->isWidgetType() && !object->inherits("QQuickItem")) {
        qWarning() << object << "is not a QWidget or a QQuickItem.";
        return {};
    }
    QPointF point = {object->property("x").toReal(), object->property("y").toReal()};
    if (object->isWidgetType())
    {
         point = ((QWidget*)object)->mapToGlobal(QPoint(0, 0));
    }
    return point;
}

这段判断的代码我改成了这样，没问题了

**Comment by wangwenx190** [comment]
你贴的这个代码有两个问题，第一个是引入了QWidget依赖，既然依赖QWidget就没必要有这个函数了，直接用QWidget提供的mapToGlobal()就可以了。我写这个函数就是为了去除QWidget依赖的。第二个是QQuickItem的坐标判断被去掉了，你这样写的话Qt Quick程序还正常吗

**Comment by Fishguys** [comment]
我目前没有用到Quick，所以暂时没测，那你有什么比较好的解决方案？

**Comment by wangwenx190** [comment]
目前还想不到，你用不到quick的话就那么改吧

**Comment by wangwenx190** [comment]
找到原因了，有个函数签名改了，代码忘记更新了，所以产生了这个问题，已经在前一阵子修复了

**Comment by wangwenx190** [comment]
如果你用不到Qt Quick的话，其实就用不到这个函数了，直接用QWidget自己的mapToGlobal就可以了，还省的麻烦
