### ISSUE TITLE
目前发现另外一个hover问题

### ISSUE THREAD

**Issue by Fishguys** [wangwenx190/framelesshelper#64]
目前在windows10上面发现，程序调整到一定大小，移动程序右下角离屏幕右下角很近的时候，
1、程序右下角的按钮hover效果会消失
2、从程序右下角边框移动鼠标进入程序，鼠标的形状会保持成调整边框的形状一段距离之后才消失

**Comment by Fishguys** [comment]
![image](https://user-images.githubusercontent.com/20129667/127446413-c5341bd2-ffbc-4be1-a057-d2222892b92a.png)
红框进入，按钮无hover效果，往左移动程序一段距离以后，按钮hover效果出现

**Comment by wangwenx190** [comment]
感谢反馈，看来还是坐标的判断有点问题

**Comment by Fishguys** [comment]
![image](https://user-images.githubusercontent.com/20129667/127454861-df688efd-b9f9-473a-948c-1a00a362bf19.png)
我这个demo也是可以复现的，具体是哪个地方呢？我自己改一改看看

**Comment by wangwenx190** [comment]
坐标的判断是在下面这两个地方：

https://github.com/wangwenx190/framelesshelper/blob/c6e5545b4da1dcbf18c76f236f2b558333151db7/framelesshelper_win32.cpp#L496

https://github.com/wangwenx190/framelesshelper/blob/c6e5545b4da1dcbf18c76f236f2b558333151db7/utilities.cpp#L83

肯定是这两者中的某一个出问题了

**Comment by Fishguys** [comment]
应该不是坐标判断的问题，我看了一下，在我上图中的红色区域，*result值确实是HTCLIENT，而且虽然鼠标形状没有改变，但是无法在非边框区域，移动鼠标改变程序界面大小，你github中提供的那个mainwindow DEMO，拖到屏幕右下方，就可以复现这个问题

**Comment by Fishguys** [comment]
![image](https://user-images.githubusercontent.com/20129667/127472169-e0d7aa1c-b26d-44e8-93ee-31c78f3e87fc.png)

**Comment by Fishguys** [comment]
您好，有空能看下这个问题吗？

**Comment by wangwenx190** [comment]
不好意思忘记回复了，现在最新代码还存在这个问题吗

**Comment by wangwenx190** [comment]
长时间没回复，先关闭了，有问题可以再重新打开。
