### ISSUE TITLE
(quick)最大化窗体->最小化->再次打开后没有最大化的效果

### ISSUE THREAD

**Issue by kkwell** [wangwenx190/framelesshelper#66]

**Comment by wangwenx190** [comment]
测了下确实存在这个问题，但问题是最大化/最小化/还原我都是调用的qt本身的接口，我的代码也并没有干涉这方面的行为，暂时不知道为什么会这样

**Comment by kkwell** [comment]
估计是qt的bug,不过也不影响使用

**Comment by camgaertner** [comment]
This should be solved from #35 . Qt bug for reference: https://bugreports.qt.io/browse/QTBUG-69711

**Comment by wangwenx190** [comment]
@camgaertner is right, this issue is now fixed by the commit a9256ba4b3b77ae4a505a1dae19affbd637bd596 . I'm closing this ticket, feel free to reopen it if you find any related issues.
