### ISSUE TITLE
高分屏 (4K) 下 resize 的边缘坐标计算获取错误

### ISSUE THREAD

**Issue by altairwei** [wangwenx190/framelesshelper#68]
![20210812190713](https://user-images.githubusercontent.com/30854075/129187216-8c4a1584-40cf-4c09-b782-661910ad192e.jpg)

注意红色箭头所指的地方，resize 指示器的位置出现在正中心，导致程序无法正常使用。resize 时的鼠标坐标获取应该出现了错误。

**Comment by altairwei** [comment]
错误发生在：

```C++
QPointF Utilities::getGlobalMousePosition(const QWindow *window)
{
    if (window) {
        return QPointF(QCursor::pos(window->screen())) * window->devicePixelRatio();
    } else {
        return QPointF(QCursor::pos()) * QGuiApplication::primaryScreen()->devicePixelRatio();
    }
}
```

使用 `screen()` 获取窗口位置信息在设置了 `Qt::AA_EnableHighDpiScaling` 的程序中应该是 DPI awareness 的，所以不需要再乘以 `devicePixelRatio` 了。

**Comment by wangwenx190** [comment]
X11和Wayland表现一样吗

**Comment by altairwei** [comment]
> X11和Wayland表现一样吗

我用的 deepin 20 ，应该不是 wayland

**Comment by Fishguys** [comment]
双屏下，不同dpi，这个问题windows10下可以复现，这给地方的鼠标位置计算，我直接用了windows的：
 case WM_NCHITTEST:

	//POINT point;
	//GetCursorPos(&point); // 获取鼠标指针位置（屏幕坐标）
	//POINT winLocalMouse = {qRound(globalMouse.x()), qRound(globalMouse.y())};
	POINT winLocalMouse;
	//用windows获去鼠标位置，避免多屏不同分辨率，缩放倍率不同的时候，鼠标位置计算错误
	GetCursorPos(&winLocalMouse);
        ScreenToClient(msg->hwnd, &winLocalMouse);

**Comment by wangwenx190** [comment]
> 
> 
> 双屏下，不同dpi，这个问题windows10下可以复现，这给地方的鼠标位置计算，我直接用了windows的：
> case WM_NCHITTEST:
> 
> ```
> //POINT point;
> //GetCursorPos(&point); // 获取鼠标指针位置（屏幕坐标）
> //POINT winLocalMouse = {qRound(globalMouse.x()), qRound(globalMouse.y())};
> POINT winLocalMouse;
> //用windows获去鼠标位置，避免多屏不同分辨率，缩放倍率不同的时候，鼠标位置计算错误
> GetCursorPos(&winLocalMouse);
>     ScreenToClient(msg->hwnd, &winLocalMouse);
> ```

我原本就是这样获取鼠标位置的，但之前有人反馈这个位置在多显示器的情况下会不准，所以才改用Qt的函数了，怎么你这里正好和我之前收到的反馈是反着来的

**Comment by wangwenx190** [comment]
523e35fdb1498c3c52a1b241bb009239b43407b4 应该解决了这个问题，先close了，有问题再重新open
