### ISSUE TITLE
Ignore algorithm doesn't ignore areas in the resizing borders region.

### ISSUE THREAD

**Issue by shujaatak** [wangwenx190/framelesshelper#7]
I tested the updated code and it works great but I found that resizing borders are not included in the ignore areas.
Suppose you place a button in the top-right corner just like a normal win32 app's close button, you would notice that resizing borders do not allow you to interact with a part of a button which is below the resizing borders area. A user may need such a button anywhere near the borders so, I think, the resizing borders should also be included in the ignore areas calculations.

**Comment by wangwenx190** [comment]
Yes, you are right. Thanks for telling me this. I'll fix it right now.

**Comment by wangwenx190** [comment]
Master branch updated. Can you test the latest code? Should be fixed now. You can reopen this issue if it's not fixed.
