### ISSUE TITLE
Linux 下双击 titlebar 无法正常将窗口最大化

### ISSUE THREAD

**Issue by altairwei** [wangwenx190/framelesshelper#72]
双击 titlebar 后依次激发了如下事件：

```
QEvent::MouseButtonPress
startSystemMove() 
QEvent::MouseButtonPress
startSystemMove()
QEvent::MouseButtonDblClick
```

看起来应该是 `startSystemMove()` 将 `MouseButtonDblClick` 的反应打断了。

**Comment by wangwenx190** [comment]
看来得处理下

**Comment by altairwei** [comment]
我试了下监听 `QEvent::MouseMove` 然后通过 `QMouseEvent::buttons()` 来判断是否点击了左键，然后再调用 `startSystemMove() ` 。不过这个会引起新的问题，点击拖动最小化、最大化、关闭按钮也能拖动窗体。

**Comment by wangwenx190** [comment]
看来还得研究下

**Comment by altairwei** [comment]
我仔细测试了下，只要点击最小化、最大化、关闭按钮时，鼠标不移动超过这些按钮区域，就不会拖动窗口。不过我的这种实现，与桌面系统的原生行为还是有点不同。

**Comment by altairwei** [comment]
另一个思路是，framelesshelper 不处理双击事件。这个东西很简单，让用户自己来实现就行了。

**Comment by altairwei** [comment]
> 另一个思路是，framelesshelper 不处理双击事件。这个东西很简单，让用户自己来实现就行了。

不过问题似乎也存在，比较双击事件始终发生在两个单击事件之后

**Comment by wangwenx190** [comment]
> 
> 
> 双击 titlebar 后依次激发了如下事件：
> 
> ```
> QEvent::MouseButtonPress
> startSystemMove() 
> QEvent::MouseButtonPress
> startSystemMove()
> QEvent::MouseButtonDblClick
> ```
> 
> 看起来应该是 `startSystemMove()` 将 `MouseButtonDblClick` 的反应打断了。

我在想，是不是优先判断双击事件就解决了

**Comment by wangwenx190** [comment]
> 
> 
> 另一个思路是，framelesshelper 不处理双击事件。这个东西很简单，让用户自己来实现就行了。

这个不太合适，明显是该有的功能，不能让反而让用户来补充

**Comment by altairwei** [comment]
> 我在想，是不是优先判断双击事件就解决了

我试过了，不行。毕竟 eventFilter 是每次接收一个事件，代码的顺序无所谓。

**Comment by wangwenx190** [comment]
> 
> 
> > 我在想，是不是优先判断双击事件就解决了
> 
> 我试过了，不行。毕竟 eventFilter 是每次接收一个事件，代码的顺序无所谓。

那或者搞个变量作为标识？
