### ISSUE TITLE
startSystemMove 或者 startSystemResize 之后整个窗口接收不到事件

### ISSUE THREAD

**Issue by altairwei** [wangwenx190/framelesshelper#75]
如题，在 move 和 resize 事件发生后，整个窗口接收不到事件。其中 hover 事件最明显，窗口完全无法对 hovor 做出反应。

只有当鼠标再次点击窗口的任何区域后，才能恢复正常。

**Comment by wangwenx190** [comment]
这个待调查，win平台我测过是没这个问题的

**Comment by altairwei** [comment]
要是这个问题解决了，Linux 端我感觉几乎就完美了。

**Comment by wangwenx190** [comment]
目前还不清楚是什么导致的

**Comment by altairwei** [comment]
这个问题可能是因为 Qt 没有收到 ButtonRelease 的事件导，所以认为鼠标还在 Press 状态。有空我试试用 X11 在 startSystemMove 和 startSystemResize 之前发送一个 ButtonRelease 。

**Comment by wangwenx190** [comment]
这个问题还存在吗？解决了的话就close吧

**Comment by altairwei** [comment]
`altairwei/2.0` 已重头实现 Linux 端无边框，所以此问题不存在了。
