### ISSUE TITLE
有没有办法捕获标题栏的enter和leave事件？ 

### ISSUE THREAD

**Issue by ZhouYing-bit** [wangwenx190/framelesshelper#78]
我重写了事件过滤器 eventFilter 方法， 发现当鼠标在标题栏上移动时只有 QEvent::NonClientAreaMouseMove 事件触发，我现在有一个需求是，当鼠标进入和离开标题栏时要触发一些操作，可以提供一些思路吗

**Comment by wangwenx190** [comment]
Windows平台的话无边框窗口已经没有非客户区了，在evenfilter中监听MouseMove消息就行，只要鼠标的y坐标在标题栏高度内就是位于标题栏区域，反之就是在标题栏区域外

**Comment by wangwenx190** [comment]
如果要判断是进入还是离开，可以用一个变量作为标志，判断下

**Comment by ZhouYing-bit** [comment]
![image](https://user-images.githubusercontent.com/13702789/130307464-4d5596ef-6120-4305-86fa-a0511b514dad.png)
标题栏里面只有 QEvent::NonClientAreaMouseMove 这一个事件

**Comment by wangwenx190** [comment]
用它也一样，你试着输出一下进入事件时的鼠标位置，看看坐标系是窗口还是屏幕，然后根据坐标判断是否进出了标题栏区域

**Comment by ZhouYing-bit** [comment]
明白了，感谢你的指导；
