### ISSUE TITLE
请问为什么源码中继承QWidget的类改成继承QDialog靠边放大的功能就失效了，新手看不太懂源代码，咨询一些设计如此还是bug

### ISSUE THREAD

**Issue by ZhangHuanSir** [wangwenx190/framelesshelper#83]

**Comment by wangwenx190** [comment]
可能是QDialog和QWidget的大小策略不同导致的。为什么要继承自QDialog呢，QWidget有哪里不能满足你的需求吗？

**Comment by ZhangHuanSir** [comment]
理论上QDialg能做的QWidget都能做，但是项目中有好多弹出窗口都是QDialg，exec后获取QDialg的退出方式，这些方式QWidget没有，虽然这个无边框做的已经很完美了，但是如果QDialg也能想QWidget那样方便就更好了

**Comment by ZhangHuanSir** [comment]
顺便请问一下，展示图片里那几个亚克力效果怎么实现的，是开源的吗？

**Comment by wangwenx190** [comment]
> 理论上QDialg能做的QWidget都能做，但是项目中有好多弹出窗口都是QDialg，exec后获取QDialg的退出方式，这些方式QWidget没有，虽然这个无边框做的已经很完美了，但是如果QDialg也能想QWidget那样方便就更好了

QDialog确实有一些兼容性问题，原因暂时不知道，等我抽空看看Qt的源码研究一下

> 顺便请问一下，展示图片里那几个亚克力效果怎么实现的，是开源的吗？

图片里的亚克力跟Qt没什么关系，是完全用win32 api做的，具体可以看看 https://github.com/wangwenx190/Win32Acrylic

以前我曾经搞过一个qt模拟的亚克力，不过效果不太好，就没开源，上面开源的那个算效果不错的

**Comment by wangwenx190** [comment]
请使用FramelessDialog
