### ISSUE TITLE
Windows 11 error

### ISSUE THREAD

**Issue by mirroI** [wangwenx190/framelesshelper#88]
Hello! I have been using your library for a long time, but when upgrading to the latest version I encountered a build error. I use CMake 3.21.4, Windows 11, Qt 6.2.1 (Quick)

C:\Users\Alexe\Documents\framelesshelper-1.x\framelesshelper_windows.h:54: ошибка: pasting ")" and "0000" does not give a valid preprocessing token
..\framelesshelper-1.x\framelesshelper_windows.h:54:37: error: pasting ")" and "0000" does not give a valid preprocessing token
 #define NTDDI_WIN10_19H1 (0x0A000007)
                                     ^

**Comment by wangwenx190** [comment]
Thanks for your feedback! Can you verify whether bb7ab2e fixed this issue or not?
