### ISSUE TITLE
由全屏状态 到 最大化状态 变迁的过程会出现一个本地的小窗口，然后迅速消失

### ISSUE THREAD

**Issue by ZhouYing-bit** [wangwenx190/framelesshelper#90]

**Comment by ZhouYing-bit** [comment]
![image](https://user-images.githubusercontent.com/13702789/145803647-5d28d0ac-9623-4994-952a-593c9eb4fcdb.png)

我将关闭按钮用于切换全屏， 主窗口从全屏状态 到 最大化状态会闪烁；

**Comment by wangwenx190** [comment]
好的，我验证一下。不过感觉跟这个项目没什么关系，全屏状态比较特殊，直接在全屏与其他状态之间切换应该会有点问题，应该是QPA中的代码导致的，待验证。

**Comment by ZhouYing-bit** [comment]
好的 感谢，其实这个需求是真实存在的，比如使用播放器播放视频时， 如果用户在窗口最大化状态进入全屏模式，那么在退出全屏模式时，用户肯定期望回到刚才的最大化状态，而不是normal状态。

PotPlayer和Vlc等其它几个主流播放器都是这样实现

**Comment by ZhouYing-bit** [comment]
> 好的，我验证一下。不过感觉跟这个项目没什么关系，全屏状态比较特殊，直接在全屏与其他状态之间切换应该会有点问题，应该是QPA中的代码导致的，待验证。

好的，感谢；

其实这个需求是真实存在的，在播放器中基本都这样设计，比如用户在最大化状态观看视频，点击全屏按钮进入全屏模式，当退出全屏时，用户应该是期望回到刚才的最大化状态；  我调研了vlc、potplayer等几个主流播放器都是这样设计的，所以这应该是个合理的需求。

**Comment by altairwei** [comment]
你能录一个视频展示一下这个问题吗？

**Comment by ZhouYing-bit** [comment]
@altairwei 

![image](https://user-images.githubusercontent.com/13702789/147341269-d9dcabfa-5c3f-4a16-87b5-1e97e29d1133.png)

将examples\widget\widget.cpp中的m_closeButton按钮点击槽函数修改成图中那样，然后来回点击关闭按钮就能复现问题。

**Comment by wangwenx190** [comment]
我试了下，确实有这个现象，不过这个问题不是我这个项目导致的。那个瞬间出现的窗口是窗口先被还原到normal状态了，然后紧接着又切换到最大化了。我用Qt Quick那个例子试了下，发现有相同的现象。我估计可能是Qt没法直接在最大化与全屏之间切换，在退出全屏状态时，Qt只能先还原到normal状态。而且在从全屏状态退出后，有一瞬间能看到原本的窗口边框，这个问题是窗口在全屏状态间切换时Qt内部修改了窗口样式导致的，暂时没法解决，不修改窗口样式就不会出现原本的边框。

**Comment by wangwenx190** [comment]
不是这个项目导致的问题，而且从我这边也没法解决这个问题，如果你想解决这个问题，要自己去修改QPA的相关源码，自己编译一份修改版的Qt

**Comment by ZhouYing-bit** [comment]
@wangwenx190 好的，明白了，感谢回复。

**Comment by yuanqi-pythoner** [comment]
我也遇到了同样的问题，并且我还是用的windows原生的标题栏

**Comment by wangwenx190** [comment]
> 我也遇到了同样的问题，并且我还是用的windows原生的标题栏

Qt自己的问题，跟我这个项目没有关系。Qt退出全屏后会先还原到normal状态，然后再恢复到全屏前的状态，所以能看到窗口切换的过程。
