### ISSUE TITLE
Quick example not working as expected on Windows

### ISSUE THREAD

**Issue by rupertdaniel** [wangwenx190/framelesshelper#91]
I'm trying out the Quick example and for some reason on my Windows 10 laptop framelesshelper does not seem to work correctly. The qt window content is still offset from the original title bar. See attached screenshot.

What's strange is that it works as expected on other Windows 10 devices I've tried.

Do you have any ideas what could be going wrong?

<img width="1037" alt="Screenshot 2021-12-15 at 12 46 25" src="https://user-images.githubusercontent.com/237035/146191224-ed0e3295-b96f-4dca-bb92-cc378c3fa45b.png">

**Comment by altairwei** [comment]
Are you using Intel(R) HD Graphics? Try to upgrade it's drivers.

**Comment by wangwenx190** [comment]
@rupertdaniel It's a known bug of OpenGL. I see you are using Qt 5.15, you can change the RHI backend to D3D11, which can fix this issue. Qt RHI is introduced in Qt 5.14. Let me know if changing RHI backend doesn't help. And upgrade graphic driver may also help, but I'm not sure.

**Comment by rupertdaniel** [comment]
@wangwenx190 thanks for the reply and the information. 

Yes my laptop is using an Intel HD Graphics device. I tried upgrading to the latest drivers, but it is still broken.

However I tried enabled the RHI D3D11 backend and that does seem to fix it. I'll investigate some more to see if we can use the RHI backend in our app.

**Comment by wangwenx190** [comment]
It's a bug of the graphics driver, not Qt's bug or FramelessHelper's bug, so I really can't do much about it. For Qt Quick applications, the only way to solve this is to switch the RHI backend to something not OpenGL, such as D3D11 and Vulkan. If you have dual graphics cards, you can try switching to the other one to see if it helps. Upgrading the graphics driver can sometimes fix this issue, but not always. If you are running your application on Windows 7, you can try switch your system theme to "Basic" to fix this.
