### ISSUE TITLE
Issues with mouse tracking when dismissing a popup by clicking on the top bar

### ISSUE THREAD

**Issue by JulienMaille** [wangwenx190/framelesshelper#92]
I noticed a weird behavior of the mouse after a certain sequence happens.
You will see in the movie that buttons hovering is broken, but there's more issues when opening menus for instance.

Here is how to reproduce it.
- Unfold a widget like a combo box, a toolmenu or a QMenu
- Click in the title bar (but not in a section that has been processed by `FramelessWindowsManager::setHitTestVisible()`
- Now the mouse tracking is broken

It can be fixed by reopening the widget and clicking somewhere else, or my dragging the window or even by clicking outside the window.
![frameless2](https://user-images.githubusercontent.com/182520/146548350-07733a73-7ddb-4e48-aca6-f17a579abb23.gif)

It seems something is happening in `FramelessHelperWin::nativeEventFilter()`

**Comment by altairwei** [comment]
I can reproduce this BUG in Win10. I guess that any widget (such as QMenu, QComboBox) that pops up through `exec()` will cause this BUG. It seems like `nativeEventFilter()` can't handle quitting of event loops of these widgets.

**Comment by JulienMaille** [comment]
@altairwei where would you advise me to look? Which message type might be at fault?

**Comment by altairwei** [comment]
> where would you advise me to look? Which message type might be at fault?

Sorry, I don't have any ideas at the moment.

**Comment by JulienMaille** [comment]
Returnin false in `case WM_NCHITTEST:` removes the bug

**Comment by JulienMaille** [comment]
@altairwei It seems I can't reproduce the bug if the window is maximized, do you confirm?

**Comment by JulienMaille** [comment]
Could this help?
https://github.com/lambdaxymox/wine/commit/cfcc280905b7804efde8f42bcd6bddbe5ebd8cad

**Comment by altairwei** [comment]
This patch #93 worked, thanks a lot!

**Comment by JulienMaille** [comment]
@altairwei I'm sorry I already asked this question and can't find the answer: can you remind me what's the purpose of your `2.0` branch? Are there bugfixes that I should cherry pick in my form of `1.0`. Should I work with branch `2.0`? Thanks a lot.

**Comment by altairwei** [comment]
@JulienMaille The purpose of `2.0` has been explained in https://github.com/wangwenx190/framelesshelper/issues/86#issuecomment-934139020 . The implementation of `2.0` on Windows is similar to that of `1.0`, but `2.0` has some minor refactoring to fit the new API design. Cherry-picking directly would have been a bit tricky, as I had removed or moved some of the code elsewhere.

The initial work on `2.0` is now complete and I have applied it to the [WizNotePlus](https://github.com/altairwei/WizNotePlus) project. If you are interested, try out the `altairwei/2.0` branch and decide if you want to work on it.

**Comment by JulienMaille** [comment]
Thanks and sorry for asking twice, totally forgot about your other reply

**Comment by altairwei** [comment]
> Thanks and sorry for asking twice, totally forgot about your other reply. Is this commit in 1.0? [1f1de5d](https://github.com/wangwenx190/framelesshelper/commit/1f1de5deb67ccab73749c4af6ed433f9fe4e8626)

I'm not sure. This BUG is caused by `Utilities::getSystemMetric`. @wangwenx190 forgot to fix function calls when change it's function signature.

By the way, `altairwei/2.0` branch is serveral commits behind `1.x`

**Comment by wangwenx190** [comment]
@JulienMaille  Nothing need to be cherry-picked back to the 1.x branch. For Windows, 2.0 is only a redesign and reorganization of the project, the core code doesn't change. The main goal of 2.0 is to provide complete support for Linux and macOS without relying on Qt 5.15's QWindow API, which is not related to Windows.

> This BUG is caused by Utilities::getSystemMetric. @wangwenx190 forgot to fix function calls when change it's function signature.

@altairwei  这个问题现在还存在吗

**Comment by altairwei** [comment]
> 这个问题现在还存在吗

That BUG #77 has been fixed in `altairwei/2.0`, but I'm not sure if it has also been fixed in `1.x`

**Comment by wangwenx190** [comment]
> Thanks and sorry for asking twice, totally forgot about your other reply. Is this commit in 1.0? [1f1de5d](https://github.com/wangwenx190/framelesshelper/commit/1f1de5deb67ccab73749c4af6ed433f9fe4e8626)

@JulienMaille The issue you mentioned is now fixed in the 1.x branch. Sorry for the inconvenience.
