### ISSUE TITLE
<timeapi.h> 头文件找不到

### ISSUE THREAD

**Issue by ZhangHuanSir** [wangwenx190/framelesshelper#94]
mingw 编译会报错 <timeapi.h> 头文件找不到，请问您那里有这个问题吗？

**Comment by ZhangHuanSir** [comment]
我看了一下和前几点的改动有关系，这个头文件是在windows sdk里面的，mingw可能无法使用

**Comment by wangwenx190** [comment]
你mingw什么版本？可能是头文件太老了

临时解决方案：把下面这个if分支里所有的内容都去掉，然后去掉`#include <timeapi.h>`

https://github.com/wangwenx190/framelesshelper/blob/c3c5ef0d5dd0c2598dff2ea702e275e57a3e4599/framelesshelper_win32.cpp#L379

过会我更新下代码，去除对这个头文件的依赖

**Comment by ZhangHuanSir** [comment]
谢谢您，我看了一下 Qt 5.15.2 自带的mingw是 8.1.0 ，没有这个头文件，也就是说 Qt 5.15.2 以下版本比8.1.0还低，我试过 Qt5.9.7和5.12.12 都不行。

**Comment by wangwenx190** [comment]
代码更新了，试试最新代码呢

**Comment by wangwenx190** [comment]
8.1.0已经是几年前的版本了，最新版是11.2.0，Qt 6.2 才带，不过mingw的头文件向来都比较老，可能最新版也不怎么行

**Comment by ZhangHuanSir** [comment]
嗯现在 Qt5.15 版本没问题了，但是还是有个小遗憾 <qwinregistry_p.h> 这个头文件可能是 Qt 5.14 以后才有的，可能需要限定以下版本了，要不会报这个头文件找不到

**Comment by wangwenx190** [comment]
> 嗯现在 Qt5.15 版本没问题了，但是还是有个小遗憾 <qwinregistry_p.h> 这个头文件可能是 Qt 5.14 以后才有的，可能需要限定以下版本了，要不会报这个头文件找不到

那我得改一下了，不用限定Qt版本，可以改成使用win32 API或者再改回使用QSettings

**Comment by wangwenx190** [comment]
我刚才查了下，你提供的信息有误，`qsystemlibrary_p.h`很早就有了，至少5.6版本里就有。

**Comment by ZhangHuanSir** [comment]
报错的是 <qwinregistry_p.h> 不是 <qsystemlibrary_p.h> 在我这显示这个头文件 Qt 5.12.12 还没有 Qt 5.14.2 以上就有了,我电脑上没有 Qt 5.13，所以不清楚 5.13 是否正常。

**Comment by ZhangHuanSir** [comment]
我把 utilities_win32.cpp 恢复上一个版本了就可以编译过了，运行也正常，不知道会不会出什么问题

**Comment by wangwenx190** [comment]
是我搞错了，`qwinregistry_p.h`是5.14.0才引入的，最新代码已修改。试试能不能在5.12上编译

> 我把 utilities_win32.cpp 恢复上一个版本了就可以编译过了，运行也正常，不知道会不会出什么问题

没什么问题，不过最新代码应该没问题了，试试看

**Comment by JulienMaille** [comment]
I think that with your latest code, some headers are now missing when compiling with msvc 2019

**Comment by wangwenx190** [comment]
> I think that with your latest code, some headers are now missing when compiling with msvc 2019
> 
> ```
> 1>\FramelessHelper\framelesshelper_win32.cpp(389,34): error C2061: syntax error: identifier 'MMRESULT'
> ```

Really sorry for that. I'm using MSVC 2022 and everything works fine, I don't know it will break MSVC 2019 builds. But it's also very easy to fix, I'll upload new code right away.

**Comment by wangwenx190** [comment]
@JulienMaille  Can you check whether commit 7ddde978e84c5ec0f3fb3e1ab8ac2d74db140094 fixed the build error or not?

**Comment by JulienMaille** [comment]
Yes it works. Thanks a lot!

**Comment by ZhangHuanSir** [comment]
![image](https://user-images.githubusercontent.com/47553361/148480752-035e0bd5-28ba-4f99-bbe8-0c58fbb2eda7.png)
低版本 Qt 编译还是存在问题，我试了 Qt 5.12 还是编译不过的

**Comment by wangwenx190** [comment]
> 低版本 Qt 编译还是存在问题，我试了 Qt 5.12 还是编译不过的

知道了，这个宏也是后期才引入的，代码本身没问题。我把宏替换一下就好了

**Comment by wangwenx190** [comment]
@ZhangHuanSir 最新的代码没问题了，我亲自测了，5.9都能编译

**Comment by ZhangHuanSir** [comment]
还个小瑕疵就是在Qt5.9 mingw 编译器没有对 std::exchange 函数的定义和实现，我直接把代码复制出来了，然后能编译过了
![1641545355(1)](https://user-images.githubusercontent.com/47553361/148517865-28db3a69-0dc4-4094-aabb-439f468d73d4.png)
