### ISSUE TITLE
4k屏幕分辨率下运行示例程序（ 右边框和下边框 ）显示不正确

### ISSUE THREAD

**Issue by ZhangHuanSir** [wangwenx190/framelesshelper#95]
<img width="663" alt="5aa489714fcf87bcf3263e3b8e594ad" src="https://user-images.githubusercontent.com/47553361/148232927-c3f60aa7-b5a8-494c-9878-89c80499b1bb.png">
<img width="617" alt="3b27de71616b457f5112cbb2e7827d7" src="https://user-images.githubusercontent.com/47553361/148232938-d5764bd3-4e77-40ec-80fd-0ab415f1970c.png">
<img width="566" alt="9e3a210df95f9172b67e19e35b370ca" src="https://user-images.githubusercontent.com/47553361/148232957-a60ca104-aa2f-4bb7-9c5a-58337674d84e.png">

**Comment by ZhangHuanSir** [comment]
但是在我自己的程序上没能复现这个现象
![image](https://user-images.githubusercontent.com/47553361/148233424-9fe5f76d-8f31-45dc-ba67-769aaa01d6c8.png)

**Comment by JulienMaille** [comment]
Intersting I think I saw the same problem on a Surface laptop (high dpi screen). It seems like an odd/even pixel width problem in my case.

**Comment by JulienMaille** [comment]
Do you repaint the border in your program?
Bug must lies in there:
https://github.com/wangwenx190/framelesshelper/blob/fc307c83bf394fc27cff4e4179ac6e156fd1fadf/examples/mainwindow/mainwindow.cpp#L133-L146

**Comment by wangwenx190** [comment]
@ZhangHuanSir @JulienMaille This is a bug of Qt itself, not this repo. The fix is easy, just let Qt always round the scale factor. Use `QGuiApplication::setHighDpiScalingScaleFactorRoundPolicy()` (since Qt 5.14) to do this. Before 5.14, the scale factor is always rounded, so this bug won't appear.

**Comment by wangwenx190** [comment]
Or disable antialias of QPainter

**Comment by wangwenx190** [comment]
The latest code has fixed this issue, but you should know it's not caused by FramelessHelper, you should fix your own code instead.

**Comment by JulienMaille** [comment]
> @ZhangHuanSir @JulienMaille This is a bug of Qt itself, not this repo.

Do you know if this has been fixed in Qt6?

**Comment by JulienMaille** [comment]
I found:
https://github.com/qt/qtbase/commit/dafe9e23638c4fe272044fae91380a225e19193a
https://github.com/qt/qtbase/commit/46039092bdabcea76f5899b492e3429d6b571bfa

**Comment by wangwenx190** [comment]
> > @ZhangHuanSir @JulienMaille This is a bug of Qt itself, not this repo.
> 
> Do you know if this has been fixed in Qt6?

No it's still not fixed, the latest dev branch.

> I found: [qt/qtbase@dafe9e2](https://github.com/qt/qtbase/commit/dafe9e23638c4fe272044fae91380a225e19193a) [qt/qtbase@4603909](https://github.com/qt/qtbase/commit/46039092bdabcea76f5899b492e3429d6b571bfa)

Maybe they are not related to this issue. The issue we are talking about here is a painting bug, Qt miscalculated the coordinate/geometry due to the rounding error when high dpi scaling is enabled and the scale factor is not integer. The issue probably not in the platform plugin. I guess it's somewhere in QtGui.

**Comment by JulienMaille** [comment]
I think this black line is the one drawn here:
https://github.com/wangwenx190/framelesshelper/blob/fc307c83bf394fc27cff4e4179ac6e156fd1fadf/examples/mainwindow/mainwindow.cpp#L133-L146

**Comment by wangwenx190** [comment]
From the snapshot it looks like you are running your application on Windows 11. We should not paint any frame border on Win11 because it seems the OS will always draw one for us, and our self-painted frame border won't be seen as well. Maybe we should special-case for Win11. I'll modify the example code to do this.

**Comment by wangwenx190** [comment]
Please try the latest commit e85e3f891e84cc7e708e3b0163c95e0a9788cf4b

**Comment by JulienMaille** [comment]
I has done something similar and planned to PR it. I will test your code and report.
One additional question; you said either add DPI scale rounding *or* remove painter anti-aliasing. But you did both, why?

**Comment by wangwenx190** [comment]
> One additional question; you said either add DPI scale rounding or remove painter anti-aliasing. But you did both, why?

The two solutions won't conflict with each other. The issue may disappear if you apply one of the two solutions, I applied both just to be extra safe, but it may not be necessary. If let Qt round the scale factor solves the issue, then you don't need to disable antialiasing of QPainter, and vice versa.

**Comment by JulienMaille** [comment]
@ZhangHuanSir can you try with just the antialising fix? My high dpi pc is running win11 so I cannot test myself.

**Comment by wangwenx190** [comment]
Currently I'm testing it on Win10 with 125% scale. Only disable antialising of QPainter can fix this issue as well, but from the appearance it looks like applying both solutions can give you the most perfect result.

**Comment by ZhangHuanSir** [comment]
I tested it with 4K monitor yesterday, but there was something wrong with the code compilation yesterday. What I used was not the complete code. I will test the new program later today and report it

**Comment by wangwenx190** [comment]
Let's make it short: so far, it looks like applying both solutions can give the best appearance, only round the scale factor without disabling antialising can fix this issue mostly as well, only disabling antialising but not round the scale factor can only fix the issue **in some degree**

**Comment by ZhangHuanSir** [comment]
昨天的代码里已经禁用了抗锯齿了，但是似乎并不能解决问题，我今晚一会儿用新的代码在4k显示器上再测试一下。

**Comment by wangwenx190** [comment]
It seems QPainter's rounding policy will also be affected QGuiApplication's rounding policy, so we'd better keep them sync with each other, both round or both pass through.

**Comment by wangwenx190** [comment]
> 昨天的代码里已经禁用了抗锯齿了，但是似乎并不能解决问题，我今晚一会儿用新的代码在4k显示器上再测试一下。

只禁用抗锯齿不够，还要修改Qt本身的缩放策略。两者同时修改，效果最好

**Comment by wangwenx190** [comment]
@JulienMaille Does the latest code running well on Win11?

**Comment by JulienMaille** [comment]
yes

**Comment by ZhangHuanSir** [comment]
我测试了最新的代码，在 win10 系统下 Qt 5.12.12 版本 msvc 和 Qt 5.14.1 版本 mingw 环境下运行示例程序， 边框还是显示不正确。
![ca436bc4a99f972bb6352678cebc214](https://user-images.githubusercontent.com/47553361/148545573-a4ef7364-b460-4f65-9545-0d816662c699.png)

**Comment by ZhangHuanSir** [comment]
由于家里这台电脑只装了 Qt 5.12 所以并没有测试更高的 Qt 版本

**Comment by wangwenx190** [comment]
跟Qt版本关系不大，把代码里那几个“-1”都去掉试试呢

**Comment by wangwenx190** [comment]
![图片](https://user-images.githubusercontent.com/17877450/148546029-5bdf7c62-c0e5-485b-8e64-15a82bb2d50c.png)
这几个-1都去掉试试

**Comment by ZhangHuanSir** [comment]
![image](https://user-images.githubusercontent.com/47553361/148546153-0e2d29b8-b4d4-40fc-9d83-20b05faf4b2b.png)
去掉之后调整窗口大小有时会出现没有边框的情况，Qt 5.12.12

**Comment by wangwenx190** [comment]
有边框的时候，外观有改善吗

**Comment by ZhangHuanSir** [comment]
有边框时候是正确的，没问题

**Comment by wangwenx190** [comment]
-1能确保边框不会消失，但缺点是会有一定空隙，不-1就没空隙了，但调整大小时经常会导致自绘的边框线消失，这个是Qt的bug

**Comment by ZhangHuanSir** [comment]
-1的时候感觉明明1px的边框，Qt 给绘制成了 2px

**Comment by JulienMaille** [comment]
Should the thickness be multiplied by the dpi scale?

**Comment by wangwenx190** [comment]
> Should the thickness be multiplied by the dpi scale?

I haven't tried it yet

**Comment by wangwenx190** [comment]
边框线是要根据DPI缩放的，200%下标准Win32窗口的边框线不是1px，我看过了

**Comment by ZhangHuanSir** [comment]
![image](https://user-images.githubusercontent.com/47553361/148551337-ef9c62c5-593b-4945-ba17-8ff65fd4e86f.png)
我在4k屏幕上测试200%缩放，资源管理器窗口边框实际上还是1px的

**Comment by wangwenx190** [comment]
如果是这样的话，在绘制边框线时只需要除以缩放倍数就可以了，那个-1的地方考虑的也不够周到，其实应该减边框线的实际宽度

**Comment by wangwenx190** [comment]
> Should the thickness be multiplied by the dpi scale?

New code uploaded. I hope commit e0c00bce35ea1c4fe3aca9945870321e5934ea64 can fix this issue.
