### ISSUE TITLE
Linux下MainWindow，Widget,在使用了startSystemMove，startSystemResize后Qt会收不到鼠标抬起的事件导致需要点击一次鼠标才能恢复正常

### ISSUE THREAD

**Issue by graycatya** [wangwenx190/framelesshelper#96]
地址:[https://gitee.com/graycatya/CatLearnQt/tree/graycatya/GrayFramelesshelper](https://gitee.com/graycatya/CatLearnQt/tree/graycatya/GrayFramelesshelper)

解决方案:
在FramelessHelper中添加m_bLinuxWindowClicked是否启用了移动，和改变大小，并执行Utilities::X11ButtonRelease

bool FramelessHelper::eventFilter(QObject *object, QEvent *event)
{
    Q_ASSERT(object);
    Q_ASSERT(event);
    if (!object || !event) {
        return false;
    }

    // Only monitor window events.
    if (!object->isWindowType()) {
        return false;
    }
    const QEvent::Type type = event->type();
    const auto window = qobject_cast<QWindow *>(object);
#ifdef Q_OS_LINUX

        if(m_bLinuxWindowClicked)
        {
            m_bLinuxWindowClicked = false;
            Utilities::X11ButtonRelease(window->winId(), QPoint(0,0), QPoint(0,0));
            return false;
        }

#endif
    // We are only interested in mouse events.
    if ((type != QEvent::MouseButtonDblClick) && (type != QEvent::MouseButtonPress)
            && (type != QEvent::MouseMove)) {
        return false;
    }
    const int resizeBorderThickness = FramelessWindowsManager::getResizeBorderThickness(window);
    const int titleBarHeight = FramelessWindowsManager::getTitleBarHeight(window);
    const bool resizable = FramelessWindowsManager::getResizable(window);
    const int windowWidth = window->width();
    const auto mouseEvent = static_cast<QMouseEvent *>(event);
#if (QT_VERSION >= QT_VERSION_CHECK(6, 0, 0))
    const QPoint localMousePosition = mouseEvent->position().toPoint();
#else
    const QPoint localMousePosition = mouseEvent->windowPos().toPoint();
#endif
    const Qt::Edges edges = [window, resizeBorderThickness, windowWidth, &localMousePosition, this] {
        const int windowHeight = window->height();
        if (localMousePosition.y() <= resizeBorderThickness) {
            if (localMousePosition.x() <= resizeBorderThickness) {
                return Qt::TopEdge | Qt::LeftEdge;
            }
            if (localMousePosition.x() >= (windowWidth - resizeBorderThickness)) {
                return Qt::TopEdge | Qt::RightEdge;
            }
            return Qt::Edges{Qt::TopEdge};
        }
        if (localMousePosition.y() >= (windowHeight - resizeBorderThickness)) {
            if (localMousePosition.x() <= resizeBorderThickness) {
                return Qt::BottomEdge | Qt::LeftEdge;
            }
            if (localMousePosition.x() >= (windowWidth - resizeBorderThickness)) {
                return Qt::BottomEdge | Qt::RightEdge;
            }
            return Qt::Edges{Qt::BottomEdge};
        }
        if (localMousePosition.x() <= resizeBorderThickness) {
            return Qt::Edges{Qt::LeftEdge};
        }
        if (localMousePosition.x() >= (windowWidth - resizeBorderThickness)) {
            return Qt::Edges{Qt::RightEdge};
        }
        return Qt::Edges{};
    } ();
    const bool hitTestVisible = Utilities::isHitTestVisible(window);
    bool isInTitlebarArea = false;
    if ((window->windowState() == Qt::WindowMaximized)
            || (window->windowState() == Qt::WindowFullScreen)) {
        isInTitlebarArea = (localMousePosition.y() >= 0)
                && (localMousePosition.y() <= titleBarHeight)
                && (localMousePosition.x() >= 0)
                && (localMousePosition.x() <= windowWidth)
                && !hitTestVisible;
    }
    if (window->windowState() == Qt::WindowNoState) {
        isInTitlebarArea = (localMousePosition.y() > resizeBorderThickness)
                && (localMousePosition.y() <= titleBarHeight)
                && (localMousePosition.x() > resizeBorderThickness)
                && (localMousePosition.x() < (windowWidth - resizeBorderThickness))
                && !hitTestVisible;
    }

    // Determine if the mouse click occurred in the title bar
    static bool titlebarClicked = false;
    if (type == QEvent::MouseButtonPress) {
        if (isInTitlebarArea)
        {
            titlebarClicked = true;
        }
        else
        {
            titlebarClicked = false;
        }
    }

    if (type == QEvent::MouseButtonDblClick) {
        if (mouseEvent->button() != Qt::MouseButton::LeftButton) {
            return false;
        }
        if (isInTitlebarArea) {
            if (window->windowState() == Qt::WindowState::WindowFullScreen) {
                return false;
            }
            if (window->windowState() == Qt::WindowState::WindowMaximized) {
                window->showNormal();
            } else {
                window->showMaximized();
            }
            window->setCursor(Qt::ArrowCursor);
        }
    } else if (type == QEvent::MouseMove) {
        // Display resize indicators
        static bool cursorChanged = false;
        if ((window->windowState() == Qt::WindowState::WindowNoState) && resizable) {
            if (((edges & Qt::TopEdge) && (edges & Qt::LeftEdge))
                    || ((edges & Qt::BottomEdge) && (edges & Qt::RightEdge))) {
                window->setCursor(Qt::SizeFDiagCursor);
                cursorChanged = true;
            } else if (((edges & Qt::TopEdge) && (edges & Qt::RightEdge))
                       || ((edges & Qt::BottomEdge) && (edges & Qt::LeftEdge))) {
                window->setCursor(Qt::SizeBDiagCursor);
                cursorChanged = true;
            } else if ((edges & Qt::TopEdge) || (edges & Qt::BottomEdge)) {
                window->setCursor(Qt::SizeVerCursor);
                cursorChanged = true;
            } else if ((edges & Qt::LeftEdge) || (edges & Qt::RightEdge)) {
                window->setCursor(Qt::SizeHorCursor);
                cursorChanged = true;
            } else {
                if (cursorChanged) {
                    window->setCursor(Qt::ArrowCursor);
                    cursorChanged = false;
                }
            }
        }
        if ((mouseEvent->buttons() & Qt::LeftButton) && titlebarClicked) {
            if (edges == Qt::Edges{}) {
                if (isInTitlebarArea) {
#ifdef Q_OS_LINUX
            m_bLinuxWindowClicked = true;
#endif
                    if (!window->startSystemMove()) {
                        // ### FIXME: TO BE IMPLEMENTED!
                        qWarning() << "Current OS doesn't support QWindow::startSystemMove().";
                    }
                }
            }
        }

    } else if (type == QEvent::MouseButtonPress) {

        if (edges != Qt::Edges{}) {
            if ((window->windowState() == Qt::WindowState::WindowNoState) && !hitTestVisible && resizable) {
#ifdef Q_OS_LINUX
            m_bLinuxWindowClicked = true;
#endif
                if (!window->startSystemResize(edges)) {
                    // ### FIXME: TO BE IMPLEMENTED!
                    qWarning() << "Current OS doesn't support QWindow::startSystemResize().";
                }
            }
        }
    }
    //qDebug() << object->objectName() << " | " << event << " framelesshelper event filter";
    return QObject::eventFilter(object, event);
}

在Utilities实现XsendEvent发送鼠标Release事件。

void Utilities::X11ButtonRelease(const WId winId, QPoint pos, QPoint globalPos)
{
    const auto display = QX11Info::display();
    //const auto screen = QX11Info::appScreen();

    XEvent xevent;
    memset(&xevent, 0, sizeof(XEvent));

    xevent.type = ButtonRelease;
    xevent.xbutton.button = Button1;
    xevent.xbutton.window = winId;
    xevent.xbutton.x = pos.x();
    xevent.xbutton.y = pos.y();
    xevent.xbutton.x_root = globalPos.x();
    xevent.xbutton.y_root = globalPos.y();
    xevent.xbutton.display = display;

    XSendEvent(display, winId, False, ButtonReleaseMask, &xevent);
    XFlush(display);
}

参考地址: [https://www.zhihu.com/question/66830111](https://www.zhihu.com/question/66830111)

**Comment by altairwei** [comment]
2.0 已修复相关问题。

**Comment by wangwenx190** [comment]
@graycatya  @altairwei  方便给1.x分支提一个pr吗

**Comment by altairwei** [comment]
@wangwenx190 
这个问题我在 #75 提过，修复方法就是发送 ButtonRelease 给 X11 。Qt 的 startSystemMove 和 startSystemResize 实现的不完美。

**Comment by graycatya** [comment]
@wangwenx190 好的，我打算把mac下的Resize自己实现，我有一个以前完成的Resize基类先先测测，问题解决在弄成一个单独的分支。

**Comment by wangwenx190** [comment]
2.0已发布，待验证

**Comment by wangwenx190** [comment]
已确认问题尚未解决，正在着手解决

**Comment by wangwenx190** [comment]
最新的代码已解决此问题
